<?php
// module/Album/view/album/album/delete.phtml:

$title = 'Delete Podcast';
$url   = $this->url('podcast', ['action' => 'delete', 'id' => $id]);

$this->headTitle($title);
?>
<div class="section container full-height white">
    <div class="row container">
<h1><?= $this->escapeHtml($title) ?></h1>

<p>
    Are you sure that you want to delete
    "<?= $this->escapeHtml($podcast->title) ?>" by
    "<?= $this->escapeHtml($podcast->title) ?>"?
</p>

<form action="<?= $url ?>" method="post">
    <div class="form-group">
        <input type="hidden" name="id" value="<?= (int) $podcast->id ?>" />
        <input type="submit" class="btn btn-danger" name="del" value="Yes" />
        <input type="submit" class="btn btn-success" name="del" value="No" />
    </div>
</form>

    </div>
</div>