<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit Podcast';
$this->headTitle($title);
?>
<div class="section container full-height white">
    <div class="row container">
    <h1><?= $this->escapeHtml($title) ?></h1>
<?php
$podcast = $form->get('title');
$podcast->setAttribute('class', 'form-control');
$podcast->setAttribute('placeholder', 'Podcast title');

$artist = $form->get('artist');
$artist->setAttribute('class', 'form-control');
$artist->setAttribute('placeholder', 'Artist');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->setAttribute('action', $this->url('podcast', [
    'action' => 'edit',
    'id'     => $id,
]));
$form->prepare();

echo $this->form()->openTag($form);
?>
    <div class="form-group">
        <?= $this->formLabel($podcast) ?>
        <?= $this->formElement($podcast) ?>
        <?= $this->formElementErrors()->render($podcast, ['class' => 'help-block']) ?>
    </div>

    <div class="form-group">
        <?= $this->formLabel($artist) ?>
        <?= $this->formElement($artist) ?>
        <?= $this->formElementErrors()->render($artist, ['class' => 'help-block']) ?>
    </div>

<?php
echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();
?>
</div>
</div>

