<?php
// module/Album/view/album/album/index.phtml:

$title = 'My Podcasts';
$this->headTitle($title);
?>
<div class="section container full-height white">
    <div class="row container">
        <h1><?= $this->escapeHtml($title) ?></h1>
        <p>
            <a href="<?= $this->url('podcast', ['action' => 'add']) ?>">Add new podcast</a>
        </p>

        <table class="table">
            <tr>
                <th>Title</th>
                <th>Artist</th>
                <th>&nbsp;</th>
            </tr>
            <?php foreach ($podcasts as $podcast) : ?>
                <tr>
                    <td><?= $this->escapeHtml($podcast->title) ?></td>
                    <td><?= $this->escapeHtml($podcast->title) ?></td>
                    <td>
                        <a href="<?= $this->url('album', ['action' => 'edit', 'id' => $podcast->id]) ?>">Edit</a>
                        <a href="<?= $this->url('album', ['action' => 'delete', 'id' => $podcast->id]) ?>">Delete</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>
