<?php

namespace Player\Service;

use Laminas\Http\Client;
use Laminas\Http\Request;
use Laminas\Stdlib\ParametersInterface;
use Laminas\Json\Json;

class SportsInfoApi
{
    private $client_id;
    private $client_secret;
    private $access_token = null;
    private $base_url = "https://api.sportsinfosolutions.com/api/v1/nfl/";
    private $college_url = "https://api.sportsinfosolutions.com/api/v1/cfb/";
    private $default_array = [];

    /**
     * SportsInfoApi constructor.
     * @param $client_id
     * @param $client_secret
     */
    public function __construct($client_id, $client_secret)
    {
        $this->client_id = $client_id;
        $this->client_secret = $client_secret;
        $this->default_array = [
            "EntityType" => 1,
            "MetricGroup" => 1,
            "MetricGroupSubType" => 1,
            "GameFilters.Conference" => -1,
            "GameFilters.vsConference" => -1,
            "GameFilters.vsDivision" => -1,
            "GameFilters.HomeAway" => -1,
            "GameFilters.Team" => -1,
            "GameFilters.vsTeam" => -1,
            "GameFilters.MultipleTeams" => 0,
            "GameFilters.vsMultipleTeams" => 0,
            "GameFilters.IndoorOutdoor" => -1,
            "TimeFilters.SeasonFrom" => 2021,
            "TimeFilters.SeasonTo" => 2021,
            "TimeFilters.StartWeek" => 1,
            "TimeFilters.EndWeek" => 21,
            "SituationFilters.Quarters" => 0,
    //            "SituationFilters.Quarters" => 1,
    //            "SituationFilters.Quarters" => 2,
    //            "SituationFilters.Quarters" => 3,
    //            "SituationFilters.Quarters" => 4,
    //            "SituationFilters.Quarters" => 5,
            "SituationFilters.Downs" => 0,
    //            "SituationFilters.Downs" => 1,
    //            "SituationFilters.Downs" => 2,
    //            "SituationFilters.Downs" => 3,
    //            "SituationFilters.Downs" => 4,
            "SituationFilters.FieldPositionFromSide" => -1,
            "SituationFilters.FieldPositionFromYd" => -1,
            "SituationFilters.FieldPositionToSide" => -1,
            "SituationFilters.FieldPositionToYd" => -1,
            "SituationFilters.TimeRemainingFrom" => 0,
            "SituationFilters.TimeRemainingTo" => 900,
            "SituationFilters.DistanceFrom" => 0,
            "SituationFilters.DistanceTo" => 100,
            "SituationFilters.ScoreDiffFrom" => -50,
            "SituationFilters.ScoreDiffTo" => 50,
            "PersonnelFilters.WRs" => -1,
            "PersonnelFilters.WRFormation" => -1,
            "PersonnelFilters.TEs" => -1,
            "PersonnelFilters.DLs" => -1,
            "PersonnelFilters.DBs" => -1,
            "PersonnelFilters.Shotgun" => -1,
            "PersonnelFilters.RBs" => -1,
            "PersonnelFilters.RBFormation" => -1,
            "PersonnelFilters.OLs" => -1,
            "PersonnelFilters.LBs" => -1,
            "PersonnelFilters.NoHuddle" => -1,
            "PassingFilters.PlayAction" => -1,
            "PassingFilters.Pressured" => -1,
            "PassingFilters.InPocket" => -1,
            "PassingFilters.RPO" => -1,
            "PassingFilters.AnyMotion" => -1,
            "PassingFilters.JetMotion" => -1,
            "PassingFilters.TargetInMotion" => -1,
            "PassingFilters.PastSticks" => -1,
            "PassingFilters.ThrowType" => 0,
    //            "PassingFilters.ThrowType" => 1,
    //            "PassingFilters.ThrowType" => 2,
    //            "PassingFilters.ThrowType" => 3,
    //            "PassingFilters.ThrowType" => 4,
            "PassingFilters.TargetLinedUp" => 0,
    //            "PassingFilters.TargetLinedUp" => 1,
    //            "PassingFilters.TargetLinedUp" => 2,
    //            "PassingFilters.TargetLinedUp" => 3,
    //            "PassingFilters.TargetLinedUp" => 4,
            "PassingFilters.PassDir" => 0,
    //            "PassingFilters.PassDir" => 1,
    //            "PassingFilters.PassDir" => 2,
    //            "PassingFilters.PassDir" => 3,
    //            "PassingFilters.PassDir" => 4,
    //            "PassingFilters.PassDir" => 5,
            "PassingFilters.TargetPos" => 0,
    //            "PassingFilters.TargetPos" => 2,
    //            "PassingFilters.TargetPos" => 3,
    //            "PassingFilters.TargetPos" => 4,
    //            "PassingFilters.TargetPos" => 5,
            "PassingFilters.Schemes" => -999,
    //            "PassingFilters.Schemes" => 0,
    //            "PassingFilters.Schemes" => 1,
    //            "PassingFilters.Schemes" => 2,
    //            "PassingFilters.Schemes" => 5,
    //            "PassingFilters.Schemes" => 3,
    //            "PassingFilters.Schemes" => 4,
    //            "PassingFilters.Schemes" => 6,
    //            "PassingFilters.Schemes" => 10,
    //            "PassingFilters.Schemes" => 11,
    //            "PassingFilters.Schemes" => 12,
    //            "PassingFilters.Schemes" => 13,
    //            "PassingFilters.Schemes" => 14,
    //            "PassingFilters.Schemes" => 15,
    //            "PassingFilters.Schemes" => 16,
    //            "PassingFilters.Schemes" => 17,
            "PassingFilters.RouteType" => 0,
    //            "PassingFilters.RouteType" => 1,
    //            "PassingFilters.RouteType" => 2,
    //            "PassingFilters.RouteType" => 3,
    //            "PassingFilters.RouteType" => 4,
    //            "PassingFilters.RouteType" => 5,
    //            "PassingFilters.RouteType" => 6,
    //            "PassingFilters.RouteType" => 7,
    //            "PassingFilters.RouteType" => 8,
    //            "PassingFilters.RouteType" => 9,
    //            "PassingFilters.RouteType" => 10,
    //            "PassingFilters.RouteType" => 11,
    //            "PassingFilters.RouteType" => 12,
    //            "PassingFilters.RouteType" => 13,
    //            "PassingFilters.RouteType" => 14,
    //            "PassingFilters.RouteType" => 15,
    //            "PassingFilters.RouteType" => 16,
    //            "PassingFilters.RouteType" => 17,
    //            "PassingFilters.RouteType" => 18,
    //            "PassingFilters.RouteType" => 19,
    //            "PassingFilters.RouteType" => 20,
    //            "PassingFilters.RouteType" => 26,
    //            "PassingFilters.RouteType" => 27,
    //            "PassingFilters.RouteType" => 28,
    //            "PassingFilters.RouteType" => 29,
    //            "PassingFilters.RouteType" => 30,
    //            "PassingFilters.RouteType" => 34,
    //            "PassingFilters.RouteType" => 35,
    //            "PassingFilters.RouteType" => 39,
    //            "PassingFilters.RouteType" => 42,
    //            "PassingFilters.RouteType" => 43,
            "PassingFilters.DropType" => 0,
    //            "PassingFilters.DropType" => 1,
    //            "PassingFilters.DropType" => 2,
    //            "PassingFilters.DropType" => 3,
    //            "PassingFilters.DropType" => 4,
    //            "PassingFilters.DropType" => 5,
    //            "PassingFilters.DropType" => 6,
    //            "PassingFilters.DropType" => 7,
    //            "PassingFilters.DropType" => 8,
    //            "PassingFilters.DropType" => 9,
    //            "PassingFilters.DropType" => 10,
    //            "PassingFilters.DropType" => 12,
    //            "PassingFilters.DropType" => 13,
    //            "PassingFilters.DropType" => 14,
    //            "PassingFilters.DropType" => 15,
    //            "PassingFilters.DropType" => 11,
            "PassingFilters.MenInBox" => 0,
    //            "PassingFilters.MenInBox" => 4,
    //            "PassingFilters.MenInBox" => 5,
    //            "PassingFilters.MenInBox" => 6,
    //            "PassingFilters.MenInBox" => 7,
    //            "PassingFilters.MenInBox" => 8,
    //            "PassingFilters.MenInBox" => 9,
            "PassingFilters.QBAtPassType" => 0,
    //            "PassingFilters.QBAtPassType" => 1,
    //            "PassingFilters.QBAtPassType" => 2,
    //            "PassingFilters.QBAtPassType" => 3,
            "PassingFilters.PassRushers" => 0,
    //            "PassingFilters.PassRushers" => 3,
    //            "PassingFilters.PassRushers" => 4,
    //            "PassingFilters.PassRushers" => 5,
    //            "PassingFilters.PassRushers" => 6,
    //            "PassingFilters.PassRushers" => 7,
    //            "PassingFilters.PassRushers" => 8,
            "PassingFilters.MinAirYards" => -20,
            "PassingFilters.MaxAirYards" => 100,
            "RushingFilters.AnyMotion" => -1,
            "RushingFilters.JetMotion" => -1,
            "RushingFilters.BlownBlock" => -1,
            "RushingFilters.LeadBlocker" => -1,
            "RushingFilters.UsedDesignedGap" => -1,
            "RushingFilters.RPO" => -1,
            "RushingFilters.ReadOption" => -1,
            "RushingFilters.RunType" => 0,
    //            "RushingFilters.RunType" => 1,
    //            "RushingFilters.RunType" => 2,
    //            "RushingFilters.RunType" => 3,
    //            "RushingFilters.RunType" => 4,
    //            "RushingFilters.RunType" => 5,
    //            "RushingFilters.RunType" => 7,
    //            "RushingFilters.RunType" => 10,
    //            "RushingFilters.RunType" => 13,
    //            "RushingFilters.RunType" => 15,
    //            "RushingFilters.RunType" => 16,
    //            "RushingFilters.RunType" => 22,
    //            "RushingFilters.RunType" => 23,
    //            "RushingFilters.RunType" => 28,
    //            "RushingFilters.RunType" => 29,
    //            "RushingFilters.RunType" => 30,
    //            "RushingFilters.RunType" => 31,
    //            "RushingFilters.RunType" => 33,
    //            "RushingFilters.RunType" => 34,
    //            "RushingFilters.RunType" => 35,
    //            "RushingFilters.RunType" => 36,
    //            "RushingFilters.RunType" => 8,
    //            "RushingFilters.RunType" => 14,
    //            "RushingFilters.RunType" => 18,
    //            "RushingFilters.RunType" => 19,
    //            "RushingFilters.RunType" => 9,
    //            "RushingFilters.RunType" => 17,
    //            "RushingFilters.RunType" => 20,
    //            "RushingFilters.RunType" => 24,
    //            "RushingFilters.RunType" => 21,
    //            "RushingFilters.RunType" => 25,
    //            "RushingFilters.RunType" => 26,
    //            "RushingFilters.RunType" => 27,
    //            "RushingFilters.RunType" => 32,
    //            "RushingFilters.RunType" => 11,
    //            "RushingFilters.RunType" => 12,
            "RushingFilters.RunDirection" => 0,
    //            "RushingFilters.RunDirection" => 5,
    //            "RushingFilters.RunDirection" => 6,
    //            "RushingFilters.RunDirection" => 1,
    //            "RushingFilters.RunDirection" => 4,
    //            "RushingFilters.RunDirection" => 3,
    //            "RushingFilters.RunDirection" => 7,
    //            "RushingFilters.RunDirection" => 2,
            "RushingFilters.BlockScheme" => 0,
    //            "RushingFilters.BlockScheme" => 1,
    //            "RushingFilters.BlockScheme" => 10,
    //            "RushingFilters.BlockScheme" => 11,
    //            "RushingFilters.BlockScheme" => 12,
    //            "RushingFilters.BlockScheme" => 2,
    //            "RushingFilters.BlockScheme" => 5,
    //            "RushingFilters.BlockScheme" => 3,
    //            "RushingFilters.BlockScheme" => 13,
    //            "RushingFilters.BlockScheme" => 14,
    //            "RushingFilters.BlockScheme" => 15,
    //            "RushingFilters.BlockScheme" => 16,
    //            "RushingFilters.BlockScheme" => 17,
            "RushingFilters.BallCarrierPos" => 0,
    //            "RushingFilters.BallCarrierPos" => 1,
    //            "RushingFilters.BallCarrierPos" => 2,
    //            "RushingFilters.BallCarrierPos" => 3,
    //            "RushingFilters.BallCarrierPos" => 4,
    //            "RushingFilters.BallCarrierPos" => 5,
            "RushingFilters.DefInBox" => 0,
    //            "RushingFilters.DefInBox" => 4,
    //            "RushingFilters.DefInBox" => 5,
    //            "RushingFilters.DefInBox" => 6,
    //            "RushingFilters.DefInBox" => 7,
    //            "RushingFilters.DefInBox" => 8,
    //            "RushingFilters.DefInBox" => 9,
            "RushingFilters.MinFirstContact" => -20,
            "RushingFilters.MaxFirstContact" => 100,
            "ReceivingFilters.InMotion" => -1,
            "ReceivingFilters.Catchable" => -1,
            "ReceivingFilters.BrokenPlay" => -1,
            "ReceivingFilters.EndZoneTarget" => -1,
            "ReceivingFilters.IsolatedWR" => -1,
            "ReceivingFilters.QBPressured" => -1,
            "ReceivingFilters.OnTarget" => -1,
            "ReceivingFilters.TargetLinedUp" => 0,
    //            "ReceivingFilters.TargetLinedUp" => 1,
    //            "ReceivingFilters.TargetLinedUp" => 2,
    //            "ReceivingFilters.TargetLinedUp" => 3,
    //            "ReceivingFilters.TargetLinedUp" => 4,
            "ReceivingFilters.PassDir" => 0,
    //            "ReceivingFilters.PassDir" => 1,
    //            "ReceivingFilters.PassDir" => 2,
    //            "ReceivingFilters.PassDir" => 3,
    //            "ReceivingFilters.PassDir" => 4,
    //            "ReceivingFilters.PassDir" => 5,
            "ReceivingFilters.TargetPos" => 0,
    //            "ReceivingFilters.TargetPos" => 2,
    //            "ReceivingFilters.TargetPos" => 3,
    //            "ReceivingFilters.TargetPos" => 4,
    //            "ReceivingFilters.TargetPos" => 5,
            "ReceivingFilters.Schemes" => -999,
    //            "ReceivingFilters.Schemes" => 0,
    //            "ReceivingFilters.Schemes" => 1,
    //            "ReceivingFilters.Schemes" => 2,
    //            "ReceivingFilters.Schemes" => 5,
    //            "ReceivingFilters.Schemes" => 3,
    //            "ReceivingFilters.Schemes" => 4,
    //            "ReceivingFilters.Schemes" => 6,
    //            "ReceivingFilters.Schemes" => 10,
    //            "ReceivingFilters.Schemes" => 11,
    //            "ReceivingFilters.Schemes" => 12,
    //            "ReceivingFilters.Schemes" => 13,
    //            "ReceivingFilters.Schemes" => 14,
    //            "ReceivingFilters.Schemes" => 15,
    //            "ReceivingFilters.Schemes" => 16,
    //            "ReceivingFilters.Schemes" => 17,
            "ReceivingFilters.RecAlignment" => 0,
    //            "ReceivingFilters.RecAlignment" => 1,
    //            "ReceivingFilters.RecAlignment" => 2,
    //            "ReceivingFilters.RecAlignment" => 3,
    //            "ReceivingFilters.RecAlignment" => 4,
    //            "ReceivingFilters.RecAlignment" => 5,
    //            "ReceivingFilters.RecAlignment" => 6,
    //            "ReceivingFilters.RecAlignment" => 7,
            "ReceivingFilters.RouteType" => 0,
    //            "ReceivingFilters.RouteType" => 1,
    //            "ReceivingFilters.RouteType" => 2,
    //            "ReceivingFilters.RouteType" => 3,
    //            "ReceivingFilters.RouteType" => 4,
    //            "ReceivingFilters.RouteType" => 5,
    //            "ReceivingFilters.RouteType" => 6,
    //            "ReceivingFilters.RouteType" => 7,
    //            "ReceivingFilters.RouteType" => 8,
    //            "ReceivingFilters.RouteType" => 9,
    //            "ReceivingFilters.RouteType" => 10,
    //            "ReceivingFilters.RouteType" => 11,
    //            "ReceivingFilters.RouteType" => 12,
    //            "ReceivingFilters.RouteType" => 13,
    //            "ReceivingFilters.RouteType" => 14,
    //            "ReceivingFilters.RouteType" => 15,
    //            "ReceivingFilters.RouteType" => 16,
    //            "ReceivingFilters.RouteType" => 17,
    //            "ReceivingFilters.RouteType" => 18,
    //            "ReceivingFilters.RouteType" => 19,
    //            "ReceivingFilters.RouteType" => 20,
    //            "ReceivingFilters.RouteType" => 26,
    //            "ReceivingFilters.RouteType" => 27,
    //            "ReceivingFilters.RouteType" => 28,
    //            "ReceivingFilters.RouteType" => 29,
    //            "ReceivingFilters.RouteType" => 30,
    //            "ReceivingFilters.RouteType" => 34,
    //            "ReceivingFilters.RouteType" => 35,
    //            "ReceivingFilters.RouteType" => 39,
    //            "ReceivingFilters.RouteType" => 42,
    //            "ReceivingFilters.RouteType" => 43,
            "ReceivingFilters.DropType" => 0,
    //            "ReceivingFilters.DropType" => 1,
    //            "ReceivingFilters.DropType" => 2,
    //            "ReceivingFilters.DropType" => 3,
    //            "ReceivingFilters.DropType" => 4,
    //            "ReceivingFilters.DropType" => 5,
    //            "ReceivingFilters.DropType" => 6,
    //            "ReceivingFilters.DropType" => 7,
    //            "ReceivingFilters.DropType" => 8,
    //            "ReceivingFilters.DropType" => 9,
    //            "ReceivingFilters.DropType" => 10,
    //            "ReceivingFilters.DropType" => 12,
    //            "ReceivingFilters.DropType" => 13,
    //            "ReceivingFilters.DropType" => 14,
    //            "ReceivingFilters.DropType" => 15,
    //            "ReceivingFilters.DropType" => 11,
            "ReceivingFilters.MotionType" => 0,
    //            "ReceivingFilters.MotionType" => 1,
    //            "ReceivingFilters.MotionType" => 2,
    //            "ReceivingFilters.MotionType" => 3,
    //            "ReceivingFilters.MotionType" => 4,
    //            "ReceivingFilters.MotionType" => 5,
    //            "ReceivingFilters.MotionType" => 6,
    //            "ReceivingFilters.MotionType" => 7,
    //            "ReceivingFilters.MotionType" => 8,
    //            "ReceivingFilters.MotionType" => 9,
    //            "ReceivingFilters.MotionType" => 10,
    //            "ReceivingFilters.MotionType" => 11,
    //            "ReceivingFilters.MotionType" => 12,
    //            "ReceivingFilters.MotionType" => 13,
    //            "ReceivingFilters.MotionType" => 14,
    //            "ReceivingFilters.MotionType" => 15,
    //            "ReceivingFilters.MotionType" => 16,
    //            "ReceivingFilters.MotionType" => 17,
    //            "ReceivingFilters.MotionType" => 18,
    //            "ReceivingFilters.MotionType" => 19,
            "ReceivingFilters.MenInBox" => 0,
    //            "ReceivingFilters.MenInBox" => 4,
    //            "ReceivingFilters.MenInBox" => 5,
    //            "ReceivingFilters.MenInBox" => 6,
    //            "ReceivingFilters.MenInBox" => 7,
    //            "ReceivingFilters.MenInBox" => 8,
    //            "ReceivingFilters.MenInBox" => 9,
            "ReceivingFilters.PassRushers" => 0,
    //            "ReceivingFilters.PassRushers" => 3,
    //            "ReceivingFilters.PassRushers" => 4,
    //            "ReceivingFilters.PassRushers" => 5,
    //            "ReceivingFilters.PassRushers" => 6,
    //            "ReceivingFilters.PassRushers" => 7,
    //            "ReceivingFilters.PassRushers" => 8,
            "ReceivingFilters.MinAirYards" => -20,
            "ReceivingFilters.MaxAirYards" => 100,
            "RunDefenseFilters.AnyMotion" => -1,
            "RunDefenseFilters.JetMotion" => -1,
            "RunDefenseFilters.IsDesignedRun" => -1,
            "RunDefenseFilters.SideOfCenter" => -1,
            "RunDefenseFilters.RunType" => 0,
    //            "RunDefenseFilters.RunType" => 1,
    //            "RunDefenseFilters.RunType" => 2,
    //            "RunDefenseFilters.RunType" => 3,
    //            "RunDefenseFilters.RunType" => 4,
    //            "RunDefenseFilters.RunType" => 5,
    //            "RunDefenseFilters.RunType" => 7,
    //            "RunDefenseFilters.RunType" => 10,
    //            "RunDefenseFilters.RunType" => 13,
    //            "RunDefenseFilters.RunType" => 15,
    //            "RunDefenseFilters.RunType" => 16,
    //            "RunDefenseFilters.RunType" => 22,
    //            "RunDefenseFilters.RunType" => 23,
    //            "RunDefenseFilters.RunType" => 28,
    //            "RunDefenseFilters.RunType" => 29,
    //            "RunDefenseFilters.RunType" => 30,
    //            "RunDefenseFilters.RunType" => 31,
    //            "RunDefenseFilters.RunType" => 33,
    //            "RunDefenseFilters.RunType" => 34,
    //            "RunDefenseFilters.RunType" => 35,
    //            "RunDefenseFilters.RunType" => 36,
    //            "RunDefenseFilters.RunType" => 8,
    //            "RunDefenseFilters.RunType" => 14,
    //            "RunDefenseFilters.RunType" => 18,
    //            "RunDefenseFilters.RunType" => 19,
    //            "RunDefenseFilters.RunType" => 9,
    //            "RunDefenseFilters.RunType" => 17,
    //            "RunDefenseFilters.RunType" => 20,
    //            "RunDefenseFilters.RunType" => 24,
    //            "RunDefenseFilters.RunType" => 21,
    //            "RunDefenseFilters.RunType" => 25,
    //            "RunDefenseFilters.RunType" => 26,
    //            "RunDefenseFilters.RunType" => 27,
    //            "RunDefenseFilters.RunType" => 32,
    //            "RunDefenseFilters.RunType" => 11,
    //            "RunDefenseFilters.RunType" => 12,
            "RunDefenseFilters.BlockScheme" => 0,
    //            "RunDefenseFilters.BlockScheme" => 1,
    //            "RunDefenseFilters.BlockScheme" => 2,
    //            "RunDefenseFilters.BlockScheme" => 3,
    //            "RunDefenseFilters.BlockScheme" => 4,
    //            "RunDefenseFilters.BlockScheme" => 5,
    //            "RunDefenseFilters.BlockScheme" => 6,
    //            "RunDefenseFilters.BlockScheme" => 7,
    //            "RunDefenseFilters.BlockScheme" => 8,
    //            "RunDefenseFilters.BlockScheme" => 9,
    //            "RunDefenseFilters.BlockScheme" => 10,
    //            "RunDefenseFilters.BlockScheme" => 11,
    //            "RunDefenseFilters.BlockScheme" => 12,
    //            "RunDefenseFilters.BlockScheme" => 13,
    //            "RunDefenseFilters.BlockScheme" => 14,
    //            "RunDefenseFilters.BlockScheme" => 15,
    //            "RunDefenseFilters.BlockScheme" => 16,
    //            "RunDefenseFilters.BlockScheme" => 17,
    //            "RunDefenseFilters.RunDirection" => 0,
    //            "RunDefenseFilters.RunDirection" => 5,
    //            "RunDefenseFilters.RunDirection" => 6,
    //            "RunDefenseFilters.RunDirection" => 1,
    //            "RunDefenseFilters.RunDirection" => 4,
    //            "RunDefenseFilters.RunDirection" => 3,
    //            "RunDefenseFilters.RunDirection" => 7,
    //            "RunDefenseFilters.RunDirection" => 2,
    //            "RunDefenseFilters.DefenderPos" => 0,
    //            "RunDefenseFilters.DefenderPos" => 11,
    //            "RunDefenseFilters.DefenderPos" => 9,
    //            "RunDefenseFilters.DefenderPos" => 10,
    //            "RunDefenseFilters.DefenderPos" => 13,
    //            "RunDefenseFilters.DefenderPos" => 12,
            "RunDefenseFilters.DefInBox" => 0,
    //            "RunDefenseFilters.DefInBox" => 4,
    //            "RunDefenseFilters.DefInBox" => 5,
    //            "RunDefenseFilters.DefInBox" => 6,
    //            "RunDefenseFilters.DefInBox" => 7,
    //            "RunDefenseFilters.DefInBox" => 8,
    //            "RunDefenseFilters.DefInBox" => 9,
            "RunDefenseFilters.Techniques" => -1,
    //            "RunDefenseFilters.Techniques" => 0,
    //            "RunDefenseFilters.Techniques" => 1,
    //            "RunDefenseFilters.Techniques" => 2,
    //            "RunDefenseFilters.Techniques" => 3,
    //            "RunDefenseFilters.Techniques" => 4,
    //            "RunDefenseFilters.Techniques" => 5,
    //            "RunDefenseFilters.Techniques" => 6,
    //            "RunDefenseFilters.Techniques" => 7,
    //            "RunDefenseFilters.Techniques" => 8,
    //            "RunDefenseFilters.Techniques" => 9,
    //            "RunDefenseFilters.Techniques" => 10,
            "PassDefenseFilters.AnyMotion" => -1,
            "PassDefenseFilters.JetMotion" => -1,
            "PassDefenseFilters.QBPressured" => -1,
            "PassDefenseFilters.PlayAction" => -1,
            "PassDefenseFilters.RouteType" => 0,
    //            "PassDefenseFilters.RouteType" => 1,
    //            "PassDefenseFilters.RouteType" => 2,
    //            "PassDefenseFilters.RouteType" => 3,
    //            "PassDefenseFilters.RouteType" => 4,
    //            "PassDefenseFilters.RouteType" => 5,
    //            "PassDefenseFilters.RouteType" => 6,
    //            "PassDefenseFilters.RouteType" => 7,
    //            "PassDefenseFilters.RouteType" => 8,
    //            "PassDefenseFilters.RouteType" => 9,
    //            "PassDefenseFilters.RouteType" => 10,
    //            "PassDefenseFilters.RouteType" => 11,
    //            "PassDefenseFilters.RouteType" => 12,
    //            "PassDefenseFilters.RouteType" => 13,
    //            "PassDefenseFilters.RouteType" => 14,
    //            "PassDefenseFilters.RouteType" => 15,
    //            "PassDefenseFilters.RouteType" => 16,
    //            "PassDefenseFilters.RouteType" => 17,
    //            "PassDefenseFilters.RouteType" => 18,
    //            "PassDefenseFilters.RouteType" => 19,
    //            "PassDefenseFilters.RouteType" => 20,
    //            "PassDefenseFilters.RouteType" => 26,
    //            "PassDefenseFilters.RouteType" => 27,
    //            "PassDefenseFilters.RouteType" => 28,
    //            "PassDefenseFilters.RouteType" => 29,
    //            "PassDefenseFilters.RouteType" => 30,
    //            "PassDefenseFilters.RouteType" => 34,
    //            "PassDefenseFilters.RouteType" => 35,
    //            "PassDefenseFilters.RouteType" => 39,
    //            "PassDefenseFilters.RouteType" => 42,
    //            "PassDefenseFilters.RouteType" => 43,
            "PassDefenseFilters.DefenderPos" => 0,
    //            "PassDefenseFilters.DefenderPos" => 12,
    //            "PassDefenseFilters.DefenderPos" => 13,
    //            "PassDefenseFilters.DefenderPos" => 11,
    //            "PassDefenseFilters.DefenderPos" => 9,
            "PassDefenseFilters.Schemes" => -999,
            "PassDefenseFilters.Schemes" => 0,
            "PassDefenseFilters.Schemes" => 1,
            "PassDefenseFilters.Schemes" => 2,
            "PassDefenseFilters.Schemes" => 5,
            "PassDefenseFilters.Schemes" => 3,
            "PassDefenseFilters.Schemes" => 4,
            "PassDefenseFilters.Schemes" => 6,
            "PassDefenseFilters.Schemes" => 10,
            "PassDefenseFilters.Schemes" => 11,
            "PassDefenseFilters.Schemes" => 12,
            "PassDefenseFilters.Schemes" => 13,
            "PassDefenseFilters.Schemes" => 14,
            "PassDefenseFilters.Schemes" => 15,
            "PassDefenseFilters.Schemes" => 16,
            "PassDefenseFilters.Schemes" => 17,
            "PassDefenseFilters.PassDir" => 0,
            "PassDefenseFilters.PassDir" => 1,
            "PassDefenseFilters.PassDir" => 2,
            "PassDefenseFilters.PassDir" => 3,
            "PassDefenseFilters.PassDir" => 4,
            "PassDefenseFilters.PassDir" => 5,
            "PassDefenseFilters.TargetLinedUp" => 0,
            "PassDefenseFilters.TargetLinedUp" => 1,
            "PassDefenseFilters.TargetLinedUp" => 2,
            "PassDefenseFilters.TargetLinedUp" => 3,
            "PassDefenseFilters.TargetLinedUp" => 4,
            "PassDefenseFilters.ReceiverPos" => 0,
            "PassDefenseFilters.ReceiverPos" => 2,
            "PassDefenseFilters.ReceiverPos" => 4,
            "PassDefenseFilters.ReceiverPos" => 5,
            "PassDefenseFilters.DefenderLinedUp" => 0,
            "PassDefenseFilters.DefenderLinedUp" => 1,
            "PassDefenseFilters.DefenderLinedUp" => 2,
            "PassDefenseFilters.DefenderLinedUp" => 3,
            "PassDefenseFilters.DefenderLinedUp" => 4,
            "PassDefenseFilters.DefenderLinedUp" => 5,
            "PassDefenseFilters.DefenderLinedUp" => 6,
            "PassDefenseFilters.Rushers" => 0,
            "PassDefenseFilters.Rushers" => 3,
            "PassDefenseFilters.Rushers" => 4,
            "PassDefenseFilters.Rushers" => 5,
            "PassDefenseFilters.Rushers" => 6,
            "PassDefenseFilters.Rushers" => 7,
            "PassDefenseFilters.Rushers" => 8,
            "PassDefenseFilters.MinAirYards" => -20,
            "PassDefenseFilters.MaxAirYards" => 100,
            "PassRushFilters.AnyMotion" => -1,
            "PassRushFilters.JetMotion" => -1,
            "PassRushFilters.PlayAction" => -1,
            "PassRushFilters.SideOfCenter" => -1,
            "PassRushFilters.Schemes" => -999,
            "PassRushFilters.Schemes" => 0,
            "PassRushFilters.Schemes" => 1,
            "PassRushFilters.Schemes" => 2,
            "PassRushFilters.Schemes" => 5,
            "PassRushFilters.Schemes" => 3,
            "PassRushFilters.Schemes" => 4,
            "PassRushFilters.Schemes" => 6,
            "PassRushFilters.Schemes" => 10,
            "PassRushFilters.Schemes" => 11,
            "PassRushFilters.Schemes" => 12,
            "PassRushFilters.Schemes" => 13,
            "PassRushFilters.Schemes" => 14,
            "PassRushFilters.Schemes" => 15,
            "PassRushFilters.Schemes" => 16,
            "PassRushFilters.Schemes" => 17,
            "PassRushFilters.DefenderPos" => 0,
            "PassRushFilters.DefenderPos" => 9,
            "PassRushFilters.DefenderPos" => 10,
            "PassRushFilters.DefenderPos" => 11,
            "PassRushFilters.DefenderPos" => 13,
            "PassRushFilters.DefenderPos" => 12,
            "PassRushFilters.DropType" => 0,
            "PassRushFilters.DropType" => 1,
            "PassRushFilters.DropType" => 2,
            "PassRushFilters.DropType" => 3,
            "PassRushFilters.DropType" => 4,
            "PassRushFilters.DropType" => 5,
            "PassRushFilters.DropType" => 6,
            "PassRushFilters.DropType" => 7,
            "PassRushFilters.DropType" => 8,
            "PassRushFilters.DropType" => 9,
            "PassRushFilters.DropType" => 10,
            "PassRushFilters.DropType" => 12,
            "PassRushFilters.DropType" => 13,
            "PassRushFilters.DropType" => 14,
            "PassRushFilters.DropType" => 15,
            "PassRushFilters.DropType" => 11,
            "PassRushFilters.Rushers" => 0,
            "PassRushFilters.Rushers" => 3,
            "PassRushFilters.Rushers" => 4,
            "PassRushFilters.Rushers" => 5,
            "PassRushFilters.Rushers" => 6,
            "PassRushFilters.Rushers" => 7,
            "PassRushFilters.Rushers" => 8,
            "PassRushFilters.Techniques" => -1,
            "PassRushFilters.Techniques" => 0,
            "PassRushFilters.Techniques" => 1,
            "PassRushFilters.Techniques" => 2,
            "PassRushFilters.Techniques" => 3,
            "PassRushFilters.Techniques" => 4,
            "PassRushFilters.Techniques" => 5,
            "PassRushFilters.Techniques" => 6,
            "PassRushFilters.Techniques" => 7,
            "PassRushFilters.Techniques" => 8,
            "PassRushFilters.Techniques" => 9,
            "PassRushFilters.Techniques" => 10,
            "PassRushFilters.MinAirYards" => -20,
            "PassRushFilters.MaxAirYards" => 100,
            "PassRushFilters.PuntType" => 0,
            "PassRushFilters.PuntType" => 1,
            "PassRushFilters.PuntType" => 2,
            "PassRushFilters.PuntType" => 3,
            "PassRushFilters.PuntType" => 4,
            "KickingFilters.MinFGYards" => 0,
            "KickingFilters.MaxFGYards" => 65,
            "BlockFilters.BlockScheme" => 0,
            "BlockFilters.BlockScheme" => 1,
            "BlockFilters.BlockScheme" => 10,
            "BlockFilters.BlockScheme" => 11,
            "BlockFilters.BlockScheme" => 12,
            "BlockFilters.BlockScheme" => 2,
            "BlockFilters.BlockScheme" => 3,
            "BlockFilters.BlockScheme" => 8,
            "BlockFilters.BlockScheme" => 9,
            "BlockFilters.BlockScheme" => 13,
            "BlockFilters.BlockScheme" => 14,
            "BlockFilters.BlockScheme" => 15,
            "BlockFilters.BlockScheme" => 16,
            "BlockFilters.BlockScheme" => 17,
            "BlockFilters.DefInBox" => 0,
            "BlockFilters.DefInBox" => 4,
            "BlockFilters.DefInBox" => 5,
            "BlockFilters.DefInBox" => 6,
            "BlockFilters.DefInBox" => 7,
            "BlockFilters.DefInBox" => 8,
            "BlockFilters.DefInBox" => 9,
            "BlockFilters.LinedUp" => 0,
            "BlockFilters.LinedUp" => 1,
            "BlockFilters.LinedUp" => 2,
            "BlockFilters.LinedUp" => 3,
            "BlockFilters.LinedUp" => 4,
            "BlockFilters.LinedUp" => 5,
            "BlockFilters.LinedUp" => 6,
            "BlockFilters.LinedUp" => 7,
            "BlockFilters.BlockingPosition" => 0,
            "BlockFilters.BlockingPosition" => 1,
            "BlockFilters.BlockingPosition" => 2,
            "BlockFilters.BlockingPosition" => 3,
            "BlockFilters.BlockingPosition" => 4,
            "BlockFilters.BlockingPosition" => 5,
            "BlockFilters.BlockingPosition" => 6,
            "BlockFilters.PlayAction" => -1,
            "BlockFilters.InPocket" => -1,
            "BlockFilters.DropType" => 0,
    //            "BlockFilters.DropType" => 1,
    //            "BlockFilters.DropType" => 2,
    //            "BlockFilters.DropType" => 3,
    //            "BlockFilters.DropType" => 4,
    //            "BlockFilters.DropType" => 5,
    //            "BlockFilters.DropType" => 6,
    //            "BlockFilters.DropType" => 7,
    //            "BlockFilters.DropType" => 8,
    //            "BlockFilters.DropType" => 9,
    //            "BlockFilters.DropType" => 10,
    //            "BlockFilters.DropType" => 12,
    //            "BlockFilters.DropType" => 13,
    //            "BlockFilters.DropType" => 14,
    //            "BlockFilters.DropType" => 15,
    //            "BlockFilters.DropType" => 11,
            "BlockFilters.PassRushers" => 0,
    //            "BlockFilters.PassRushers" => 3,
    //            "BlockFilters.PassRushers" => 4,
    //            "BlockFilters.PassRushers" => 5,
    //            "BlockFilters.PassRushers" => 6,
    //            "BlockFilters.PassRushers" => 7,
    //            "BlockFilters.PassRushers" => 8,
            "BlockFilters.RunDirection" => 0,
    //            "BlockFilters.RunDirection" => 5,
    //            "BlockFilters.RunDirection" => 6,
    //            "BlockFilters.RunDirection" => 1,
    //            "BlockFilters.RunDirection" => 4,
    //            "BlockFilters.RunDirection" => 3,
    //            "BlockFilters.RunDirection" => 7,
    //            "BlockFilters.RunDirection" => 2,
            "AdjustedBB.TeamId" => -1,
            "AdjustedBB.BlockingPosition" => 0,
    //            "AdjustedBB.BlockingPosition" => 1,
    //            "AdjustedBB.BlockingPosition" => 2,
    //            "AdjustedBB.BlockingPosition" => 3,
    //            "AdjustedBB.BlockingPosition" => 4,
    //            "AdjustedBB.BlockingPosition" => 5,
    //            "AdjustedBB.BlockingPosition" => 6,
            "PassingFilters.MinAttempts" => 1,
            "RushingFilters.MinCarries" => 5,
            "ReceivingFilters.MinTargets" => 1,
            "PassDefenseFilters.MinTargets" => 1,
            "PassDefenseFilters.MinAttempts" => 1,
            "RunDefenseFilters.MinTackles" => 1,
            "RunDefenseFilters.MinCarries" => 1,
            "PassRushFilters.MinPassRushes" => 1,
            "PassRushFilters.MinPressures" => 1,
            "ReturnFIlters.MinKR" => 1,
            "ReturnFilters.MinPR" => 1,
            "PassRushFilters.MinPunt" => 1,
            "KickingFilters.MinFG" => 1,
            "BlockFilters.MinSnaps" => 10,
            "AdjustedBB.MinPassSnaps" => 1
        ];
    }

    private function authorize()
    {
        $request = new Request();
        $uri = "https://auth.sportsinfosolutions.com/connect/token";
        $request->setUri($uri);
        $request->setMethod("POST");
        $request->getPost()->set('client_id', $this->client_id);
        $request->getPost()->set('client_secret', $this->client_secret);
        $request->getPost()->set('grant_type', 'client_credentials');
        $request->getPost()->set('scope', 'sisapi');
        $client = new Client();
        $response = $client->send($request);
        $html = $response->getBody();
        $json = Json::decode($html,1);
        $this->access_token = $json['access_token'];
    }

    public function makeRequest($endpoint)
    {
        if ($this->access_token == null) {
            $this->authorize();
        }
        $request = new Request();
        $uri = $this->base_url.$endpoint;
        $request->setUri($uri);
        $headers = $request->getHeaders()->addHeaders([
            "Authorization" => "Bearer ".$this->access_token]);
        $request->setHeaders($headers);
        return $request;
    }

    public function doRequest($request)
    {
        $client = new Client();
        $client->setOptions([
            'maxredirects' => 0,
            'timeout'      => 100,
        ]);
        $response = $client->send($request);
        $html = $response->getBody();
        if (strpos($html,"API calls quota") !== false) {
            $gotAproblem = true;
            usleep(600000000);
            $response = $client->send($request);
            $html = $response->getBody();
        }
        if (empty($html)) {
            return [];
        } else {
            $json = Json::decode($html,1);
            return $json;
        }
    }

    public function getTeams()
    {
        $request = $this->makeRequest('seasons/2020/teams');
        $result = $this->doRequest($request);
        return $result['data'];
    }

    public function testRequest()
    {
        $result = $this->getPlayersQuery("2020", "receiving", [
            'ReceivingFilters.MinAirYards' => '20',
            'ReceivingFilters.MaxAirYards' => '100',
            'GameFilters.Team' => '2',
        ]);
        return $result;
    }

    public function getSchedule($year)
    {
        $request = $this->makeRequest("/schedule/season/{$year}");
        $result = $this->doRequest($request);
        return $result;
    }

    public function getPlayers()
    {
        $request = $this->makeRequest("seasons/2021/players");
        return $this->doRequest($request);
    }

    public function getPlayerIds()
    {
        $request = $this->makeRequest("PlayerIds");
        return $this->doRequest($request);
    }

    public function getPlayersQuery($year="2021", $type="", $params=[])
    {
        $defaultArray = [
            "EntityType" => 1,
            "MetricGroup" => 1,
            "MetricGroupSubType" => 1,
            "GameFilters.Conference" => -1,
            "GameFilters.vsConference" => -1,
            "GameFilters.vsDivision" => -1,
            "GameFilters.HomeAway" => -1,
            "GameFilters.Team" => -1,
            "GameFilters.vsTeam" => -1,
            "GameFilters.MultipleTeams" => 0,
            "GameFilters.vsMultipleTeams" => 0,
            "GameFilters.IndoorOutdoor" => -1,
            "TimeFilters.SeasonFrom" => 2021,
            "TimeFilters.SeasonTo" => 2021,
            "TimeFilters.StartWeek" => 1,
            "TimeFilters.EndWeek" => 21,
            "SituationFilters.Quarters" => 0,
//            "SituationFilters.Quarters" => 1,
//            "SituationFilters.Quarters" => 2,
//            "SituationFilters.Quarters" => 3,
//            "SituationFilters.Quarters" => 4,
//            "SituationFilters.Quarters" => 5,
            "SituationFilters.Downs" => 0,
//            "SituationFilters.Downs" => 1,
//            "SituationFilters.Downs" => 2,
//            "SituationFilters.Downs" => 3,
//            "SituationFilters.Downs" => 4,
            "SituationFilters.FieldPositionFromSide" => -1,
            "SituationFilters.FieldPositionFromYd" => -1,
            "SituationFilters.FieldPositionToSide" => -1,
            "SituationFilters.FieldPositionToYd" => -1,
            "SituationFilters.TimeRemainingFrom" => 0,
            "SituationFilters.TimeRemainingTo" => 900,
            "SituationFilters.DistanceFrom" => 0,
            "SituationFilters.DistanceTo" => 100,
            "SituationFilters.ScoreDiffFrom" => -50,
            "SituationFilters.ScoreDiffTo" => 50,
            "PersonnelFilters.WRs" => -1,
            "PersonnelFilters.WRFormation" => -1,
            "PersonnelFilters.TEs" => -1,
            "PersonnelFilters.DLs" => -1,
            "PersonnelFilters.DBs" => -1,
            "PersonnelFilters.Shotgun" => -1,
            "PersonnelFilters.RBs" => -1,
            "PersonnelFilters.RBFormation" => -1,
            "PersonnelFilters.OLs" => -1,
            "PersonnelFilters.LBs" => -1,
            "PersonnelFilters.NoHuddle" => -1,
            "PassingFilters.PlayAction" => -1,
            "PassingFilters.Pressured" => -1,
            "PassingFilters.InPocket" => -1,
            "PassingFilters.RPO" => -1,
            "PassingFilters.AnyMotion" => -1,
            "PassingFilters.JetMotion" => -1,
            "PassingFilters.TargetInMotion" => -1,
            "PassingFilters.PastSticks" => -1,
            "PassingFilters.ThrowType" => 0,
//            "PassingFilters.ThrowType" => 1,
//            "PassingFilters.ThrowType" => 2,
//            "PassingFilters.ThrowType" => 3,
//            "PassingFilters.ThrowType" => 4,
            "PassingFilters.TargetLinedUp" => 0,
//            "PassingFilters.TargetLinedUp" => 1,
//            "PassingFilters.TargetLinedUp" => 2,
//            "PassingFilters.TargetLinedUp" => 3,
//            "PassingFilters.TargetLinedUp" => 4,
            "PassingFilters.PassDir" => 0,
//            "PassingFilters.PassDir" => 1,
//            "PassingFilters.PassDir" => 2,
//            "PassingFilters.PassDir" => 3,
//            "PassingFilters.PassDir" => 4,
//            "PassingFilters.PassDir" => 5,
            "PassingFilters.TargetPos" => 0,
//            "PassingFilters.TargetPos" => 2,
//            "PassingFilters.TargetPos" => 3,
//            "PassingFilters.TargetPos" => 4,
//            "PassingFilters.TargetPos" => 5,
            "PassingFilters.Schemes" => -999,
//            "PassingFilters.Schemes" => 0,
//            "PassingFilters.Schemes" => 1,
//            "PassingFilters.Schemes" => 2,
//            "PassingFilters.Schemes" => 5,
//            "PassingFilters.Schemes" => 3,
//            "PassingFilters.Schemes" => 4,
//            "PassingFilters.Schemes" => 6,
//            "PassingFilters.Schemes" => 10,
//            "PassingFilters.Schemes" => 11,
//            "PassingFilters.Schemes" => 12,
//            "PassingFilters.Schemes" => 13,
//            "PassingFilters.Schemes" => 14,
//            "PassingFilters.Schemes" => 15,
//            "PassingFilters.Schemes" => 16,
//            "PassingFilters.Schemes" => 17,
            "PassingFilters.RouteType" => 0,
//            "PassingFilters.RouteType" => 1,
//            "PassingFilters.RouteType" => 2,
//            "PassingFilters.RouteType" => 3,
//            "PassingFilters.RouteType" => 4,
//            "PassingFilters.RouteType" => 5,
//            "PassingFilters.RouteType" => 6,
//            "PassingFilters.RouteType" => 7,
//            "PassingFilters.RouteType" => 8,
//            "PassingFilters.RouteType" => 9,
//            "PassingFilters.RouteType" => 10,
//            "PassingFilters.RouteType" => 11,
//            "PassingFilters.RouteType" => 12,
//            "PassingFilters.RouteType" => 13,
//            "PassingFilters.RouteType" => 14,
//            "PassingFilters.RouteType" => 15,
//            "PassingFilters.RouteType" => 16,
//            "PassingFilters.RouteType" => 17,
//            "PassingFilters.RouteType" => 18,
//            "PassingFilters.RouteType" => 19,
//            "PassingFilters.RouteType" => 20,
//            "PassingFilters.RouteType" => 26,
//            "PassingFilters.RouteType" => 27,
//            "PassingFilters.RouteType" => 28,
//            "PassingFilters.RouteType" => 29,
//            "PassingFilters.RouteType" => 30,
//            "PassingFilters.RouteType" => 34,
//            "PassingFilters.RouteType" => 35,
//            "PassingFilters.RouteType" => 39,
//            "PassingFilters.RouteType" => 42,
//            "PassingFilters.RouteType" => 43,
            "PassingFilters.DropType" => 0,
//            "PassingFilters.DropType" => 1,
//            "PassingFilters.DropType" => 2,
//            "PassingFilters.DropType" => 3,
//            "PassingFilters.DropType" => 4,
//            "PassingFilters.DropType" => 5,
//            "PassingFilters.DropType" => 6,
//            "PassingFilters.DropType" => 7,
//            "PassingFilters.DropType" => 8,
//            "PassingFilters.DropType" => 9,
//            "PassingFilters.DropType" => 10,
//            "PassingFilters.DropType" => 12,
//            "PassingFilters.DropType" => 13,
//            "PassingFilters.DropType" => 14,
//            "PassingFilters.DropType" => 15,
//            "PassingFilters.DropType" => 11,
            "PassingFilters.MenInBox" => 0,
//            "PassingFilters.MenInBox" => 4,
//            "PassingFilters.MenInBox" => 5,
//            "PassingFilters.MenInBox" => 6,
//            "PassingFilters.MenInBox" => 7,
//            "PassingFilters.MenInBox" => 8,
//            "PassingFilters.MenInBox" => 9,
            "PassingFilters.QBAtPassType" => 0,
//            "PassingFilters.QBAtPassType" => 1,
//            "PassingFilters.QBAtPassType" => 2,
//            "PassingFilters.QBAtPassType" => 3,
            "PassingFilters.PassRushers" => 0,
//            "PassingFilters.PassRushers" => 3,
//            "PassingFilters.PassRushers" => 4,
//            "PassingFilters.PassRushers" => 5,
//            "PassingFilters.PassRushers" => 6,
//            "PassingFilters.PassRushers" => 7,
//            "PassingFilters.PassRushers" => 8,
            "PassingFilters.MinAirYards" => -20,
            "PassingFilters.MaxAirYards" => 100,
            "RushingFilters.AnyMotion" => -1,
            "RushingFilters.JetMotion" => -1,
            "RushingFilters.BlownBlock" => -1,
            "RushingFilters.LeadBlocker" => -1,
            "RushingFilters.UsedDesignedGap" => -1,
            "RushingFilters.RPO" => -1,
            "RushingFilters.ReadOption" => -1,
            "RushingFilters.RunType" => 0,
//            "RushingFilters.RunType" => 1,
//            "RushingFilters.RunType" => 2,
//            "RushingFilters.RunType" => 3,
//            "RushingFilters.RunType" => 4,
//            "RushingFilters.RunType" => 5,
//            "RushingFilters.RunType" => 7,
//            "RushingFilters.RunType" => 10,
//            "RushingFilters.RunType" => 13,
//            "RushingFilters.RunType" => 15,
//            "RushingFilters.RunType" => 16,
//            "RushingFilters.RunType" => 22,
//            "RushingFilters.RunType" => 23,
//            "RushingFilters.RunType" => 28,
//            "RushingFilters.RunType" => 29,
//            "RushingFilters.RunType" => 30,
//            "RushingFilters.RunType" => 31,
//            "RushingFilters.RunType" => 33,
//            "RushingFilters.RunType" => 34,
//            "RushingFilters.RunType" => 35,
//            "RushingFilters.RunType" => 36,
//            "RushingFilters.RunType" => 8,
//            "RushingFilters.RunType" => 14,
//            "RushingFilters.RunType" => 18,
//            "RushingFilters.RunType" => 19,
//            "RushingFilters.RunType" => 9,
//            "RushingFilters.RunType" => 17,
//            "RushingFilters.RunType" => 20,
//            "RushingFilters.RunType" => 24,
//            "RushingFilters.RunType" => 21,
//            "RushingFilters.RunType" => 25,
//            "RushingFilters.RunType" => 26,
//            "RushingFilters.RunType" => 27,
//            "RushingFilters.RunType" => 32,
//            "RushingFilters.RunType" => 11,
//            "RushingFilters.RunType" => 12,
            "RushingFilters.RunDirection" => 0,
//            "RushingFilters.RunDirection" => 5,
//            "RushingFilters.RunDirection" => 6,
//            "RushingFilters.RunDirection" => 1,
//            "RushingFilters.RunDirection" => 4,
//            "RushingFilters.RunDirection" => 3,
//            "RushingFilters.RunDirection" => 7,
//            "RushingFilters.RunDirection" => 2,
            "RushingFilters.BlockScheme" => 0,
//            "RushingFilters.BlockScheme" => 1,
//            "RushingFilters.BlockScheme" => 10,
//            "RushingFilters.BlockScheme" => 11,
//            "RushingFilters.BlockScheme" => 12,
//            "RushingFilters.BlockScheme" => 2,
//            "RushingFilters.BlockScheme" => 5,
//            "RushingFilters.BlockScheme" => 3,
//            "RushingFilters.BlockScheme" => 13,
//            "RushingFilters.BlockScheme" => 14,
//            "RushingFilters.BlockScheme" => 15,
//            "RushingFilters.BlockScheme" => 16,
//            "RushingFilters.BlockScheme" => 17,
            "RushingFilters.BallCarrierPos" => 0,
//            "RushingFilters.BallCarrierPos" => 1,
//            "RushingFilters.BallCarrierPos" => 2,
//            "RushingFilters.BallCarrierPos" => 3,
//            "RushingFilters.BallCarrierPos" => 4,
//            "RushingFilters.BallCarrierPos" => 5,
            "RushingFilters.DefInBox" => 0,
//            "RushingFilters.DefInBox" => 4,
//            "RushingFilters.DefInBox" => 5,
//            "RushingFilters.DefInBox" => 6,
//            "RushingFilters.DefInBox" => 7,
//            "RushingFilters.DefInBox" => 8,
//            "RushingFilters.DefInBox" => 9,
            "RushingFilters.MinFirstContact" => -20,
            "RushingFilters.MaxFirstContact" => 100,
            "ReceivingFilters.InMotion" => -1,
            "ReceivingFilters.Catchable" => -1,
            "ReceivingFilters.BrokenPlay" => -1,
            "ReceivingFilters.EndZoneTarget" => -1,
            "ReceivingFilters.IsolatedWR" => -1,
            "ReceivingFilters.QBPressured" => -1,
            "ReceivingFilters.OnTarget" => -1,
            "ReceivingFilters.TargetLinedUp" => 0,
//            "ReceivingFilters.TargetLinedUp" => 1,
//            "ReceivingFilters.TargetLinedUp" => 2,
//            "ReceivingFilters.TargetLinedUp" => 3,
//            "ReceivingFilters.TargetLinedUp" => 4,
            "ReceivingFilters.PassDir" => 0,
//            "ReceivingFilters.PassDir" => 1,
//            "ReceivingFilters.PassDir" => 2,
//            "ReceivingFilters.PassDir" => 3,
//            "ReceivingFilters.PassDir" => 4,
//            "ReceivingFilters.PassDir" => 5,
            "ReceivingFilters.TargetPos" => 0,
//            "ReceivingFilters.TargetPos" => 2,
//            "ReceivingFilters.TargetPos" => 3,
//            "ReceivingFilters.TargetPos" => 4,
//            "ReceivingFilters.TargetPos" => 5,
            "ReceivingFilters.Schemes" => -999,
//            "ReceivingFilters.Schemes" => 0,
//            "ReceivingFilters.Schemes" => 1,
//            "ReceivingFilters.Schemes" => 2,
//            "ReceivingFilters.Schemes" => 5,
//            "ReceivingFilters.Schemes" => 3,
//            "ReceivingFilters.Schemes" => 4,
//            "ReceivingFilters.Schemes" => 6,
//            "ReceivingFilters.Schemes" => 10,
//            "ReceivingFilters.Schemes" => 11,
//            "ReceivingFilters.Schemes" => 12,
//            "ReceivingFilters.Schemes" => 13,
//            "ReceivingFilters.Schemes" => 14,
//            "ReceivingFilters.Schemes" => 15,
//            "ReceivingFilters.Schemes" => 16,
//            "ReceivingFilters.Schemes" => 17,
            "ReceivingFilters.RecAlignment" => 0,
//            "ReceivingFilters.RecAlignment" => 1,
//            "ReceivingFilters.RecAlignment" => 2,
//            "ReceivingFilters.RecAlignment" => 3,
//            "ReceivingFilters.RecAlignment" => 4,
//            "ReceivingFilters.RecAlignment" => 5,
//            "ReceivingFilters.RecAlignment" => 6,
//            "ReceivingFilters.RecAlignment" => 7,
            "ReceivingFilters.RouteType" => 0,
//            "ReceivingFilters.RouteType" => 1,
//            "ReceivingFilters.RouteType" => 2,
//            "ReceivingFilters.RouteType" => 3,
//            "ReceivingFilters.RouteType" => 4,
//            "ReceivingFilters.RouteType" => 5,
//            "ReceivingFilters.RouteType" => 6,
//            "ReceivingFilters.RouteType" => 7,
//            "ReceivingFilters.RouteType" => 8,
//            "ReceivingFilters.RouteType" => 9,
//            "ReceivingFilters.RouteType" => 10,
//            "ReceivingFilters.RouteType" => 11,
//            "ReceivingFilters.RouteType" => 12,
//            "ReceivingFilters.RouteType" => 13,
//            "ReceivingFilters.RouteType" => 14,
//            "ReceivingFilters.RouteType" => 15,
//            "ReceivingFilters.RouteType" => 16,
//            "ReceivingFilters.RouteType" => 17,
//            "ReceivingFilters.RouteType" => 18,
//            "ReceivingFilters.RouteType" => 19,
//            "ReceivingFilters.RouteType" => 20,
//            "ReceivingFilters.RouteType" => 26,
//            "ReceivingFilters.RouteType" => 27,
//            "ReceivingFilters.RouteType" => 28,
//            "ReceivingFilters.RouteType" => 29,
//            "ReceivingFilters.RouteType" => 30,
//            "ReceivingFilters.RouteType" => 34,
//            "ReceivingFilters.RouteType" => 35,
//            "ReceivingFilters.RouteType" => 39,
//            "ReceivingFilters.RouteType" => 42,
//            "ReceivingFilters.RouteType" => 43,
            "ReceivingFilters.DropType" => 0,
//            "ReceivingFilters.DropType" => 1,
//            "ReceivingFilters.DropType" => 2,
//            "ReceivingFilters.DropType" => 3,
//            "ReceivingFilters.DropType" => 4,
//            "ReceivingFilters.DropType" => 5,
//            "ReceivingFilters.DropType" => 6,
//            "ReceivingFilters.DropType" => 7,
//            "ReceivingFilters.DropType" => 8,
//            "ReceivingFilters.DropType" => 9,
//            "ReceivingFilters.DropType" => 10,
//            "ReceivingFilters.DropType" => 12,
//            "ReceivingFilters.DropType" => 13,
//            "ReceivingFilters.DropType" => 14,
//            "ReceivingFilters.DropType" => 15,
//            "ReceivingFilters.DropType" => 11,
            "ReceivingFilters.MotionType" => 0,
//            "ReceivingFilters.MotionType" => 1,
//            "ReceivingFilters.MotionType" => 2,
//            "ReceivingFilters.MotionType" => 3,
//            "ReceivingFilters.MotionType" => 4,
//            "ReceivingFilters.MotionType" => 5,
//            "ReceivingFilters.MotionType" => 6,
//            "ReceivingFilters.MotionType" => 7,
//            "ReceivingFilters.MotionType" => 8,
//            "ReceivingFilters.MotionType" => 9,
//            "ReceivingFilters.MotionType" => 10,
//            "ReceivingFilters.MotionType" => 11,
//            "ReceivingFilters.MotionType" => 12,
//            "ReceivingFilters.MotionType" => 13,
//            "ReceivingFilters.MotionType" => 14,
//            "ReceivingFilters.MotionType" => 15,
//            "ReceivingFilters.MotionType" => 16,
//            "ReceivingFilters.MotionType" => 17,
//            "ReceivingFilters.MotionType" => 18,
//            "ReceivingFilters.MotionType" => 19,
            "ReceivingFilters.MenInBox" => 0,
//            "ReceivingFilters.MenInBox" => 4,
//            "ReceivingFilters.MenInBox" => 5,
//            "ReceivingFilters.MenInBox" => 6,
//            "ReceivingFilters.MenInBox" => 7,
//            "ReceivingFilters.MenInBox" => 8,
//            "ReceivingFilters.MenInBox" => 9,
            "ReceivingFilters.PassRushers" => 0,
//            "ReceivingFilters.PassRushers" => 3,
//            "ReceivingFilters.PassRushers" => 4,
//            "ReceivingFilters.PassRushers" => 5,
//            "ReceivingFilters.PassRushers" => 6,
//            "ReceivingFilters.PassRushers" => 7,
//            "ReceivingFilters.PassRushers" => 8,
            "ReceivingFilters.MinAirYards" => -20,
            "ReceivingFilters.MaxAirYards" => 100,
            "RunDefenseFilters.AnyMotion" => -1,
            "RunDefenseFilters.JetMotion" => -1,
            "RunDefenseFilters.IsDesignedRun" => -1,
            "RunDefenseFilters.SideOfCenter" => -1,
            "RunDefenseFilters.RunType" => 0,
//            "RunDefenseFilters.RunType" => 1,
//            "RunDefenseFilters.RunType" => 2,
//            "RunDefenseFilters.RunType" => 3,
//            "RunDefenseFilters.RunType" => 4,
//            "RunDefenseFilters.RunType" => 5,
//            "RunDefenseFilters.RunType" => 7,
//            "RunDefenseFilters.RunType" => 10,
//            "RunDefenseFilters.RunType" => 13,
//            "RunDefenseFilters.RunType" => 15,
//            "RunDefenseFilters.RunType" => 16,
//            "RunDefenseFilters.RunType" => 22,
//            "RunDefenseFilters.RunType" => 23,
//            "RunDefenseFilters.RunType" => 28,
//            "RunDefenseFilters.RunType" => 29,
//            "RunDefenseFilters.RunType" => 30,
//            "RunDefenseFilters.RunType" => 31,
//            "RunDefenseFilters.RunType" => 33,
//            "RunDefenseFilters.RunType" => 34,
//            "RunDefenseFilters.RunType" => 35,
//            "RunDefenseFilters.RunType" => 36,
//            "RunDefenseFilters.RunType" => 8,
//            "RunDefenseFilters.RunType" => 14,
//            "RunDefenseFilters.RunType" => 18,
//            "RunDefenseFilters.RunType" => 19,
//            "RunDefenseFilters.RunType" => 9,
//            "RunDefenseFilters.RunType" => 17,
//            "RunDefenseFilters.RunType" => 20,
//            "RunDefenseFilters.RunType" => 24,
//            "RunDefenseFilters.RunType" => 21,
//            "RunDefenseFilters.RunType" => 25,
//            "RunDefenseFilters.RunType" => 26,
//            "RunDefenseFilters.RunType" => 27,
//            "RunDefenseFilters.RunType" => 32,
//            "RunDefenseFilters.RunType" => 11,
//            "RunDefenseFilters.RunType" => 12,
            "RunDefenseFilters.BlockScheme" => 0,
//            "RunDefenseFilters.BlockScheme" => 1,
//            "RunDefenseFilters.BlockScheme" => 2,
//            "RunDefenseFilters.BlockScheme" => 3,
//            "RunDefenseFilters.BlockScheme" => 4,
//            "RunDefenseFilters.BlockScheme" => 5,
//            "RunDefenseFilters.BlockScheme" => 6,
//            "RunDefenseFilters.BlockScheme" => 7,
//            "RunDefenseFilters.BlockScheme" => 8,
//            "RunDefenseFilters.BlockScheme" => 9,
//            "RunDefenseFilters.BlockScheme" => 10,
//            "RunDefenseFilters.BlockScheme" => 11,
//            "RunDefenseFilters.BlockScheme" => 12,
//            "RunDefenseFilters.BlockScheme" => 13,
//            "RunDefenseFilters.BlockScheme" => 14,
//            "RunDefenseFilters.BlockScheme" => 15,
//            "RunDefenseFilters.BlockScheme" => 16,
//            "RunDefenseFilters.BlockScheme" => 17,
//            "RunDefenseFilters.RunDirection" => 0,
//            "RunDefenseFilters.RunDirection" => 5,
//            "RunDefenseFilters.RunDirection" => 6,
//            "RunDefenseFilters.RunDirection" => 1,
//            "RunDefenseFilters.RunDirection" => 4,
//            "RunDefenseFilters.RunDirection" => 3,
//            "RunDefenseFilters.RunDirection" => 7,
//            "RunDefenseFilters.RunDirection" => 2,
//            "RunDefenseFilters.DefenderPos" => 0,
//            "RunDefenseFilters.DefenderPos" => 11,
//            "RunDefenseFilters.DefenderPos" => 9,
//            "RunDefenseFilters.DefenderPos" => 10,
//            "RunDefenseFilters.DefenderPos" => 13,
//            "RunDefenseFilters.DefenderPos" => 12,
            "RunDefenseFilters.DefInBox" => 0,
//            "RunDefenseFilters.DefInBox" => 4,
//            "RunDefenseFilters.DefInBox" => 5,
//            "RunDefenseFilters.DefInBox" => 6,
//            "RunDefenseFilters.DefInBox" => 7,
//            "RunDefenseFilters.DefInBox" => 8,
//            "RunDefenseFilters.DefInBox" => 9,
            "RunDefenseFilters.Techniques" => -1,
//            "RunDefenseFilters.Techniques" => 0,
//            "RunDefenseFilters.Techniques" => 1,
//            "RunDefenseFilters.Techniques" => 2,
//            "RunDefenseFilters.Techniques" => 3,
//            "RunDefenseFilters.Techniques" => 4,
//            "RunDefenseFilters.Techniques" => 5,
//            "RunDefenseFilters.Techniques" => 6,
//            "RunDefenseFilters.Techniques" => 7,
//            "RunDefenseFilters.Techniques" => 8,
//            "RunDefenseFilters.Techniques" => 9,
//            "RunDefenseFilters.Techniques" => 10,
            "PassDefenseFilters.AnyMotion" => -1,
            "PassDefenseFilters.JetMotion" => -1,
            "PassDefenseFilters.QBPressured" => -1,
            "PassDefenseFilters.PlayAction" => -1,
            "PassDefenseFilters.RouteType" => 0,
//            "PassDefenseFilters.RouteType" => 1,
//            "PassDefenseFilters.RouteType" => 2,
//            "PassDefenseFilters.RouteType" => 3,
//            "PassDefenseFilters.RouteType" => 4,
//            "PassDefenseFilters.RouteType" => 5,
//            "PassDefenseFilters.RouteType" => 6,
//            "PassDefenseFilters.RouteType" => 7,
//            "PassDefenseFilters.RouteType" => 8,
//            "PassDefenseFilters.RouteType" => 9,
//            "PassDefenseFilters.RouteType" => 10,
//            "PassDefenseFilters.RouteType" => 11,
//            "PassDefenseFilters.RouteType" => 12,
//            "PassDefenseFilters.RouteType" => 13,
//            "PassDefenseFilters.RouteType" => 14,
//            "PassDefenseFilters.RouteType" => 15,
//            "PassDefenseFilters.RouteType" => 16,
//            "PassDefenseFilters.RouteType" => 17,
//            "PassDefenseFilters.RouteType" => 18,
//            "PassDefenseFilters.RouteType" => 19,
//            "PassDefenseFilters.RouteType" => 20,
//            "PassDefenseFilters.RouteType" => 26,
//            "PassDefenseFilters.RouteType" => 27,
//            "PassDefenseFilters.RouteType" => 28,
//            "PassDefenseFilters.RouteType" => 29,
//            "PassDefenseFilters.RouteType" => 30,
//            "PassDefenseFilters.RouteType" => 34,
//            "PassDefenseFilters.RouteType" => 35,
//            "PassDefenseFilters.RouteType" => 39,
//            "PassDefenseFilters.RouteType" => 42,
//            "PassDefenseFilters.RouteType" => 43,
            "PassDefenseFilters.DefenderPos" => 0,
//            "PassDefenseFilters.DefenderPos" => 12,
//            "PassDefenseFilters.DefenderPos" => 13,
//            "PassDefenseFilters.DefenderPos" => 11,
//            "PassDefenseFilters.DefenderPos" => 9,
            "PassDefenseFilters.Schemes" => -999,
            "PassDefenseFilters.Schemes" => 0,
            "PassDefenseFilters.Schemes" => 1,
            "PassDefenseFilters.Schemes" => 2,
            "PassDefenseFilters.Schemes" => 5,
            "PassDefenseFilters.Schemes" => 3,
            "PassDefenseFilters.Schemes" => 4,
            "PassDefenseFilters.Schemes" => 6,
            "PassDefenseFilters.Schemes" => 10,
            "PassDefenseFilters.Schemes" => 11,
            "PassDefenseFilters.Schemes" => 12,
            "PassDefenseFilters.Schemes" => 13,
            "PassDefenseFilters.Schemes" => 14,
            "PassDefenseFilters.Schemes" => 15,
            "PassDefenseFilters.Schemes" => 16,
            "PassDefenseFilters.Schemes" => 17,
            "PassDefenseFilters.PassDir" => 0,
            "PassDefenseFilters.PassDir" => 1,
            "PassDefenseFilters.PassDir" => 2,
            "PassDefenseFilters.PassDir" => 3,
            "PassDefenseFilters.PassDir" => 4,
            "PassDefenseFilters.PassDir" => 5,
            "PassDefenseFilters.TargetLinedUp" => 0,
            "PassDefenseFilters.TargetLinedUp" => 1,
            "PassDefenseFilters.TargetLinedUp" => 2,
            "PassDefenseFilters.TargetLinedUp" => 3,
            "PassDefenseFilters.TargetLinedUp" => 4,
            "PassDefenseFilters.ReceiverPos" => 0,
            "PassDefenseFilters.ReceiverPos" => 2,
            "PassDefenseFilters.ReceiverPos" => 4,
            "PassDefenseFilters.ReceiverPos" => 5,
            "PassDefenseFilters.DefenderLinedUp" => 0,
            "PassDefenseFilters.DefenderLinedUp" => 1,
            "PassDefenseFilters.DefenderLinedUp" => 2,
            "PassDefenseFilters.DefenderLinedUp" => 3,
            "PassDefenseFilters.DefenderLinedUp" => 4,
            "PassDefenseFilters.DefenderLinedUp" => 5,
            "PassDefenseFilters.DefenderLinedUp" => 6,
            "PassDefenseFilters.Rushers" => 0,
            "PassDefenseFilters.Rushers" => 3,
            "PassDefenseFilters.Rushers" => 4,
            "PassDefenseFilters.Rushers" => 5,
            "PassDefenseFilters.Rushers" => 6,
            "PassDefenseFilters.Rushers" => 7,
            "PassDefenseFilters.Rushers" => 8,
            "PassDefenseFilters.MinAirYards" => -20,
            "PassDefenseFilters.MaxAirYards" => 100,
            "PassRushFilters.AnyMotion" => -1,
            "PassRushFilters.JetMotion" => -1,
            "PassRushFilters.PlayAction" => -1,
            "PassRushFilters.SideOfCenter" => -1,
            "PassRushFilters.Schemes" => -999,
            "PassRushFilters.Schemes" => 0,
            "PassRushFilters.Schemes" => 1,
            "PassRushFilters.Schemes" => 2,
            "PassRushFilters.Schemes" => 5,
            "PassRushFilters.Schemes" => 3,
            "PassRushFilters.Schemes" => 4,
            "PassRushFilters.Schemes" => 6,
            "PassRushFilters.Schemes" => 10,
            "PassRushFilters.Schemes" => 11,
            "PassRushFilters.Schemes" => 12,
            "PassRushFilters.Schemes" => 13,
            "PassRushFilters.Schemes" => 14,
            "PassRushFilters.Schemes" => 15,
            "PassRushFilters.Schemes" => 16,
            "PassRushFilters.Schemes" => 17,
            "PassRushFilters.DefenderPos" => 0,
            "PassRushFilters.DefenderPos" => 9,
            "PassRushFilters.DefenderPos" => 10,
            "PassRushFilters.DefenderPos" => 11,
            "PassRushFilters.DefenderPos" => 13,
            "PassRushFilters.DefenderPos" => 12,
            "PassRushFilters.DropType" => 0,
            "PassRushFilters.DropType" => 1,
            "PassRushFilters.DropType" => 2,
            "PassRushFilters.DropType" => 3,
            "PassRushFilters.DropType" => 4,
            "PassRushFilters.DropType" => 5,
            "PassRushFilters.DropType" => 6,
            "PassRushFilters.DropType" => 7,
            "PassRushFilters.DropType" => 8,
            "PassRushFilters.DropType" => 9,
            "PassRushFilters.DropType" => 10,
            "PassRushFilters.DropType" => 12,
            "PassRushFilters.DropType" => 13,
            "PassRushFilters.DropType" => 14,
            "PassRushFilters.DropType" => 15,
            "PassRushFilters.DropType" => 11,
            "PassRushFilters.Rushers" => 0,
            "PassRushFilters.Rushers" => 3,
            "PassRushFilters.Rushers" => 4,
            "PassRushFilters.Rushers" => 5,
            "PassRushFilters.Rushers" => 6,
            "PassRushFilters.Rushers" => 7,
            "PassRushFilters.Rushers" => 8,
            "PassRushFilters.Techniques" => -1,
            "PassRushFilters.Techniques" => 0,
            "PassRushFilters.Techniques" => 1,
            "PassRushFilters.Techniques" => 2,
            "PassRushFilters.Techniques" => 3,
            "PassRushFilters.Techniques" => 4,
            "PassRushFilters.Techniques" => 5,
            "PassRushFilters.Techniques" => 6,
            "PassRushFilters.Techniques" => 7,
            "PassRushFilters.Techniques" => 8,
            "PassRushFilters.Techniques" => 9,
            "PassRushFilters.Techniques" => 10,
            "PassRushFilters.MinAirYards" => -20,
            "PassRushFilters.MaxAirYards" => 100,
            "PassRushFilters.PuntType" => 0,
            "PassRushFilters.PuntType" => 1,
            "PassRushFilters.PuntType" => 2,
            "PassRushFilters.PuntType" => 3,
            "PassRushFilters.PuntType" => 4,
            "KickingFilters.MinFGYards" => 0,
            "KickingFilters.MaxFGYards" => 65,
            "BlockFilters.BlockScheme" => 0,
            "BlockFilters.BlockScheme" => 1,
            "BlockFilters.BlockScheme" => 10,
            "BlockFilters.BlockScheme" => 11,
            "BlockFilters.BlockScheme" => 12,
            "BlockFilters.BlockScheme" => 2,
            "BlockFilters.BlockScheme" => 3,
            "BlockFilters.BlockScheme" => 8,
            "BlockFilters.BlockScheme" => 9,
            "BlockFilters.BlockScheme" => 13,
            "BlockFilters.BlockScheme" => 14,
            "BlockFilters.BlockScheme" => 15,
            "BlockFilters.BlockScheme" => 16,
            "BlockFilters.BlockScheme" => 17,
            "BlockFilters.DefInBox" => 0,
            "BlockFilters.DefInBox" => 4,
            "BlockFilters.DefInBox" => 5,
            "BlockFilters.DefInBox" => 6,
            "BlockFilters.DefInBox" => 7,
            "BlockFilters.DefInBox" => 8,
            "BlockFilters.DefInBox" => 9,
            "BlockFilters.LinedUp" => 0,
            "BlockFilters.LinedUp" => 1,
            "BlockFilters.LinedUp" => 2,
            "BlockFilters.LinedUp" => 3,
            "BlockFilters.LinedUp" => 4,
            "BlockFilters.LinedUp" => 5,
            "BlockFilters.LinedUp" => 6,
            "BlockFilters.LinedUp" => 7,
            "BlockFilters.BlockingPosition" => 0,
            "BlockFilters.BlockingPosition" => 1,
            "BlockFilters.BlockingPosition" => 2,
            "BlockFilters.BlockingPosition" => 3,
            "BlockFilters.BlockingPosition" => 4,
            "BlockFilters.BlockingPosition" => 5,
            "BlockFilters.BlockingPosition" => 6,
            "BlockFilters.PlayAction" => -1,
            "BlockFilters.InPocket" => -1,
            "BlockFilters.DropType" => 0,
//            "BlockFilters.DropType" => 1,
//            "BlockFilters.DropType" => 2,
//            "BlockFilters.DropType" => 3,
//            "BlockFilters.DropType" => 4,
//            "BlockFilters.DropType" => 5,
//            "BlockFilters.DropType" => 6,
//            "BlockFilters.DropType" => 7,
//            "BlockFilters.DropType" => 8,
//            "BlockFilters.DropType" => 9,
//            "BlockFilters.DropType" => 10,
//            "BlockFilters.DropType" => 12,
//            "BlockFilters.DropType" => 13,
//            "BlockFilters.DropType" => 14,
//            "BlockFilters.DropType" => 15,
//            "BlockFilters.DropType" => 11,
            "BlockFilters.PassRushers" => 0,
//            "BlockFilters.PassRushers" => 3,
//            "BlockFilters.PassRushers" => 4,
//            "BlockFilters.PassRushers" => 5,
//            "BlockFilters.PassRushers" => 6,
//            "BlockFilters.PassRushers" => 7,
//            "BlockFilters.PassRushers" => 8,
            "BlockFilters.RunDirection" => 0,
//            "BlockFilters.RunDirection" => 5,
//            "BlockFilters.RunDirection" => 6,
//            "BlockFilters.RunDirection" => 1,
//            "BlockFilters.RunDirection" => 4,
//            "BlockFilters.RunDirection" => 3,
//            "BlockFilters.RunDirection" => 7,
//            "BlockFilters.RunDirection" => 2,
            "AdjustedBB.TeamId" => -1,
            "AdjustedBB.BlockingPosition" => 0,
//            "AdjustedBB.BlockingPosition" => 1,
//            "AdjustedBB.BlockingPosition" => 2,
//            "AdjustedBB.BlockingPosition" => 3,
//            "AdjustedBB.BlockingPosition" => 4,
//            "AdjustedBB.BlockingPosition" => 5,
//            "AdjustedBB.BlockingPosition" => 6,
            "PassingFilters.MinAttempts" => 1,
            "RushingFilters.MinCarries" => 5,
            "ReceivingFilters.MinTargets" => 1,
            "PassDefenseFilters.MinTargets" => 1,
            "PassDefenseFilters.MinAttempts" => 1,
            "RunDefenseFilters.MinTackles" => 1,
            "RunDefenseFilters.MinCarries" => 1,
            "PassRushFilters.MinPassRushes" => 1,
            "PassRushFilters.MinPressures" => 1,
            "ReturnFIlters.MinKR" => 1,
            "ReturnFilters.MinPR" => 1,
            "PassRushFilters.MinPunt" => 1,
            "KickingFilters.MinFG" => 1,
            "BlockFilters.MinSnaps" => 10,
            "AdjustedBB.MinPassSnaps" => 1,
        ];

        /**
         * MetricGroups:(1=passing, 5=receiving, 3=rushing, 14=offensive line, 9=passDef, 10=passRush, 11=runDef, 12=returning)
         */
        $metricGroup = [
            "passing" => 1,
            "rushing" => 3,
            "receiving" => 5,
            "blocking" => 14,
            "passDef" => 9,
            "passRush" => 10,
            "runDef" => 11,
            "return" => 12
        ];

        if (!empty($params)) {
            $defaultArray = array_merge($defaultArray, $params);
        }

        $defaultArray['MetricGroup'] = $metricGroup[$type];
        $defaultArray['TimeFilters.SeasonFrom'] = $year;
        $defaultArray['TimeFilters.SeasonTo'] = $year;
        $defaultArray['Result'] = "starts";

        $request = $this->makeRequest('players/query');
        foreach ($defaultArray as $query => $value) {
            $request->getPost()->set($query, $value);
        }

        $request->setMethod(Request::METHOD_POST);
        $response = $this->doRequest($request);
        return $response['data'];
    }

    public function getTeamsQuery()
    {
        /**
         * MetricGroups:(1=passing, 5=receiving, 3=rushing, 14=offensive line, 9=passDef, 10=passRush, 11=runDef, 12=returning)
         */
        $defaultQuery = [
            "EntityType" => 1,
            "MetricGroup" => 3,
            "MetricGroupSubType" => 1,
            "GameFilters.vsConference" => -1,
            "GameFilters.vsDivision" => -1,
            "GameFilters.vsTeam" => -1,
            "GameFilters.HomeAway" => -1,
            "GameFilters.IndoorOutdoor" => -1,
            "GameFilters.Team" => -1,
            "TimeFilters.SeasonFrom" => 2019,
            "TimeFilters.SeasonTo" => 2019,
            "TimeFilters.StartWeek" => 1,
            "TimeFilters.EndWeek" => 17,
            "SituationFilters.Quarters" => 0,
            "SituationFilters.Downs" => 0,
            "SituationFilters.FieldPositionFromSide" => -1,
            "SituationFilters.FieldPositionFromYd" => "",
            "SituationFilters.FieldPositionToSide" => -1,
            "SituationFilters.FieldPositionToYd" => "",
            "SituationFilters.TimeRemainingFrom" => 0,
            "SituationFilters.TimeRemainingTo" => 900,
            "SituationFilters.DistanceFrom" => 0,
            "SituationFilters.DistanceTo" => 100,
            "SituationFilters.ScoreDiffFrom" => -50,
            "SituationFilters.ScoreDiffTo" => 50,
            "PersonnelFilters.WRs" => -1,
            "PersonnelFilters.WRFormation" => -1,
            "PersonnelFilters.TEs" => -1,
            "PersonnelFilters.DLs" => -1,
            "PersonnelFilters.DBs" => -1,
            "PersonnelFilters.Shotgun" => -1,
            "PersonnelFilters.RBs" => -1,
            "PersonnelFilters.RBFormation" => -1,
            "PersonnelFilters.OLs" => -1,
            "PersonnelFilters.LBs" => -1,
            "PersonnelFilters.NoHuddle" => -1,
            "PassingFilters.PlayAction" => -1,
            "PassingFilters.Bootleg" => -1,
            "PassingFilters.Pressured" => -1,
            "PassingFilters.InPocket" => -1,
            "PassingFilters.ThrowType" => 0,
            "PassingFilters.TargetLinedUp" => 0,
            "PassingFilters.PassDir" => 0,
            "PassingFilters.TargetPos" => 0,
            "PassingFilters.Schemes" => 0,
            "PassingFilters.RouteType" => 0,
            "PassingFilters.DropType" => 0,
            "PassingFilters.MinAirYards" => -20,
            "PassingFilters.MaxAirYards" => 100,
            "RushingFilters.RunType" => 0,
            "RushingFilters.RunDirection" => 0,
            "RushingFilters.BlockScheme" => 0,
            "RushingFilters.BallCarrierPos" => 0,
            "RushingFilters.DefInBox" => 0,
            "ReceivingFilters.InMotion" => -1,
            "ReceivingFilters.Catchable" => -1,
            "ReceivingFilters.TargetLinedUp" => 0,
            "ReceivingFilters.PassDir" => 0,
            "ReceivingFilters.TargetPos" => 0,
            "ReceivingFilters.Schemes" => 0,
            "ReceivingFilters.RecAlignment" => 0,
            "ReceivingFilters.RouteType" => 0,
            "ReceivingFilters.MinAirYards" => -20,
            "ReceivingFilters.MaxAirYards" => 100,
            "RunDefenseFilters.RunType" => 0,
            "RunDefenseFilters.RunDirection" => 0,
            "RunDefenseFilters.BlockScheme" => 0,
            "RunDefenseFilters.DefenderPos" => 0,
            "RunDefenseFilters.DefInBox" => 0,
            "PassDefenseFilters.RouteType" => 0,
            "PassDefenseFilters.DefenderPos" => 0,
            "PassDefenseFilters.Schemes" => 0,
            "PassDefenseFilters.PassDir" => 0,
            "PassDefenseFilters.TargetLinedUp" => 0,
            "PassDefenseFilters.ReceiverPos" => 0,
            "PassDefenseFilters.MinAirYards" => -20,
            "PassDefenseFilters.MaxAirYards" => 100,
            "PassRushFilters.Schemes" => 0,
            "PassRushFilters.DefenderPos" => 0,
            "PuntingFilters.PuntType" => 0,
            "KickingFilters.MinFGYards" => 0,
            "KickingFilters.MaxFGYards" => 65,
            "BlockFilters.PlayAction" => -1,
            "BlockFilters.Bootleg" => -1,
            "BlockFilters.InPocket" => -1,
            "BlockFilters.RunDirection" => 0,
            "BlockFilters.BlockScheme" => 0,
            "BlockFilters.DefInBox" => 0,
            "BlockFilters.PassRushers" => 0,
            "BlockFilters.BlockingPosition" => 0,
            "AdjustedBB.TeamId" => -1,
            "AdjustedBB.BlockingPosition" => 0,
            "PassingFilters.MinAttempts" => 1,
            "RushingFilters.MinCarries" => 5,
            "ReceivingFilters.MinTargets" => 1,
            "PassDefenseFilters.MinTargets" => 1,
            "PassDefenseFilters.MinAttempts" => 1,
            "RunDefenseFilters.MinTackles" => 1,
            "RunDefenseFilters.MinCarries" => 1,
            "PassRushFilters.MinPassRushes" => 1,
            "PassRushFilters.MinPressures" => 1,
            "ReturnFIlters.MinKR" => 1,
            "ReturnFilters.MinPR" => 1,
            "PuntingFilters.MinPunt" => 1,
            "KickingFilters.MinFG" => 1,
            "BlockFilters.MinSnaps" => 10,
            "AdjustedBB.MinPassSnaps" => 1
        ];

        $request = $this->makeRequest('teams/query');
        foreach ($defaultQuery as $query => $value) {
            $request->getPost()->set($query, $value);
        }
        $request->setMethod('POST');
        return $this->doRequest($request);
    }

    public function getSeasonStats($playerId, $year, $type)
    {
        /*
         *                             "gp" => $stats['passing']['g'],
                            "gs" => $stats['passing']['starts'],
                            "td" => $stats['passing']['td'] + $stats['passing']['td'],
                            "pass_att" => $stats['passing']['attempts'],
                            "pass_cmp" => $stats['passing']['comp'],
                            "pass_int" => $stats['passing']['int'],
                            "pass_rtg" => $stats['passing']['qbRating'],
                            "pass_lng" => $stats['passing']['passLong'],
                            "pass_ypa" => $stats['passing']['yardsPerAtt'],
                            "pass_ypc" => $stats['passing']['yardsPerComp'],
                            "pass_td" => $stats['passing']['td'],
         */


        $emptyRushing = [
            "g" => 0,
            "starts" => 0,
            "att" => 0,
            "yards" => 0,
            "int" => 0,
            "qbRating" => 0,
            "passLong" => 0,
            "yardsPerAtt" => 0,
            "yardsPerComp" => 0,
            "td" => 0,
            "long" => 0,
            "firstDown" => 0
        ];

        $emptyReceiving = [
            "g" => 0,
            "starts" => 0,
            "recs" => 0,
            "targets" => 0,
            "yards" => 0,
            "yardsPerRec" => 0,
            "yardsPerTarget" => 0,
            "yardsPerAtt" => 0,
            "yardsPerComp" => 0,
            "td" => 0,
            "firstDowns" => 0,
            "long" => 0,
        ];


        switch ($type) {
            case "QB":
                $request = $this->makeRequest("seasons/{$year}/players/{$playerId}/passing");
                $passing = $this->doRequest($request);
                $request = $this->makeRequest("seasons/{$year}/players/{$playerId}/rushing");
                $rushing = $this->doRequest($request);

                $result['passing'] = (empty($passing['data']) || empty($passing['data'][0]))? [] : $passing['data'][0];
                if (empty($result['passing'])) {
                   $result['passing'] = $passing;
                }
                $result['rushing'] = (empty($rushing['data']))? [] : $rushing['data'][0];
                if (empty($result['rushing'])) {
                   $result['rushing'] = $emptyRushing;
                }

                break;
            case "RB":
            case "WR":
            case "TE":
                $request = $this->makeRequest("seasons/{$year}/players/{$playerId}/rushing");
                $rushing = $this->doRequest($request);
                $request = $this->makeRequest("seasons/{$year}/players/{$playerId}/receiving");
                $receiving = $this->doRequest($request);

                $result['rushing'] = (empty($rushing['data']))? [] : $rushing['data'][0];
                if (empty($result['rushing'])) {
                    $result['rushing'] = $emptyRushing;
                }
                $result['receiving'] = (empty($receiving['data']))? [] : $receiving['data'][0];
                if (empty($result['receiving'])) {
                    $result['receiving'] = $emptyReceiving;
                }
                break;
            case "C":
            case "T":
            case "G":
                $request = $this->makeRequest("seasons/{$year}/players/{$playerId}/blocking");
                $blocking = $this->doRequest($request);

                $result['blocking'] = (empty($blocking))? [] : $blocking['data'][0] ;
                break;
            case "LB":
            case "CB":
            case "DE":
            case "RE":
            case "LE":
            case "DT":
            case "FS":
            case "SS":
                $request = $this->makeRequest("seasons/{$year}/players/{$playerId}/defense");
                $defense = $this->doRequest($request);
                $result['defense'] = (empty($defense['data']))? [] : $defense['data'][0];
                break;
            default:
                $request = $this->makeRequest("season/{$year}/weeks/players/{$playerId}");
                $result = $this->doRequest($request);
        }
        return $result;
    }

    public function getLeaders($year, $type) {
        $request = $this->makeRequest("seasons/2019/leaders/rushing");
        return $this->doRequest($request);
    }

    /***** College Requests *****/
    public function makeCollegeRequest($endpoint)
    {
        if ($this->access_token == null) {
            $this->authorize();
        }
        $request = new Request();
        $uri = $this->college_url.$endpoint;
        $request->setUri($uri);
        $headers = $request->getHeaders()->addHeaders([
            "Authorization" => "Bearer ".$this->access_token]);
        $request->setHeaders($headers);
        return $request;
    }

    public function getCollegeStats($playerId, $type)
    {
        $request = $this->makeCollegeRequest("players/{$playerId}/{$type}");
        $result = $this->doRequest($request);
        if (array_key_exists('data', $result)) {
            return $result['data'];
        } else {
            return $result;
        }
    }

    public function getCollegeTeamStats($year, $teamId, $type)
    {
        $request = $this->makeCollegeRequest("seasons/{$year}/teams/{$teamId}/{$type}");
        $result = $this->doRequest($request);
        if (!array_key_exists('data', $result)) {
            return $result;
        }
        return $result['data'];
    }

    public function getCollegePlayers($year)
    {
        $request = $this->makeCollegeRequest("seasons/{$year}/players");
        $result = $this->doRequest($request);
        return $result['data'];
    }

    public function getCollegePassing($year, $type, $params = [])
    {
        $defaultArray = $this->default_array;
        /**
         * MetricGroups:(1=passing, 5=receiving, 3=rushing, 14=offensive line, 9=passDef, 10=passRush, 11=runDef, 12=returning)
         */
        $metricGroup = [
            "passing" => 1,
            "rushing" => 3,
            "receiving" => 5,
            "blocking" => 14,
            "passDef" => 9,
            "passRush" => 10,
            "runDef" => 11,
            "return" => 12
        ];

        if (!empty($params)) {
            $defaultArray = array_merge($defaultArray, $params);
        }

        $defaultArray['MetricGroup'] = $metricGroup[$type];
        $defaultArray['TimeFilters.SeasonFrom'] = $year;
        $defaultArray['TimeFilters.SeasonTo'] = $year;
        $defaultArray['Result'] = "starts";

        $request = $this->makeCollegeRequest('players/query');
        foreach ($defaultArray as $query => $value) {
            $request->getPost()->set($query, $value);
        }

        $request->setMethod(Request::METHOD_POST);
        $response = $this->doRequest($request);
        return $response['data'];
    }

    public function getCollegeTeamPassing($year, $type, $params = [])
    {
        $defaultArray = $this->default_array;
        /**
         * MetricGroups:(1=passing, 5=receiving, 3=rushing, 14=offensive line, 9=passDef, 10=passRush, 11=runDef, 12=returning)
         */
        $metricGroup = [
            "passing" => 1,
            "rushing" => 3,
            "receiving" => 5,
            "blocking" => 14,
            "passDef" => 9,
            "passRush" => 10,
            "runDef" => 11,
            "return" => 12
        ];

        if (!empty($params)) {
            $defaultArray = array_merge($defaultArray, $params);
        }

        $defaultArray['MetricGroup'] = $metricGroup[$type];
        $defaultArray['TimeFilters.SeasonFrom'] = $year;
        $defaultArray['TimeFilters.SeasonTo'] = $year;
        $defaultArray['Result'] = "starts";

        $request = $this->makeCollegeRequest('teams/query');
        foreach ($defaultArray as $query => $value) {
            $request->getPost()->set($query, $value);
        }

        $request->setMethod(Request::METHOD_POST);
        $response = $this->doRequest($request);
        return $response['data'];
    }


}