<?php
// module/Album/view/album/album/edit.phtml:

$title = 'Edit Player';
$this->headTitle($title);
?>
<div class="section container full-height white">
    <div class="row container">
        <h1><?= $this->escapeHtml($title) ?></h1>
        <?php
        $firstName = $form->get('first_name');
        $firstName->setAttribute('class', 'form-control');
        $firstName->setAttribute('placeholder', 'First Name');

        $lastName = $form->get('last_name');
        $lastName->setAttribute('class', 'form-control');
        $lastName->setAttribute('placeholder', 'Last Name');

        $position = $form->get('position');
        $position->setAttribute('class', 'form-control');
        $positionValue = $position->getValue();

        $team = $form->get('team');
        $team->setAttribute('class', 'form-control');
        $team->setAttribute('placeholder', 'Team');

        $player_info = $form->get('player_info');
        $player_info->setAttribute('class', 'form-control');
        $player_info->setAttribute('placeholder', 'player info');

        $team_info = $form->get('team_info');
        $team_info->setAttribute('class', 'form-control');
        $team_info->setAttribute('placeholder', 'player info');

        $api_info = $form->get('api_info');
        $api_info->setAttribute('class', 'form-control');
        $api_info->setAttribute('placeholder', 'player info');

        $injury_info = $form->get('injury_info');
        $injury_info->setAttribute('class', 'form-control');
        $injury_info->setAttribute('placeholder', 'player info');

        $metrics = $form->get('metrics');
        $metrics->setAttribute('class', 'form-control');
        $metrics->setAttribute('placeholder', 'player info');
        if (!$metrics->getValue()){
            $form->get('metrics')->setValue('{"fortyTime": "","broadJump": "","verticalJump": "","shuttle": "","cone":"", "benchPress":""}');
        };

        $percentiles = $form->get('percentiles');
        $percentiles->setAttribute('class', 'form-control');
        $percentiles->setAttribute('placeholder', 'percentiles');

        $collegeStats = $form->get('college_stats');
        $collegeStats->setAttribute('class', 'form-control');
        $collegeStats->setAttribute('placeholder', 'college_stats');

        if (!$collegeStats->getValue()){
            $collegeStats->setValue('{"2014": {"recs": "", "year": "2014", "class": "", "games": "", "recAvg": "", "recTds": "", "recYds": "", "rushes": "", "totals": {"tds": "", "yds": "", "recs": "", "returnTds": "", "returnYds": ""}, "college": "", "rushAvg": "", "rushTds": "", "rushYds": "", "position": "", "conference": ""}}');
        };

        $image1 = $form->get('image1');
        $image1->setAttribute('class', 'form-control');
        $image1->setAttribute('placeholder', 'image1');

        $image2 = $form->get('image2');
        $image2->setAttribute('class', 'form-control');
        $image2->setAttribute('placeholder', 'image2');

        $image3 = $form->get('image3');
        $image3->setAttribute('class', 'form-control');
        $image3->setAttribute('placeholder', 'image3');

        $image4 = $form->get('image4');
        $image4->setAttribute('class', 'form-control');
        $image4->setAttribute('placeholder', 'image4');

        $image5 = $form->get('image5');
        $image5->setAttribute('class', 'form-control');
        $image5->setAttribute('placeholder', 'image5');

        $headshot = $form->get('headshot');
        $headshot->setAttribute('class', 'form-control');
        $headshot->setAttribute('placeholder', 'headshot');

        $submit = $form->get('submit');
        $submit->setAttribute('class', 'btn btn-primary');

        $form->setAttribute('action', $this->url('admin', [
            'action' => 'editPlayer',
            'id'     => $id,
        ]));

        //college
        $collegeSets = $form->get('college')->getFieldsets();
        $form->prepare();

        echo $this->form()->openTag($form);
        ?>
        <div class="form-group col m6">
            <?= $this->formLabel($firstName) ?>
            <?= $this->formElement($firstName) ?>
            <?= $this->formElementErrors()->render($firstName, ['class' => 'help-block']) ?>
        </div>

        <div class="form-group col m6">
            <?= $this->formLabel($lastName) ?>
            <?= $this->formElement($lastName) ?>
            <?= $this->formElementErrors()->render($lastName, ['class' => 'help-block']) ?>
        </div>

        <div class="form-group col m6">
            <?= $this->formLabel($position) ?>
            <?= $this->formElement($position) ?>
            <?= $this->formElementErrors()->render($lastName, ['class' => 'help-block']) ?>
        </div>


        <div class="form-group col m6 my-2">
            <?= $this->formLabel($team) ?>
            <?= $this->formElement($team) ?>
            <?= $this->formElementErrors()->render($team, ['class' => 'help-block']) ?>
        </div>

        <fieldset>
            <legend>Player Info</legend>

            <div class="form-group col m12">
                <?= $this->formCollection($form->get('body')) ?>
                <ul class="collapsible expandable">
                    <li>
                        <div class="collapsible-header"><i class="material-icons">filter_drama</i>Player Info Json</div>
                        <div class="collapsible-body">
                            <?= $this->formLabel($player_info) ?>
                            <?= $this->formElement($player_info) ?>
                            <?= $this->formElementErrors()->render($player_info, ['class' => 'help-block']) ?>
                            <a href="" class="prettyPrint" onclick="prettyPrint()">Pretty Print</a>
                        </div>
                    </li>
                </ul>
            </div>
        </fieldset>

        <fieldset>
            <legend>Team Info</legend>
            <div class="form-group col m12">
                <?= $this->formCollection($form->get('teamFieldset')) ?>
                <ul class="collapsible expandable">
                    <li>
                        <div class="collapsible-header"><i class="material-icons">filter_drama</i>Team Info Json</div>
                        <div class="collapsible-body">
                            <?= $this->formLabel($team_info) ?>
                            <?= $this->formElement($team_info) ?>
                            <?= $this->formElementErrors()->render($team_info, ['class' => 'help-block']) ?>
                            <a href="" class="prettyPrint" onclick="prettyPrint()">Pretty Print</a>
                        </div>
                    </li>
                </ul>
            </div>
        </fieldset>

        <fieldset>
            <legend>API Info</legend>
            <div class="form-group col m12">
                <?= $this->formCollection($form->get('apiFieldset')) ?>
                <ul class="collapsible expandable">
                    <li>
                        <div class="collapsible-header"><i class="material-icons">filter_drama</i>API Info Json</div>
                        <div class="collapsible-body">
                            <?= $this->formLabel($api_info) ?>
                            <?= $this->formElement($api_info) ?>
                            <?= $this->formElementErrors()->render($api_info, ['class' => 'help-block']) ?>
                            <a href="" class="prettyPrint" onclick="prettyPrint()">Pretty Print</a>
                        </div>
                    </li>
                </ul>
            </div>
        </fieldset>

        <fieldset>
            <legend>Injury Info</legend>
            <div class="form-group col m12">
                <?= $this->formLabel($injury_info) ?>
                <?= $this->formElement($injury_info) ?>
                <?= $this->formElementErrors()->render($injury_info, ['class' => 'help-block']) ?>
                <a href="" class="prettyPrint" onclick="prettyPrint()">Pretty Print</a>
            </div>
        </fieldset>

        <fieldset>
            <legend>Metrics</legend>
            <fieldset>
                <legend>Combine</legend>
                <?php if ($positionValue == "QB") : ?>
                    <div class="form-group col m2">
                        <?= $this->formLabel($form->get('throwVelocity')); ?>
                        <?= $this->formElement($form->get('throwVelocity')); ?>
                        <?= $this->formElementErrors()->render($form->get('throwVelocity'), ['class' => 'help-block']); ?>
                    </div>
                <?php endif; ?>
                <div class="form-group col m2">
                    <?= $this->formLabel($form->get('benchPress')); ?>
                    <?= $this->formElement($form->get('benchPress')); ?>
                    <?= $this->formElementErrors()->render($form->get('benchPress'), ['class' => 'help-block']); ?>
                </div>
                <div class="form-group col m2">
                    <?= $this->formLabel($form->get('fortyTime')); ?>
                    <?= $this->formElement($form->get('fortyTime')); ?>
                    <?= $this->formElementErrors()->render($form->get('fortyTime'), ['class' => 'help-block']); ?>
                </div>
                <div class="form-group col m2">
                    <?= $this->formLabel($form->get('shuttle')); ?>
                    <?= $this->formElement($form->get('shuttle')); ?>
                    <?= $this->formElementErrors()->render($form->get('shuttle'), ['class' => 'help-block']); ?>
                </div>
                <div class="form-group col m2">
                    <?= $this->formLabel($form->get('cone')); ?>
                    <?= $this->formElement($form->get('cone')); ?>
                    <?= $this->formElementErrors()->render($form->get('cone'), ['class' => 'help-block']); ?>
                </div>
                <div class="form-group col m2">
                    <?= $this->formLabel($form->get('verticalJump')); ?>
                    <?= $this->formElement($form->get('verticalJump')); ?>
                    <?= $this->formElementErrors()->render($form->get('verticalJump'), ['class' => 'help-block']); ?>
                </div>
                <div class="form-group col m2">
                    <?= $this->formLabel($form->get('broadJump')); ?>
                    <?= $this->formElement($form->get('broadJump')); ?>
                    <?= $this->formElementErrors()->render($form->get('broadJump'), ['class' => 'help-block']); ?>
                </div>
            </fieldset>
            <div>
                <ul class="collapsible expandable">
                    <li>
                        <div class="collapsible-header"><i class="material-icons">filter_drama</i>Metrics</div>
                        <div class="collapsible-body">
                            <?= $this->formCollection($form->get('metricsFieldset')) ?>
                        </div>
                    </li>
                    <li>
                        <div class="collapsible-header"><i class="material-icons">filter_drama</i>Metrics Json</div>
                        <div class="collapsible-body">
                            <?= $this->formLabel($metrics) ?>
                            <?= $this->formElement($metrics) ?>
                            <?= $this->formElementErrors()->render($metrics, ['class' => 'help-block']) ?>
                            <a href="" class="prettyPrint" onclick="prettyPrint()">Pretty Print</a>
                        </div>
                    </li>
                </ul>
            </div>
        </fieldset>

        <fieldset>
            <legend>Percentiles</legend>
            <ul class="collapsible expandable">
                <li>
                    <div class="collapsible-header"><i class="material-icons">filter_drama</i>Percentiles Json</div>
                    <div class="collapsible-body">
                        <?= $this->formLabel($percentiles) ?>
                        <?= $this->formElement($percentiles) ?>
                        <?= $this->formElementErrors()->render($percentiles, ['class' => 'help-block']) ?>
                        <a href="" class="prettyPrint" onclick="prettyPrint()">Pretty Print</a>
                    </div>
                </li>
            </ul>
        </fieldset>


        <?php if (array_key_exists('college-0', $collegeSets)): ?>
        <fieldset>
            <legend>College Stats</legend>
            <ul class="collapsible">
                <li>
                    <div class='collapsible-header'><i class='material-icons'>filter_drama</i>Freshman</div>
                    <div class='collapsible-body'><?= $this->formCollection($collegeSets['college-0']); ?></div>
                </li>
                <li>
                    <div class='collapsible-header'><i class='material-icons'>filter_drama</i>Sophmore</div>
                    <div class='collapsible-body'><?= $this->formCollection($collegeSets['college-1']); ?></div>
                </li>
                <li>
                    <div class='collapsible-header'><i class='material-icons'>filter_drama</i>Junior</div>
                    <div class='collapsible-body'><?= $this->formCollection($collegeSets['college-2']); ?></div>
                </li>
                <li>
                    <div class='collapsible-header'><i class='material-icons'>filter_drama</i>Senior</div>
                    <div class='collapsible-body'><?= $this->formCollection($collegeSets['college-3']); ?></div>
                </li>
            </ul>
            <ul class="collapsible expandable">
                <li>
                    <div class="collapsible-header"><i class="material-icons">filter_drama</i>College Json</div>
                    <div class="collapsible-body">
                        <?= $this->formLabel($collegeStats) ?>
                        <?= $this->formElement($collegeStats) ?>
                        <?= $this->formElementErrors()->render($collegeStats, ['class' => 'help-block']) ?>
                        <a href="" class="prettyPrint" onclick="prettyPrint()">Pretty Print</a>
                    </div>
                </li>
            </ul>
        </fieldset>
        <?php endif; ?>

        <fieldset>
            <legend>Images</legend>
            <div class="form-group col m6">
                <?= $this->formLabel($image1) ?>
                <?= $this->formElement($image1) ?>
                <?= $this->formElementErrors()->render($image1, ['class' => 'help-block']) ?>
                <a href="" class="prettyPrint" onclick="prettyPrint()">Pretty Print</a>
            </div>
            <div class="form-group col m6">
                <?= $this->formLabel($image2) ?>
                <?= $this->formElement($image2) ?>
                <?= $this->formElementErrors()->render($image1, ['class' => 'help-block']) ?>
                <a href="" class="prettyPrint" onclick="prettyPrint()">Pretty Print</a>
            </div>
            <div class="form-group col m6">
                <?= $this->formLabel($image3) ?>
                <?= $this->formElement($image3) ?>
                <?= $this->formElementErrors()->render($image1, ['class' => 'help-block']) ?>
                <a href="" class="prettyPrint" onclick="prettyPrint()">Pretty Print</a>
            </div>
            <div class="form-group col m6">
                <?= $this->formLabel($image4) ?>
                <?= $this->formElement($image4) ?>
                <?= $this->formElementErrors()->render($image1, ['class' => 'help-block']) ?>
                <a href="" class="prettyPrint" onclick="prettyPrint()">Pretty Print</a>
            </div>
            <div class="form-group col m6">
                <?= $this->formLabel($image5) ?>
                <?= $this->formElement($image5) ?>
                <?= $this->formElementErrors()->render($image1, ['class' => 'help-block']) ?>
                <a href="" class="prettyPrint" onclick="prettyPrint()">Pretty Print</a>
            </div>
            <div class="form-group col m6">
                <?= $this->formLabel($headshot) ?>
                <?= $this->formElement($headshot) ?>
                <?= $this->formElementErrors()->render($headshot, ['class' => 'help-block']) ?>
                <a href="" class="prettyPrint" onclick="prettyPrint()">Pretty Print</a>
            </div>
        </fieldset>

        <div class="form-group col m6 my-2">
            <?= $this->formSubmit($submit) ?>
        </div>


        <?php

        echo $this->formHidden($form->get('id'));
        echo $this->form()->closeTag();
        ?>
    </div>
</div>

<script>
    function prettyPrint() {
        var textArea = $(this).parent().find('textarea');

    }

    // $(".prettyPrint").on("click", function(e){
    //     e.preventDefault();
    //     var textArea = $(this).parent().find('textarea');
    //     var ugly = textArea.val();
    //     var obj = JSON.parse(ugly);
    //     var pretty = JSON.stringify(obj, undefined, 4);
    //     textArea.val(pretty);
    // });
</script>
