

<div class="section light full-height">
    <div class="row">
        <div class="col s12 m10 offset-m1 center">
            <h1 class="fade-in-out">Edit Players</h1>
            <div id="edit-players" class="container player-search my-2">
                <input class="typeahead" type="text" placeholder="Type In A Player's Name">
            </div>
        </div>
    </div>
</div>
<div class="section dark full-height">
    <div class="row">
        <div class="col s12 m10 offset-m1 center">
            <h1 class="fade-in-out">Edit Teams</h1>
            <div id="custom-templates" class="container my-2">
                <input class="typeahead" type="text" placeholder="Type In A Player's Name">
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var rlfData = <?=json_encode($jsVars, 512)?>;

    $(document).ready(function() {
        rlf.initSearch();
    });
</script>