

<div class="section light full-height">
    <div class="row">
        <div class="col s12 m10 offset-m1 center">
            <h1 class="fade-in-out">Edit Players</h1>
            <div id="edit-players" class="container player-search my-2">
                <input class="typeahead" type="text" placeholder="Type In A Player's Name">
            </div>
        </div>
    </div>
</div>
<div class="section dark full-height">
    <div class="row">
        <div class="col s4 m4 center">
            <h3 class="fade-in-out">Edit Teams</h3>
            <div id="custom-templates" class="container my-2">
                <input class="typeahead" type="text" placeholder="Type In A Player's Name">
            </div>
        </div>
        <div class="col s4 m4 center section dark">
            <a href="/manage-podcasts"><h3>Manage Podcasts</h3></a>
            <div class="btn-group" role="group" aria-label="Post actions">
                <a class="btn btn-primary dark" href="<?= $this->url('podcastAdmin/add') ?>">Add new podcast</a>
            </div>
        </div>
        <div class="col s4 m4 center section dark">
            <h3><a href="/manage-articles">Manage Articles</a></h3>
            <div class="btn-group" role="group" aria-label="Post actions">
                <a class="btn btn-primary dark" href="<?= $this->url('cms/add') ?>">Write new Article</a>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var rlfData = <?=json_encode($jsVars, 512)?>;

    $(document).ready(function() {
        rlf.initSearch();
    });
</script>