<?php
$this->headTitle('Sign in');

$this->mainMenu()->setActiveItemId('login');

$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Email address',
    'required' => true,
    'autofocus' => true
])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Password',
    'required' => true,
])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
$clientId = "_95TC9mhSPNvKnEMirH3N4LMDthwKL1dvRoVzvoY6eaFEU5qLxkCINJ_Kbejvgs1";
$redirectUri = "https://www.drafttradewin.com";
$scope = "";
$state = "";
$patreonLink = "https://www.patreon.com/oauth2/authorize?response_type=code&client_id={$clientId}&redirect_uri={$redirectUri}";
?>
<div class="section white container">
    <div class="container fullscreen">
<div class="row">
    <div class="col s12 m8 offset-m2 l4 offset-l4">
        <form class="form-signin" method="post">
            <h3 class="form-signin-heading">Please sign in</h3>
            <?php if ($isLoginError): ?>
                <div class="alert alert-warning" role="alert">
                    Incorrect login and/or password.
                    <a href="<?= $this->url('reset-password') ?>">Forgot password?</a>
                </div>
            <?php endif; ?>
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <div class="checkbox">
                <label>
                    <?= $this->formElement($form->get('remember_me')); ?> Remember me
                </label>
            </div>
            <?= $this->formElement($form->get('redirect_url')); ?>
            <?= $this->formElement($form->get('csrf')) ?>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        </form>
        <a href="<?=$this->signUpLink ?>"><img src="/images/login_with_patreon.png"></a>
    </div>
</div>
    </div>
</div>