<?php
?>
<div class="section white full-height container">
    <div class="row container">
        <div class="col s12">
            <ul class="tabs">
                <li class="tab col s3"><a class="active" href="#team1"><?= $team1->name ?></a></li>
                <li class="tab col s3"><a href="#team2"><?= $team2->name ?></a></li>
            </ul>
        </div>
        <div id="team1" class="col s12 <?= $team1->name ?>">
            <div class="row">
                <h4 class="center">Offensive Line</h4>
                <div class="col s11 prospect z-depth-1 hoverable waves-block" style="background:white; position: relative; height:450px;">
                    <canvas id="team1-canvas" width="75%"></canvas>
                </div>
                <div class="col s1">
                    <a class="waves-effect waves-light btn-small active" id="team1-runBlock">RunBlock</a>
                    <a class="waves-effect waves-light btn-small" id="team1-passBlock">PassRush</a>
                </div>
                <h4 class="center">Receiver Matchups</h4>
                <div class="row container">
                    <div class="col s2"></div>
                    <div class="col s4 card">
                        <h5 class="center">Free Safety</h5>
                        <table id="team1-FS"></table>
                    </div>
                    <div class="col s4 card">
                        <h5 class="center">Strong Safety</h5>
                        <table class="team1-SS"></table>
                    </div>
                    <div class="col s2"></div>
                </div>
                <div class="row container">
                    <hr>
                    <div class="col s6 team1-WRs card">
                        <div id="team1-WR1-container" class="col s6">
                            <h5 class="center">LWR</h5>
                            <table id="team1-WR1" width="100%"></table>
                        </div>
                        <div class="team1-CB-container" class="col s10">
                            <div class="col s5">
                                <ul class="team1-tabs tabs">
                                    <li id="team1-CB1-link" class="tab col"><a href="#team1-WR1-CB1-container" class="active">LCB</a></li>
                                    <li id="team1-CB2-link" class="tab col"><a href="#team1-WR1-CB2-container">RCB</a></li>
                                </ul>
                            </div>
                            <div id="team1-WR1-CB1-container" class="col s6">
                                <table id="team1-WR1-CB1" class="team1-CB1"></table>
                            </div>
                            <div id="team1-WR1-CB2-container" class="col s6">
                                <table id="team1-WR1-CB2" class="team1-CB2"></table>
                            </div>
                        </div>
                    </div>
                    <div class="col s6 team1-WRs card">
                        <div id="team1-WR2-container" class="col s6">
                            <h5 class="center">RWR</h5>
                            <table id="team1-WR2" width="100%"></table>
                        </div>
                        <div class="team1-CB-container" class="col s10">
                            <div class="col s5">
                                <ul class="team1-tabs tabs">
                                    <li id="team1-CB1-link" class="tab col"><a href="#team1-WR2-CB1-container">LCB</a></li>
                                    <li id="team1-CB2-link" class="tab col"><a href="#team1-WR2-CB2-container" class="active" >RCB</a></li>
                                </ul>
                            </div>
                            <div id="team1-WR2-CB1-container" class="col s6">
                                <table id="team1-WR1-CB1" class="team1-CB1"></table>
                            </div>
                            <div id="team1-WR2-CB2-container" class="col s6">
                                <table id="team1-WR1-CB1" class="team1-CB2"></table>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row container">
                    <hr>
                    <div class="col s6 team1-WRs card">
                        <div id="team1-slot-container" class="col s6">
                            <h5 class="center">Slot</h5>
                            <table id="team1-slot" width="100%"></table>
                        </div>
                        <div class="team1-slot-CB-container" class="col s10">
                            <div class="col s5">
                                <ul class="team1-tabs tabs">
                                    <li id="team1-slot-CB-link" class="tab col"><a href="#team1-slot-CB1-container" class="active">Slot CB</a></li>
                                    <li id="team1-slot-SS-link" class="tab col"><a href="#team1-slot-SS1-container">SS</a></li>
                                </ul>
                            </div>
                            <div id="team1-slot-CB1-container" class="col s6">
                                <table id="team1-slot-CB" class="team1-slot-CB"></table>
                            </div>
                            <div id="team1-slot-SS1-container" class="col s6">
                                <table id="team1-SS" class="team1-SS"></table>
                            </div>
                        </div>
                    </div>
                    <div class="col s6 team1-WRs card">
                        <div id="team1-TE1-container" class="col s6">
                            <h5 class="center">TE</h5>
                            <table id="team1-TE1" width="100%"></table>
                        </div>
                        <div class="team1-CB-container" class="col s10">
                            <div class="col s5">
                                <ul class="team1-tabs tabs">
                                    <li id="team1-MLB-link" class="tab col"><a href="#team1-TE-MLB-container" class="active">MLB</a></li>
                                    <li id="team1-SS-link" class="tab col"><a href="#team1-TE-SS-container">SS</a></li>
                                </ul>
                            </div>
                            <div id="team1-TE-MLB-container" class="col s6">
                                <table id="team1-MLB" class="team1-MLB"></table>
                            </div>
                            <div id="team1-TE-SS-container" class="col s6">
                                <table id="team1-SS" class="team1-SS"></table>
                            </div>
                        </div>
                    </div>
                </div>
                <h4 class="center">Rushing Matchups</h4>
                <div class="row container">
                    <div class="col s4">
                        <div class="col s12">
                            <ul class="tabs">
                                <li class="tab col s3"><a class="active" href="#team1-RB1-container">RB1</a></li>
                                <li class="tab col s3"><a href="#team1-RB2-container">RB2</a></li>
                            </ul>
                        </div>
                        <div id="team1-RB1-container" class="col s12">
                            <h5 class="center">RB1</h5>
                            <table id="team1-RB1" width="100%"></table>
                        </div>
                        <div id="team1-RB2-container" class="col s12">
                            <h5 class="center">RB2</h5>
                            <table id="team1-RB2" width="100%"></table>
                        </div>
                    </div>
                    <div class="col s2">
                        <h5 class="center">VS.</h5>
                    </div>
                    <div class="col s6 card">
                        <h5 class="center">Linebackers</h5>
                        <table id="team1-LBs" width="100%"></table>
                    </div>
                </div>



                </div>
            </div>
        </div>
        <div id="team2" class="col s12 <?= $team2->name ?>">
            <div class="row">
                <h4 class="center">Offensive Line</h4>
                <div class="col s11 prospect z-depth-1 hoverable waves-block" style="background:white; position: relative; height:450px;">
                    <canvas id="team2-canvas" width="75%"></canvas>
                </div>
                <div class="col s1">
                    <a class="waves-effect waves-light btn-small active" id="team2-runBlock">RunBlock</a>
                    <a class="waves-effect waves-light btn-small" id="team2-passBlock">PassRush</a>
                </div>
                <h4 class="center">Receiver Matchups</h4>
                <div class="row container">
                    <div class="col s2"></div>
                    <div class="col s4 card">
                        <h5 class="center">Free Safety</h5>
                        <table id="team2-FS"></table>
                    </div>
                    <div class="col s4 card">
                        <h5 class="center">Strong Safety</h5>
                        <table id="team2-SS"></table>
                    </div>
                    <div class="col s2"></div>
                </div>
                <div class="row container">
                    <div class="col s6 card">
                        <h5>X WR</h5>
                        <table id="team2-LWR">
                        </table>
                    </div>
                    <div class="col s6 card">
                        <h5>Z WR</h5>
                        <table id="team2-RWR">
                        </table>
                    </div>
                    <div class="col s6 card">
                        <h5>Slot</h5>
                        <table id="team2-SWR">
                        </table>
                    </div>

                    <div class="col s6 card">
                        <h5>TE</h5>
                        <table id="team2-TE">
                        </table>
                    </div>
                </div>
                <h4 class="center">Rushing Matchups</h4>
                <div class="row container">
                    <div class="col s4 team2-RBs">
                        <div class="col s12">
                            <ul class="team2-tabs tabs">
                                <li id="team2-RB1-link" class="tab col s3"><a href="#team2-RB1-container" class="active">RB1</a></li>
                                <li id="team2-RB2-link" class="tab col s3"><a href="#team2-RB2-container">RB2</a></li>
                            </ul>
                        </div>
                        <div id="team2-RB1-container" class="col s12">
                            <h5 class="center">RB1</h5>
                            <table id="team2-RB1" width="100%"></table>
                        </div>
                        <div id="team2-RB2-container" class="col s12">
                            <h5 class="center">RB2</h5>
                            <table id="team2-RB2" width="100%"></table>
                        </div>
                    </div>
                    <div class="col s2">
                        <h5 class="center">VS.</h5>
                    </div>
                    <div class="col s6 card">
                        <h5 class="center">Linebackers</h5>
                        <table id="team2-LBs" width="100%"></table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    var rlfData = <?=json_encode($jsVars, 512)?>;
    rlf.initMatchupPage();
    $(document).ready(function() {
        $(".determinate").each(function(){
            var width = $(this).width()/$(this).parent().width();
            if (width > .69) {
                $(this).css("background-color", "green");
            }

            if (width < .69 && width > .40) {
                $(this).css("background-color", "yellow");
            }

            if (width < .40) {
                $(this).css("background-color", "red");
            }
        });

    });
</script>