<?php
?>
<div class="section white full-height container">
    <div class="row">
        <h4>Offensive Line</h4>
        <div class="col s12 prospect z-depth-1 hoverable waves-block" style="background:white; position: relative; height:450px;">
            <canvas id="canvas" width="75%"></canvas>
        </div>
    </div>
    <div class="row">
        <div class="col s4">
            <h5>LWR Matchup</h5>
            <table id="LWR">
            </table>
        </div>
        <div class="col s4">
            <h5>SWR Matchup</h5>
            <table id="SWR">
            </table>
        </div>
        <div class="col s4">
            <h5>RWR Matchup</h5>
            <table id="RWR">
            </table>
        </div>
    </div>
</div>

<script>
    var rlfData = <?=json_encode($jsVars, 512)?>;
    $(document).ready(function() {
        rlf.initMatchupPage();
    });
</script>