<?php
?>
<div class="section white full-height container">
    <div class="row container">
        <h2 class="center">Passing By Air Yard Splits</h2>
        <div class="row">
            <h5>Behind the line of scrimmage</h5>
            <div class="col s3 ">
                <p class="black-text">% of Targets: </p>
                <p class="black-text">On Target %: </p>
            </div>
            <div class="col s3">1</div>
            <div class="col s3">1</div>
            <div class="col s3">1</div>
        </div>
        <div class="row">
            <h5>Short: 1 - 9 yards</h5>
            <div class="col s3">1</div>
            <div class="col s3">1</div>
            <div class="col s3">1</div>
            <div class="col s3">1</div>
        </div>
        <div class="row">
            <h5>Intermediate: 10 - 19 yards</h5>
            <div class="col s3">1</div>
            <div class="col s3">1</div>
            <div class="col s3">1</div>
            <div class="col s3">1</div>
        </div>
        <div class="row">
            <h5>Deep: 20+ yards</h5>
            <div class="col s3">1</div>
            <div class="col s3">1</div>
            <div class="col s3">1</div>
            <div class="col s3">1</div>
        </div>
    </div>
</div>
