<?php
    $json = json_encode($this->jsVars);
    $percents = [];
    foreach($players[0]['percentiles'][0] as $key => $value) {
        $nf = new NumberFormatter('en_US', NumberFormatter::ORDINAL);
        $percents[0][$key] = $nf->format($value);
    }

    foreach($players[1]['percentiles'][0] as $key => $value) {
        $nf = new NumberFormatter('en_US', NumberFormatter::ORDINAL);
        $percents[1][$key] = $nf->format($value);
    }
?>

<div class="section container page-container player-container">
    <div class="row center">
        <div class="col s4">
            <div class="input-field col s12 compare-search-field">
                <input type="text" class="typeahead right compare-search" id="compare-1" class="autocomplete" placeholder="Search for Players">
            </div>
        </div>
        <div class="col s4">
            <button class="btn-large waves-effect waves-light" id="compare-button">Compare Players
                <i class="material-icons right">send</i>
            </button>
        </div>
        <div class="col s4">
            <div class="input-field col s12 compare-search-field">
                <input type="text" class="typeahead right compare-search" id="compare-2" class="autocomplete" placeholder="Search for Players">
            </div>
        </div>
    </div>
    <div class="row player-header section scrollspy" id="player-header">
        <div class="col m4 s12 profile">
            <div class="card small player-card hoverable">
                <div class="card-image waves-effect waves-block waves-light">
                    <div class="carousel carousel-slider activator">
                        <a class="carousel-item" href="#one!"><img  src="<?= $players[0]['image1']?>" style="height:280px"></a>
                        <a class="carousel-item" href="#two!"><img src="<?= $players[0]['image2'] ?>" style="height:280px"></a>
                        <a class="carousel-item" href="#three!"><img src="<?= $players[0]['image3'] ?>" style="height:280px"></a>
                    </div>
                </div>
                <div class="card-content player-card-content center">
                    <a class="btn-floating right halfway-fab waves-effect waves-light red activator"><i class="material-icons">arrow_upward</i></a>
                    <span class="player-title activator white-text text-darken-4"><?= $players[0]['firstName']." ".$players[0]['lastName'] ?></span>
                    <p class="player-title activator yellow-text text-darken-4">#19 <?=$players[0]['position']?> <?= $players[0]['team']?></p>
                </div>
                <div class="card-reveal player-card-reveal">
                    <span class="card-title white-text">Player Info<i class="material-icons right">arrow_downward</i></span>
                    <p>Height: <?= $players[0]['height']?> (<?= $percents[0]['height'] ?> percentile)</p>
                    <p>Weight: <?= $players[0]['weight']?> lbs (<?= $percents[0]['weight'] ?> percentile)</p>
                    <p>Arms: <?= $players[0]['arms']?> inches (<?= $percents[0]['arms'] ?> percentile)</p>
                    <p>BMI: <?= $players[0]['bmi']?> (<?= $percents[0]['bmi'] ?> percentile)</p>
                    <p>College: <?= $players[0]['college']?></p>
                    <p>Draft Pick: <?= $players[0]['draftPick']?> | Draft Year: <?= $players[0]['draftYear']?> </p>
                </div>
            </div>
        </div>
        <div class="col m4 s12 measurables">
            <div class="card player-card small hoverable">
                <div class="card-image waves-effect waves-block waves-light">
                    <div id="radar-graph" style="width:400px; height:400px; margin:auto" class="scale-transition scale-out">

                    </div>
                </div>
                <div class="card-content player-card-content center">>
                    <span class="player-title white-text text-darken-4">Measurables</span>
                </div>
                <div class="card-reveal player-card-reveal">
                    <span class="card-title white-text">Workout Metrics<i class="material-icons right">arrow_downward</i></span>
                    <p>40 yd dash: <?= (!empty($players[0]['metrics'][0]['fortyTime'])) ? $players[0]['metrics'][0]['fortyTime']." seconds (".$percents[0]['fortyTime']." percentile)" : "Not Available"?></p>
                    <p>Bench Press: <?= (!empty($players[0]['metrics'][0]['benchPress'])) ? $players[0]['metrics'][0]['benchPress']." reps (".$percents[0]['benchPress']." percentile)" : "Not Available"?></p>
                    <p>3 cone: <?= (!empty($players[0]['metrics'][0]['cone'])) ? $players[0]['metrics'][0]['cone']." seconds (".$percents[0]['cone']." percentile)" : "Not Available" ?></p>
                    <p>Shuttle: <?= (!empty($players[0]['metrics'][0]['shuttle'])) ? $players[0]['metrics'][0]['shuttle']." seconds (".$percents[0]['shuttle']." percentile)" : "Not Available" ?></p>
                    <p>Vertical Jump: <?= (!empty($players[0]['metrics'][0]['verticalJump'])) ? $players[0]['metrics'][0]['verticalJump']." inches (".$percents[0]['verticalJump']." percentile)" : "Not Available" ?></p>
                    <p>Broad Jump: <?= (!empty($players[0]['metrics'][0]['broadJump'])) ? $players[0]['metrics'][0]['broadJump']." inches (".$percents[0]['broadJump']." percentile)" : "Not Available"?></p>
                </div>
            </div>
        </div>
            <div class="col m4 s12 profile">
                <div class="card small player-card hoverable">
                    <div class="card-image waves-effect waves-block waves-light">
                        <div class="carousel carousel-slider activator">
                            <a class="carousel-item" href="#one!"><img  src="<?= $players[1]['image1']?>" style="height:280px"></a>
                            <a class="carousel-item" href="#two!"><img src="<?= $players[1]['image2'] ?>" style="height:280px"></a>
                            <a class="carousel-item" href="#three!"><img src="<?= $players[1]['image3'] ?>" style="height:280px"></a>
                        </div>
                    </div>
                    <div class="card-content player-card-content center">
                        <a class="btn-floating right halfway-fab waves-effect waves-light red activator"><i class="material-icons">arrow_upward</i></a>
                        <span class="player-title activator white-text text-darken-4"><?= $players[1]['firstName']." ".$players[1]['lastName'] ?></span>
                        <p class="player-title activator yellow-text text-darken-4">#19 <?=$players[1]['position']?> <?= $players[1]['team']?></p>
                    </div>
                    <div class="card-reveal player-card-reveal">
                        <span class="card-title white-text">Player Info<i class="material-icons right">arrow_downward</i></span>
                        <p>Height: <?= $players[1]['height']?> (<?= $percents[1]['height'] ?> percentile)</p>
                        <p>Weight: <?= $players[1]['weight']?> lbs (<?= $percents[1]['weight'] ?> percentile)</p>
                        <p>Arms: <?= $players[1]['arms']?> inches (<?= $percents[1]['arms'] ?> percentile)</p>
                        <p>BMI: <?= $players[1]['bmi']?> (<?= $percents[1]['bmi'] ?> percentile)</p>
                        <p>College: <?= $players[1]['college']?></p>
                        <p>Draft Pick: <?= $players[1]['draftPick']?> | Draft Year: <?= $players[1]['draftYear']?> </p>
                    </div>
                </div>
            </div>
    </div>
    <div class="row player-prospect section scrollspy" id="player-prospect">
        <a class="waves-effect waves-light btn-small right center modal-trigger" href="#modal2">Explain<i class="material-icons">live_help</i></a>
        <div class="col s12 center row-title"><h6>Prospect Breakdown</h6></div>
        <div class="col m2 s12 skillset z-depth-1 hoverable" id="player1-skill">
            <div class="slot-box center">
                <div style="margin-top:10px" class="role-one-title"></div>
                <div class="role-one-score"></div>
                <div class="progress role-one-bar">
                    <div class="determinate" style="width: 0%"></div>
                </div>
            </div>
            <div class="deep-box center">
                <div style="margin-top:10px" class="role-two-title"></div>
                <div class="role-two-score"></div>
                <div class="progress role-two-bar">
                    <div class="determinate" style="width: 0%"></div>
                </div>
            </div>
            <div class="alpha-box center">
                <div style="margin-top:10px" class="role-three-title"></div>
                <div class="role-three-score"></div>
                <div class="progress role-three-bar">
                    <div class="determinate" style="width: 0%"></div>
                </div>
            </div>
        </div>
        <div class="col m8 s12 prospect z-depth-1 hoverable">
            <div id="prospect-graph" style="margin:auto"></div>
        </div>
        <div class="col m2 s12 skillset z-depth-1 hoverable" id="player2-skill">
            <div class="slot-box center">
                <div style="margin-top:10px" class="role-one-title"></div>
                <div class="role-one-score"></div>
                    <div class="progress role-one-bar">
                        <div class="determinate" style="width: 0%"></div>
                    </div>
            </div>
            <div class="deep-box center">
                <div style="margin-top:10px" class="role-two-title"></div>
                <div class="role-two-score"></div>
                <div class="progress role-two-bar">
                    <div class="determinate" style="width: 0%"></div>
                </div>
            </div>
            <div class="alpha-box center">
                <div style="margin-top:10px" class="role-three-title"></div>
                <div class="role-three-score"></div>
                <div class="progress role-three-bar">
                    <div class="determinate" style="width: 0%"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="player-situation scrollspy col s6" id="player-situation">
            <a class="waves-effect waves-light btn-small right center modal-trigger" href="#modal1">Explain<i class="material-icons">live_help</i></a>
            <div class="col s center row-title"><h6>Situation Breakdown</h6></div>
            <div class="col m4 s12 fit z-depth-1 hoverable">
                <div id="fit-graph"></div>
            </div>
            <div class="col m4 s12 volume z-depth-1 hoverable">
                <div id="volume-graph"></div>
            </div>
            <div class="col m4 s12 support z-depth-1 hoverable">
                <div id="support-graph"></div>
            </div>
        </div>
    </div>

</div>
<div class="parallax-container">
    <div class="parallax"><img src="https://pbs.twimg.com/profile_banners/733170759829327874/1527727987/1500x500"></div>
</div>
<div class="section container page-container player-container">
    <div class="row player-stats section scrollspy hoverable" id="player-stats">
        <div class="col s12 center row-title"><h6>Stats</h6></div>
        <div class="col s12">
            <ul class="tabs">
                <li class="tab col s3"><a href="#test1">NFL Stats</a></li>
                <li class="tab col s3"><a class="active" href="#test2">College Stats</a></li>
            </ul>
        </div>
        <div id="test1" class="col s12">NFL Stats</div>
        <div id="test2" class="col s12">
            <div class="col-sm-12">
                <table id="college-stats" class="display" width="100%"></table>
            </div>
        </div>
    </div>
    <div class="row player-takes section scrollspy hoverable" id="player-takes">
        <div class="col s12 center row-title"><h6>Taeks</h6></div>
        <div class="col s12">
            <ul class="tabs">
                <li class="tab col s3"><a class="active" href="#article">Articles</a></li>
                <li class="tab col s3"><a href="#audio">Audio</a></li>
                <li class="tab col s3"><a href="#video">Video</a></li>
            </ul>
        </div>
        <div id="article" class="col s12">Articles</div>
        <div id="audio" class="col s12">Audio</div>
        <div id="video" class="col s12">Video</div>
    </div>
</div>
<div class="player-menu">
    <ul class="section table-of-contents">
        <li><a href="#player-header">Measurables</a></li>
        <li><a href="#player-prospect">Prospect</a></li>
        <li><a href="#player-situation">Situation</a></li>
        <li><a href="#player-stats">Stats</a></li>
        <li><a href="#player-takes">Taeks</a></li>
    </ul>
</div>

<?php
    switch($players[0]['position']) {
        case "WR":
            $init = "rlf.initWrPage();";
            break;
        case "RB":
            $init = "rlf.initRbPage();";
            break;
        case "TE":
            $init = "rlf.initTePage();";
            break;
        default:
    }
?>

<script type="text/javascript">
    var rlfData = <?=$json?>;

    $(document).ready(function() {
        rlf.initComparePage();
    });
</script>

