<?php
// module/Album/view/album/album/index.phtml:

$title = 'Rookie Rankings';
$this->headTitle($title);
?>
<div class="section container full-height white full-height container">
    <div class="row container">
        <h1><?= $this->escapeHtml($title) ?></h1>
        <div class="row">
            <div class="col s12">
                <ul class="tabs">
                    <li class="tab col s3"><a class="active" href="#test1">Rookie WR</a></li>
                    <li class="tab col s3"><a href="#test2">Rookie RB</a></li>
                    <li class="tab col s3"><a href="#test4">Rookie TE</a></li>
                </ul>
            </div>
            <div id="test1" class="col s12">
                <ol>
                    <li><a href="/player/view/27445?JaMarrChase-NFL-FA-0" target="_blank">Ja'Marr Chase</a></li>
                    <li><a href="/player/view/27409?TerraceMarshall-NFL-FA-0" target="_blank">Terrace Marshall</a></li>
                    <li><a href="/player/view/27417?RondaleMoore-NFL-FA-0" target="_blank" >Rondale Moore</a></li>
                    <li><a href="/player/view/27432?ElijahMoore-NFL-FA-0" target="_blank" >Elijah Moore</a></li>
                    <li><a href="/player/view/27466?RashodBateman-NFL-FA-0" target="_blank" >Rashod Batemon</a></li>
                    <li><a href="/player/view/27451?DeVontaSmith-NFL-FA-0" target="_blank" >Devonta Smith</a></li>
                    <li><a href="/player/view/27407?JaylenWaddle-NFL-FA-0" target="_blank" >Jaylen Waddle</a></li>
                    <li><a href="/player/view/27408?AmonRaStBrown-NFL-FA-0" target="_blank" >Amon-ra St. Brown</a></li>
                    <li><a href="/player/view/27465?DyamiBrown-NFL-FA-0" target="_blank" >Dyami Brown</a></li>
                    <li><a href="/player/view/27441?NicoCollins-NFL-FA-0" target="_blank" >Nico Collins</a></li>
                    <li><a href="/player/view/27498?MichaelStrachan-NFL-Rookie-0" target="_blank" >Mike Strachan</a></li>
                    <li><a href="/player/view/27427?KadariusToney-NFL-FA-0" target="_blank" >Kadarius Toney</a></li>
                    <li><a href="/player/view/27494?SimiFehoko-NFL-Rookie-0" target="_blank" >Simi Fehoko</a></li>
                    <li><a href="/player/view/27423?ShiSmith-NFL-FA-0" target="_blank" >Shi Smith</a></li>
                    <li><a href="/player/view/27433?AmariRodgers-NFL-FA-0" target="_blank" >Amari Rodgers</a></li>
                    <li><a href="/player/view/27449?TylanWallace-NFL-FA-0" target="_blank" >Tylan Wallace</a></li>
                    <li><a href="/player/view/27399?TamorrionTerry-NFL-FA-0" target="_blank" >Tamorrion Terry</a></li>
                    <li><a href="/player/view/27462?AnthonySchwartz-NFL-FA-0" target="_blank" >Anthony Schwartz</a></li>
                    <li><a href="/player/view/27487?JalenCamp-NFL-Rookie-0" target="_blank" >Jalen Camp</a></li>
                    <li><a href="/player/view/27482?JaelonDarden-NFL-Rookie-0" target="_blank" >Jaelon Darden</a></li>
                    <li><a href="/player/view/27467?SethWilliams-NFL-FA-0" target="_blank" >Seth Williams</a></li>
                    <li><a href="/player/view/27479?TutuAtwell-NFL-FA-0" target="_blank" >Tutu Atwell</a></li>
                    <li><a href="/player/view/27456?DWayneEskridge-NFL-FA-0" target="_blank" >Dwayne Eskridge</a></li>
                    <li><a href="/player/view/27430?MarquezStevenson-NFL-FA-0" target="_blank" >Marquez Stevenson</a></li>
                    <li><a href="/player/view/27495?ConnorWedington-NFL-Rookie-0" target="_blank" >Connor Wedington</a></li>
                    <li><a href="/player/view/27509?TrevonGrimes-NFL-Rookie-0" target="_blank" >Trevon Grimes</a></li>
                    <li><a href="/player/view/27471?TylerVaughns-NFL-FA-0" target="_blank" >Tyler Vaughns</a></li>
                    <li><a href="/player/view/27401?CornellPowell-NFL-FA-0" target="_blank" >Cornell Powell</a></li>
                    <li><a href="/player/view/27490?Josh%20Imatorbhebhe-NFL-Rookie-0" target="_blank" >Josh Imatorbhebhe</a></li>
                    <li><a href="/player/view/27448?SageSurratt-NFL-FA-0" target="_blank" >Sage Surratt</a></li>
                    <li><a href="/player/view/27400?BrennanEagles-NFL-FA-0" target="_blank" >Breenan Eagles</a></li>
                    <li><a href="/player/view/27510?JacobHarris-NFL-Rookie-0" target="_blank" >Jacob Harris</a></li>
                    <li><a href="/player/view/27518?KawaanBaker-NFL-Rookie-0" target="_blank" >Kawaan Baker</a></li>
                    <li><a href="/player/view/27550?DillonStoner-NFL-Rookie-0" target="_blank" >Dillon Stoner</a></li>
                    <li><a href="/player/view/27398?IhmirSmithMarsette-NFL-FA-0" target="_blank" >Imir Smith-Marsette</a></li>
                    <li><a href="/player/view/27481?JonathanAdams%20Jr.-NFL-Rookie-0" target="_blank" >Jonathan Adams Jr.</a></li>
                    <li><a href="/player/view/27424?WarrenJackson-NFL-FA-0" target="_blank" >Warren Jackson</a></li>
                    <li><a href="/player/view/27501?CadeJohnson-NFL-Rookie-0" target="_blank" >Cade Johnson</a></li>
                    <li><a href="/player/view/27515?RaceyMcMath-NFL-Rookie-0" target="_blank" >Racey McMath</a></li>
                </ol>
            </div>
            <div id="test2" class="col s12">
                <ol>
                    <li><a href="/player/view/27425?TravisEtienne-NFL-FA-0" target="_blank" >Travis Etienne</a></li>
                    <li><a href="/player/view/27463?NajeeHarris-NFL-FA-0" target="_blank" >Najee Harris</a></li>
                    <li><a href="/player/view/27455?JavonteWilliams-NFL-FA-0" target="_blank" >Javonte Williams</a></li>
                    <li><a href="/player/view/27438?MichaelCarter-NFL-FA-0" target="_blank" >Michael Carter</a></li>
                    <li><a href="/player/view/27392?ChubaHubbard-NFL-FA-0" target="_blank" >Chuba Hubbard</a></li>
                    <li><a href="/player/view/27499?ChrisEvans-NFL-Rookie-0" target="_blank" >Chris Evans</a></li>
                    <li><a href="/player/view/26672?TreySermon-NFL-FA-0" target="_blank" >Trey Sermon</a></li>
                    <li><a href="/player/view/27396?KhalilHerbert-NFL-FA-0" target="_blank" >Khalil Herbert</a></li>
                    <li><a href="/player/view/27435?KennethGainwell-NFL-FA-0" target="_blank" >Kenneth Gainwell</a></li>
                    <li><a href="/player/view/27450?KylinHill-NFL-FA-0" target="_blank" >Kylin Hill</a></li>
                    <li><a href="/player/view/27394?DeonJackson-NFL-FA-0" target="_blank" >Deon Jackson</a></li>
                    <li><a href="/player/view/27434?RhamondreStevenson-NFL-FA-0" target="_blank" >Rhamondre Stevenson</a></li>
                    <li><a href="/player/view/27436?GerridDoaks-NFL-FA-0" target="_blank" >Gerrid Doaks</a></li>
                    <li><a href="/player/view/27446?JavianHawkins-NFL-FA-0" target="_blank" >Javian Hawkins</a></li>
                    <li><a href="/player/view/27473?JermarJefferson-NFL-FA-0" target="_blank" >Jermar Jefferson</a></li>
                    <li><a href="/player/view/27483?KeneNwangwu-NFL-Rookie-0" target="_blank" >Kene Nwagwu</a></li>
                    <li><a href="/player/view/27485?JakeFunk-NFL-Rookie-0" target="_blank" >Jake Funk</a></li>
                    <li><a href="/player/view/27477?JaretPatterson-NFL-FA-0" target="_blank" >Jaret Patterson</a></li>
                    <li><a href="/player/view/27523?TreyRagas-NFL-Rookie-0" target="_blank" >Trey Ragas</a></li>
                    <li><a href="/player/view/27522?StevieScott-NFL-Rookie-0" target="_blank" >Stevie Scott</a></li>
                </ol>
            </div>
            <div id="test4" class="col s12">
                <ol>
                    <li><a href="/player/view/27395?KylePitts-NFL-FA-0" target="_blank" >Kyle Pitts</a></li>
                    <li><a href="/player/view/27420?PatFreiermuth-NFL-FA-0" target="_blank" >Pat Freiermuth</a></li>
                    <li><a href="/player/view/27511?NoahGray-NFL-Rookie-0" target="_blank" >Noah Gray</a></li>
                    <li><a href="/player/view/27464?HunterLong-NFL-FA-0" target="_blank" >Hunter Long</a></li>
                    <li><a href="/player/view/27454?BrevinJordan-NFL-FA-0" target="_blank" >Brevin Jordan</a></li>
                    <li><a href="/player/view/27504?BrockWright-NFL-Rookie-0" target="_blank" >Brock Wright</a></li>
                    <li><a href="/player/view/27573?QuintinMorris-NFL-Rookie-0" target="_blank" >Quintin Morris</a></li>
                    <li><a href="/player/view/27513?BrileyMoore-NFL-Rookie-0" target="_blank" >Briley Moore</a></li>
                    <li><a href="/player/view/27426?TreMcKitty-NFL-FA-0" target="_blank" >Tre Mckitty</a></li>
                    <li><a href="/player/view/27461?KennyYeboah-NFL-FA-0" target="_blank" >Kenny Yeboah</a></li>
                    <li><a href="/player/view/27576?TommyTremble-NFL-Rookie-0" target="_blank" >Tommy Tremble</a></li>
                </ol>
            </div>
        </div>
    </div>
</div>