<?php

$json = json_encode($this->jsVars);

$page = <<<EOT
    <div class="row player-header my-2">
        <div class="col-sm-7 player-info">
            <div class="well player-image">
               <img width="350px" style="height:250px" src="{$player['image1']}"/>
            </div>
            <div class="player-info">
                <span class="first-name">{$player['firstName']}</span>
                <span class="last-name">{$player['lastName']}</span>
                <span class="player-info-line">#18 Los Angeles Rams</span>
                <br>
                <span class="player-info-line">{$player['height']}</span>
                <br>
                <span class="player-info-line">{$player['weight']} lbs</span>
                <br>
                <span class="player-info-line">Age: {$player['age']}</span>
                <br>
                <span class="player-info-line">{$player['college']}</span>
                <br>
                <span class="player-info-line">Draft Pick: {$player['draftPick']}</span>
            </div>
        </div>
        <div class="col-sm-3 player-scores">
            <div id="measurables" ></div>
        </div>
    </div>
    
        <div class="container my-5">
    
        <div class="row">
            <div class="col-sm-4 player-info-graph">
                <p class="text-center">Current Role : {$player['role']}</p>
                <div id="fit" style="width: 200px;margin: auto; height:150px"></div>
            </div>
            <div class="col-sm-4 player-info-graph">
                <p class="text-center"> Team Role Opportunity: {$player['role']}</p>
                <div id="fit2" style="width: 200px;margin: auto; height:150px"></div>
            </div>
            <div class="col-sm-4 player-info-graph">
                <p class="text-center"> Team Supporting Efficiency: {$player['role']}</p>
                <div id="fit3" style="width: 200px;margin: auto; height:150px"></div>
            </div>
        </div>

    <div class="container my-5">

        <h5 class="text-center">Athletic Breakdown</h5>
        <div class="row player-athlete">
            <div class="col-sm-8">
                <div class="prospect-graph" id="prospect"></div>
            </div>
            <div class="col-sm-4">
                <div class="row my-2">
                    <div class="profile-score col-sm-2">
                        <div style="margin-top:10px">Slot Score:</div>
                    </div>
                    <div class="col-sm-8" id="slot-score"></div>
                </div>
                <div class="row my-2">
                    <div class="profile-score col-sm-2">
                        <div style="margin-top:10px">Deep Score:</div>
                    </div>
                    <div class="col-sm-8" id="deep-score"></div>
                </div>
                <div class="row my-2">
                    <div class="profile-score col-sm-2">
                        <div style="margin-top:10px">Alpha Score:</div>
                    </div>
                    <div class="col-sm-8" id="alpha-score"></div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-sm-12 player-body my-5">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Situation Breakdown</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="messages-tab" data-toggle="tab" href="#messages" role="tab" aria-controls="messages" aria-selected="false">NFL Performance</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="settings-tab" data-toggle="tab" href="#settings" role="tab" aria-controls="settings" aria-selected="false">Matchup Breakdown</a>
            </li>
        </ul>

        <div class="tab-content my-2">
            <div class="tab-pane active" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                <div class="col-sm-12 player-college">
                    <h5 class="text-center">College Breakdown</h5>
                    <div class="col-sm-7">
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">Year</th>
                                <th scope="col">School</th>
                                <th scope="col">Conf</th>
                                <th scope="col">Class</th>
                                <th scope="col">Rush Atts</th>
                                <th scope="col">Rush Yds</th>
                                <th scope="col">YPC</th>
                                <th scope="col">Rush Tds</th>
                                <th scope="col">Rec</th>
                                <th scope="col">Rec Yds</th>
                                <th scope="col">YPR</th>
                                <th scope="col">Rec Tds</th>
                                <th scope="col">Age</th>
                                <th scope="col">Dominator</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <th scope="row">2015</th>
                                <td>Penn St.</td>
                                <td>Big Ten</td>
                                <td>FR</td>
                                <td>182</td>
                                <td>1076</td>
                                <td>5.9</td>
                                <td>7</td>
                                <td>20</td>
                                <td>161</td>
                                <td>8.1</td>
                                <td>1</td>
                                <td>18</td>
                                <td>25%</td>
                            </tr>
                            <tr>
                                <th scope="row">2016</th>
                                <td>Penn St.</td>
                                <td>Big Ten</td>
                                <td>FR</td>
                                <td>182</td>
                                <td>1076</td>
                                <td>5.9</td>
                                <td>7</td>
                                <td>20</td>
                                <td>161</td>
                                <td>8.1</td>
                                <td>1</td>
                                <td>18</td>
                                <td>25%</td>
                            </tr>
                            <tr>
                                <th scope="row">2017</th>
                                <td>Penn St.</td>
                                <td>Big Ten</td>
                                <td>FR</td>
                                <td>182</td>
                                <td>1076</td>
                                <td>5.9</td>
                                <td>7</td>
                                <td>20</td>
                                <td>161</td>
                                <td>8.1</td>
                                <td>1</td>
                                <td>18</td>
                                <td>25%</td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="messages" role="tabpanel" aria-labelledby="messages-tab">
                <table id="myTable" class="cell-border compact stripe">
                    <thead>
                    <thead>






                    <tr class="LAcolors player-table-header">
                        <td colspan="4">Regular Season</td>

                        <td colspan="2">Games</td>

                        <td colspan="5">Receiving</td>

                        <td colspan="5">Rushing</td>

                        <td colspan="2">Fumbles</td>

                    </tr>
                    <tr class="player-table-key">
                        <td class="first-td">WK</td>
                        <td>Game Date</td>
                        <td>Opp</td>
                        <td>Result</td>


                        <td>G</td>

                        <td>GS</td>

                        <td>Rec</td>

                        <td>Yds</td>

                        <td>Avg</td>

                        <td>Lng</td>

                        <td>TD</td>

                        <td>Att</td>

                        <td>Yds</td>

                        <td>Avg</td>

                        <td>Lng</td>

                        <td>TD</td>

                        <td>FUM</td>

                        <td class="last-td">Lost</td>

                    </tr>
                    </thead>
                    <tbody>
                    ...
                    </tbody>
                </table>
            </div>
            <div class="tab-pane" id="settings" role="tabpanel" aria-labelledby="settings-tab">
                Matchup
            </div>
        </div> 
<script type="text/javascript">
    var rlfData = {$json};
    
    $(document).ready(function() {
       rlf.initRbPage(); 
       rlf.initSearch();
    });
</script>
EOT;

echo $page;