<div class="section light full-height">
    <div class="row">
        <div class="col s12 m10 offset-m1 center">
            <h1 class="fade-in-out">Search Players</h1>
            <div id="custom-templates" class="container my-2">
                <input class="typeahead" type="text" placeholder="Type In A Player's Name">
            </div>
        </div>
    </div>
</div>
<div class="section dark full-height">
    <div class="row">
        <div class="col s12 m10 offset-m1 center">
            <h1 class="fade-in-out">Compare Players</h1>
        </div>
    </div>
    <div class="row center">
        <div class="col s4">
            <div class="input-field col s12 compare-search-field">
                <input type="text" class="typeahead right compare-search" id="compare-1" class="autocomplete" placeholder="Search for Players">
            </div>
        </div>
        <div class="col s4">
            <button class="btn-large waves-effect waves-light" id="compare-button">Compare Players
                <i class="material-icons right">send</i>
            </button>
        </div>
        <div class="col s4">
            <div class="input-field col s12 compare-search-field">
                <input type="text" class="typeahead right compare-search" id="compare-2" class="autocomplete" placeholder="Search for Players">
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    var rlfData = <?=json_encode($jsVars, 512)?>;

    $(document).ready(function() {
        rlf.initSearch();
        rlf.initCompareSearches();
    });
</script>