
<div class="section white full-height container">
    <div id="search-players" class="container player-search my-2 m6">
        <input class="typeahead" type="text" placeholder="Search for Players">
    </div>
    <div class="header">
        <div class="col s12 m6 container header-wrapper header">
            <h1 class="text-right brand-logo" style="color:#1de9c3; font-size:30px"><?= $player['first_name']." ".$player['last_name'] ?></h1>
        </div>
    </div>

    <div class="row player-header scrollspy container" id="player-header">
        <div class="col m5 s12 profile">
            <div class="card small player-card hoverable">
                <div class="card-image waves-effect waves-block waves-light">
                    <div class="carousel carousel-slider activator">
                        <?=$player['images']?>
                    </div>
                </div>
                <div class="card-content player-card-content center">
                    <a class="btn-floating right halfway-fab waves-effect waves-dark activator"><i class="material-icons teal-text">arrow_upward</i></a>
                    <span class="player-title activator row-title text-darken-4"><?= $player['first_name']." ".$player['last_name'] ?></span>
                    <p class="player-title activator text-darken-4" style="color:#1de9c3">#<?=$player['team_info']['number'] ?> <?=$player['position']?> <?= $player['team']?></p>
                </div>
                <div class="card-reveal player-card-reveal">
                    <span class="card-title white-text">Player Info<i class="material-icons right">arrow_downward</i></span>
                    <p>Height: <?= $player['player_info']['height']?> (<?= $player['ordinals']['heightInches'] ?> percentile)</p>
                    <p>Weight: <?= $player['player_info']['weight']?> lbs (<?= $player['ordinals']['weight'] ?> percentile)</p>
                    <p>Arms: <?= $player['player_info']['arms']?> inches (<?= $player['ordinals']['arms'] ?> percentile)</p>
                    <p>BMI: <?= $player['player_info']['bmi']?> (<?= $player['ordinals']['bmi'] ?> percentile)</p>
                    <p>College: <?= $player['player_info']['college']?></p>
                    <p>Draft Pick: <?= $player['player_info']['draft_pick']?> | Draft Year: <?= $player['player_info']['draft_year']?> </p>
                </div>
            </div>
        </div>
        <div class="col m5 s12 measurables">
            <div class="card player-card small hoverable">
                <div class="card-image waves-effect waves-block waves-light">
                    <div id="radar-graph" style="width:400px; height:400px; margin:auto" class="scale-transition scale-out active">

                    </div>
                </div>
                <div class="card-content player-card-content center">
                    <a class="btn-floating right halfway-fab waves-effect waves-light activator"><i class="material-icons teal-text">arrow_upward</i></a>
                    <span class="player-title activator white-text text-darken-4">Measurables</span>
                </div>
                <div class="card-reveal player-card-reveal">
                    <span class="card-title white-text">Workout Metrics<i class="material-icons right">arrow_downward</i></span>
                    <p>40 yd dash: <?= (!empty($player['metrics']['fortyTime'])) ? $player['metrics']['fortyTime']." seconds (".$player['ordinals']['fortyTime']." percentile)" : "Not Available"?></p>
                    <p>Bench Press: <?= (!empty($player['metrics']['benchPress'])) ? $player['metrics']['benchPress']." reps (".$player['ordinals']['benchPress']." percentile)" : "Not Available"?></p>
                    <p>3 cone: <?= (!empty($player['metrics']['cone'])) ? $player['metrics']['cone']." seconds (".$player['ordinals']['cone']." percentile)" : "Not Available" ?></p>
                    <p>Shuttle: <?= (!empty($player['metrics']['shuttle'])) ? $player['metrics']['shuttle']." seconds (".$player['ordinals']['shuttle']." percentile)" : "Not Available" ?></p>
                    <p>Vertical Jump: <?= (!empty($player['metrics']['verticalJump'])) ? $player['metrics']['verticalJump']." inches (".$player['ordinals']['verticalJump']." percentile)" : "Not Available" ?></p>
                    <p>Broad Jump: <?= (!empty($player['metrics']['broadJump'])) ? $player['metrics']['broadJump']." inches (".$player['ordinals']['broadJump']." percentile)" : "Not Available"?></p>
                </div>
            </div>
        </div>
        <?php
            if (array_key_exists("pts_ppr_avg", $player['seasonStats']['2018']['ranks']) && $player['seasonStats']['2018']['ranks']['pts_ppr_avg'] != "") {
                $rank = $player['position'].$player['seasonStats']['2018']['ranks']['pts_ppr_avg'];
                $ppg =  $player['seasonStats']['2018']['stats']['pts_ppr_avg'];
            } else {
                $rank = "N/A";
                $ppg =  "N/A";
            }

        ?>
        <div class="col m2 s12 measurables">
            <div class="card player-card small hoverable center">
                <h5>2018 PPG Rank</h5>
                <div class="btn-floating btn-large purple bold"><span style="font-size:16px; font-weight:bold"><?= $rank ?></span></div>
                <h5>2018 PPR PPG</h5>
                <div class="btn-floating btn-large purple bold"><span style="font-size:16px; font-weight:bold"><?= $ppg ?></span></div>
            </div>
        </div>
    </div>
    <div class="row player-prospect container scrollspy" id="player-prospect">
        <a class="waves-effect waves-light btn-small right center modal-trigger" href="#modal2">Explain<i class="material-icons">live_help</i></a>
        <div class="col s12 center row-title"><h6>Draft Prospect Breakdown</h6></div>
        <div class="col m9 s12 prospect hoverable z-depth-2 hoverable" style="background:white; position: relative; height:450px;">
            <canvas id="canvas" width="75%"></canvas>
        </div>
        <div class="col m3 s12 skillset hoverable z-depth-2 hoverable" style="background:white; position: relative; height:450px;">
            <div class="slot-box center">
                <div style="margin-top:10px" class="role-one-title"></div>
                <div class="role-one-score"></div>
                <div class="progress role-one-bar">
                    <div class="determinate" style="width: 0%"></div>
                </div>
                <div class="role-one-percentile"></div>
            </div>
            <div class="deep-box center">
                <div style="margin-top:10px" class="role-two-title"></div>
                <div class="role-two-score"></div>
                <div class="progress role-two-bar">
                    <div class="determinate" style="width: 0%"></div>
                </div>
                <div class="role-two-percentile"></div>
            </div>
            <div class="alpha-box center">
                <div style="margin-top:10px" class="role-three-title"></div>
                <div class="role-three-score"></div>
                <div class="progress role-three-bar">
                    <div class="determinate" style="width: 0%"></div>
                </div>
                <div class="role-three-percentile"></div>
            </div>
        </div>
    </div>

    <div class="row player-situation container scrollspy" id="player-situation" style="display:none">
        <a class="waves-effect waves-light btn-small right center modal-trigger" href="#modal1">Explain<i class="material-icons">live_help</i></a>
        <div class="col s12 center row-title"><h6>Situation Breakdown</h6></div>
        <div class="col m4 s12 fit z-depth-1 hoverable">
            <div id="fit-graph"></div>
        </div>
        <div class="col m4 s12 volume z-depth-1 hoverable">
            <div id="volume-graph"></div>
        </div>
        <div class="col m4 s12 support z-depth-1 hoverable">
            <div id="support-graph"></div>
        </div>
    </div>
    <div class="row player-stats container scrollspy hoverable z-depth-2 hoverable" id="player-stats" style="background:white">
        <div class="col s12 center row-title"><h6>Stats</h6></div>
        <div class="col s12">
            <ul class="tabs">
                <li class="tab col s3"><a class="active purple-text" href="#test1">NFL Stats</a></li>
                <li class="tab col s3"><a class="purple-text" href="#test2">NFL Game Logs</a></li>
                <li class="tab col s3"><a class="purple-text" href="#test3">College Stats</a></li>
            </ul>
        </div>
        <div id="test1" class="col s12">
            <div class="col-sm-12">
                <table id="season-stats" class="display" width="100%">
                    <tfoot>
                    <tr>
                        <th colspan="2">Career Average:<br>Career Total:</th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        <div id="test2" class="col s12">
            <div class="col-sm-12">
                <table id="game-logs" class="display" width="100%">
                    <tfoot>
                    <tr>
                        <th colspan="2">Average:<br>Total:</th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        <div id="test3" class="col s12">
            <div class="col s12 black-text" >
                <div class="col m4 offset-m2">
                    <div style="width:350px">
                        <canvas id="college-doughnut" width="170"></canvas>
                        <div class="donut-inner center-align">
                            <h5></h5>
                            <span></span>
                        </div>
                    </div>
                </div>
                <div class="col m4">
                    <div class="college-row-one">
                        <p class="black-text"></p>
                    </div>
                    <div class="college-row-two">
                        <p class="black-text"></p>
                    </div>
                    <div class="college-row-three">
                        <p class="black-text"></p>
                    </div>
                    <div class="college-row-four">
                        <p class="black-text"></p>
                    </div>
                </div>
            </div>
            <div class="col s12">
                <table id="college-stats" class="display" width="100%">
                    <tfoot>
                    <tr>
                        <th colspan="2">Career Average:<br>Career Total:</th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
    <div class="player-menu">
        <ul class="table-of-contents">
            <li><a href="#player-header">Measurables</a></li>
            <li><a href="#player-prospect">Prospect</a></li>
<!--            <li><a href="#player-situation">Situation</a></li>-->
            <li><a href="#player-stats">Stats</a></li>
<!--            <li><a href="#player-takes">Taeks</a></li>-->
        </ul>
    </div>
</div>
<?php
switch($player['position']) {
    case "QB":
        $init = "rlf.initQbPage();";
        break;
    case "WR":
        $init = "rlf.initWrPage();";
        break;
    case "RB":
        $init = "rlf.initRbPage();";
        break;
    case "TE":
        $init = "rlf.initTePage();";
        break;
    case "OT":
    case "C":
    case "G":
        $init = "rlf.initOlPage();";
        break;
    case "NT":
    case "DT":
    case "DE":
        $init = "rlf.initDlPage();";
        break;
    case "OLB":
        $init = "rlf.initOlbPage();";
        break;
    case "ILB":
        $init = "rlf.initIlbPage();";
        break;
    default:
        $init = "rlf.initWrPage();";
}
?>

<script type="text/javascript">
    var rlfData = <?=json_encode($jsVars, 512)?>;

    $(document).ready(function() {
        <?= $init ?>
        rlf.initSearch();
        rlf.initCompareSearches();
    });
</script>

