<?php

$json = json_encode($this->jsVars);

$page = <<<EOT
    <div class="row player-header my-2">
        <div class="col-sm-5 player-info">
            <div class="well player-image">
                <img width="250px" style="height:250px" src="https://media.giphy.com/media/5wFuyUCJ1Px98OEN55/giphy.gif"/>
            </div>
            <div class="player-info">
                <span class="first-name">{$player['firstName']}</span>
                <span class="last-name">{$player['lastName']}</span>
                <span class="player-info-line">{$player['team']}</span>
                <br>
                <span class="player-info-line">{$player['height']}</span>
                <br>
                <span class="player-info-line">{$player['weight']} lbs</span>
                <br>
                <span class="player-info-line">Age: {$player['age']}</span>
                <br>
                <span class="player-info-line">{$player['college']}</span>
                <br>
                <span class="player-info-line">Draft Pick: {$player['draftPick']}</span>
            </div>
            <div>
                <span> Sleeper Redraft ADP: 1.01 | </span>
                <span> Sleeper Dynasty ADP: 1.01</span>
                <br>
                <span> Draft.com BestBall ADP: 1.02</span>
            </div>

        </div>
        <div class="col-sm-3 player-info-graph">
            <p class="text-center">Current Team Role: {$player['role']}</p>
            <div id="fit" style="width: 200px;margin: auto; height:150px"></div>
            <div id="fit2" style="width: 200px;margin: auto;  height:150px"></div>
        </div>
        <div class="col-sm-3 player-scores">
            <div id="measurables" ></div>
        </div>
    </div>

    <div class="container my-5">

        <h5 class="text-center">Athletic Breakdown</h5>
        <div class="row player-athlete">
            <div class="col-sm-8">
                <div class="prospect-graph" id="prospect"></div>
            </div>
            <div class="col-sm-4">
                <div class="row my-2 col-sm-12">
                    <div class="profile-score col-sm-12">
                        <div style="margin-top:10px">Slot Score:</div>
                        <div class="progress">
                            <div class="progress-bar slot-bar" role="progressbar" style="width: 1%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>

                </div>
                <div class="row my-2 col-sm-12">
                    <div class="profile-score col-sm-12">
                        <div style="margin-top:10px">Deep Score:</div>
                        <div class="progress">
                            <div class="progress-bar deep-bar" role="progressbar" style="width: 1%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                </div>
                <div class="row my-2 col-sm-12">
                    <div class="profile-score col-sm-12">
                        <div style="margin-top:10px">Alpha Score:</div>
                        <div class="progress">
                            <div class="progress-bar alpha-bar" role="progressbar" style="width: 1%" aria-valuenow="1" aria-valuemin="0" aria-valuemax="100"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-sm-12 player-body my-5">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link active" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Situation Breakdown</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="messages-tab" data-toggle="tab" href="#messages" role="tab" aria-controls="messages" aria-selected="false">NFL Performance</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" id="settings-tab" data-toggle="tab" href="#settings" role="tab" aria-controls="settings" aria-selected="false">Matchup Breakdown</a>
            </li>
        </ul>

        <div class="tab-content my-2">
            <div class="tab-pane active" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                <div class="col-sm-12 player-college">
                    <h5 class="text-center">College Breakdown</h5>
                    <div class="col-sm-12">
                        <table id="college-stats" class="display" width="100%"></table>
                    </div>
                </div>
            </div>
            <div class="tab-pane" id="messages" role="tabpanel" aria-labelledby="messages-tab">
                <table id="myTable" class="cell-border compact stripe">
                    <thead>
                    <thead>






                    <tr class="LAcolors player-table-header">
                        <td colspan="4">Regular Season</td>

                        <td colspan="2">Games</td>

                        <td colspan="5">Receiving</td>

                        <td colspan="5">Rushing</td>

                        <td colspan="2">Fumbles</td>

                    </tr>
                    <tr class="player-table-key">
                        <td class="first-td">WK</td>
                        <td>Game Date</td>
                        <td>Opp</td>
                        <td>Result</td>


                        <td>G</td>

                        <td>GS</td>

                        <td>Rec</td>

                        <td>Yds</td>

                        <td>Avg</td>

                        <td>Lng</td>

                        <td>TD</td>

                        <td>Att</td>

                        <td>Yds</td>

                        <td>Avg</td>

                        <td>Lng</td>

                        <td>TD</td>

                        <td>FUM</td>

                        <td class="last-td">Lost</td>

                    </tr>
                    </thead>
                    <tbody>
                    ...
                    </tbody>
                </table>
            </div>
            <div class="tab-pane" id="settings" role="tabpanel" aria-labelledby="settings-tab">
                Matchup
            </div>
        </div> 
<script type="text/javascript">
    var rlfData = {$json};
    
    $(document).ready(function() {
       rlf.initWrPage(); 
       rlf.initSearch();
    });
</script>

EOT;

echo $page;


