
<div class="section container page-container player-container">
    <div class="row player-header section scrollspy" id="player-header">
        <div class="col m6 s12 profile">
            <div class="card small player-card hoverable">
                <div class="card-image waves-effect waves-block waves-light">
                    <div class="carousel carousel-slider activator">
                        <a class="carousel-item" href="#one!"><img  src="https://sleepercdn.com/content/nfl/players/<?=$player['sleeper_id']?>.jpg" style="height:280px"></a>
                        <a class="carousel-item" href="#two!"><img src="" style="height:280px"></a>
                        <a class="carousel-item" href="#three!"><img src="" style="height:280px"></a>
                    </div>
                </div>
                <div class="card-content player-card-content center">
                    <a class="btn-floating right halfway-fab waves-effect waves-light red activator"><i class="material-icons">arrow_upward</i></a>
                    <span class="player-title activator white-text text-darken-4"><?= $player['first_name']." ".$player['last_name'] ?></span>
                    <p class="player-title activator yellow-text text-darken-4">#<?=$player['team_info']['number'] ?> <?=$player['position']?> <?= $player['team']?></p>
                </div>
                <div class="card-reveal player-card-reveal">
                    <span class="card-title white-text">Player Info<i class="material-icons right">arrow_downward</i></span>
                    <p>Height: <?= $player['player_info']['height']?> (<?= $player['ordinals']['heightInches'] ?> percentile)</p>
                    <p>Weight: <?= $player['player_info']['weight']?> lbs (<?= $player['ordinals']['weight'] ?> percentile)</p>
                    <p>Arms: <?= $player['player_info']['arms']?> inches (<?= $player['ordinals']['arms'] ?> percentile)</p>
                    <p>BMI: <?= $player['player_info']['bmi']?> (<?= $player['ordinals']['bmi'] ?> percentile)</p>
                    <p>College: <?= $player['player_info']['college']?></p>
                    <p>Draft Pick: <?= $player['player_info']['draft_pick']?> | Draft Year: <?= $player['player_info']['draft_year']?> </p>
                </div>
            </div>
        </div>
        <div class="col m6 s12 measurables">
            <div class="card player-card small hoverable">
                <div class="card-image waves-effect waves-block waves-light">
                    <div id="radar-graph" style="width:400px; height:400px; margin:auto" class="scale-transition scale-out">

                    </div>
                </div>
                <div class="card-content player-card-content center">
                    <a class="btn-floating right halfway-fab waves-effect waves-light red activator"><i class="material-icons">arrow_upward</i></a>
                    <span class="player-title activator white-text text-darken-4">Measurables</span>
                </div>
                <div class="card-reveal player-card-reveal">
                    <span class="card-title white-text">Workout Metrics<i class="material-icons right">arrow_downward</i></span>
                    <p>40 yd dash: <?= (!empty($player['metrics']['fortyTime'])) ? $player['metrics']['fortyTime']." seconds (".$player['ordinals']['fortyTime']." percentile)" : "Not Available"?></p>
                    <p>Bench Press: <?= (!empty($player['metrics']['benchPress'])) ? $player['metrics']['benchPress']." reps (".$player['ordinals']['benchPress']." percentile)" : "Not Available"?></p>
                    <p>3 cone: <?= (!empty($player['metrics']['cone'])) ? $player['metrics']['cone']." seconds (".$player['ordinals']['cone']." percentile)" : "Not Available" ?></p>
                    <p>Shuttle: <?= (!empty($player['metrics']['shuttle'])) ? $player['metrics']['shuttle']." seconds (".$player['ordinals']['shuttle']." percentile)" : "Not Available" ?></p>
                    <p>Vertical Jump: <?= (!empty($player['metrics']['verticalJump'])) ? $player['metrics']['verticalJump']." inches (".$player['ordinals']['verticalJump']." percentile)" : "Not Available" ?></p>
                    <p>Broad Jump: <?= (!empty($player['metrics']['broadJump'])) ? $player['metrics']['broadJump']." inches (".$player['ordinals']['broadJump']." percentile)" : "Not Available"?></p>
                </div>
            </div>
        </div>
    </div>
    <div class="row player-prospect section scrollspy" id="player-prospect">
        <a class="waves-effect waves-light btn-small right center modal-trigger" href="#modal2">Explain<i class="material-icons">live_help</i></a>
        <div class="col s12 center row-title"><h6>Prospect Breakdown</h6></div>
        <div class="col m9 s12 prospect z-depth-1 hoverable">
            <div id="prospect-graph" style="margin:auto"></div>
        </div>
        <div class="col m3 s12 skillset z-depth-1 hoverable">
            <div class="slot-box center">
                <div style="margin-top:10px" class="role-one-title"></div>
                <div class="role-one-score"></div>
                    <div class="progress role-one-bar">
                        <div class="determinate" style="width: 0%"></div>
                    </div>
            </div>
            <div class="deep-box center">
                <div style="margin-top:10px" class="role-two-title"></div>
                <div class="role-two-score"></div>
                <div class="progress role-two-bar">
                    <div class="determinate" style="width: 0%"></div>
                </div>
            </div>
            <div class="alpha-box center">
                <div style="margin-top:10px" class="role-three-title"></div>
                <div class="role-three-score"></div>
                <div class="progress role-three-bar">
                    <div class="determinate" style="width: 0%"></div>
                </div>
            </div>
        </div>
    </div>
    <div class="row player-situation section scrollspy" id="player-situation">
        <a class="waves-effect waves-light btn-small right center modal-trigger" href="#modal1">Explain<i class="material-icons">live_help</i></a>
        <div class="col s12 center row-title"><h6>Situation Breakdown</h6></div>
        <div class="col m4 s12 fit z-depth-1 hoverable">
            <div id="fit-graph"></div>
        </div>
        <div class="col m4 s12 volume z-depth-1 hoverable">
            <div id="volume-graph"></div>
        </div>
        <div class="col m4 s12 support z-depth-1 hoverable">
            <div id="support-graph"></div>
        </div>
    </div>
</div>
<div class="parallax-container">
    <div class="parallax"><img src="https://pbs.twimg.com/profile_banners/733170759829327874/1527727987/1500x500"></div>
</div>
<div class="section container page-container player-container">
    <div class="row player-stats section scrollspy hoverable" id="player-stats">
        <div class="col s12 center row-title"><h6>Stats</h6></div>
        <div class="col s12">
            <ul class="tabs">
                <li class="tab col s3"><a href="#test1">NFL Stats</a></li>
                <li class="tab col s3"><a class="active" href="#test2">College Stats</a></li>
            </ul>
        </div>
        <div id="test1" class="col s12">NFL Stats</div>
        <div id="test2" class="col s12">
            <div class="col-sm-12">
                <table id="college-stats" class="display" width="100%"></table>
            </div>
        </div>
    </div>
    <div class="row player-takes section scrollspy hoverable" id="player-takes">
        <div class="col s12 center row-title"><h6>Taeks</h6></div>
        <div class="col s12">
            <ul class="tabs">
                <li class="tab col s3"><a class="active" href="#article">Articles</a></li>
                <li class="tab col s3"><a href="#audio">Audio</a></li>
                <li class="tab col s3"><a href="#video">Video</a></li>
            </ul>
        </div>
        <div id="article" class="col s12">Articles</div>
        <div id="audio" class="col s12">Audio</div>
        <div id="video" class="col s12">Video</div>
    </div>
</div>
<div class="player-menu">
    <ul class="section table-of-contents">
        <li><a href="#player-header">Measurables</a></li>
        <li><a href="#player-prospect">Prospect</a></li>
        <li><a href="#player-situation">Situation</a></li>
        <li><a href="#player-stats">Stats</a></li>
        <li><a href="#player-takes">Taeks</a></li>
    </ul>
</div>

<?php
    switch($player['position']) {
        case "WR":
            $init = "rlf.initWrPage();";
            break;
        case "RB":
            $init = "rlf.initRbPage();";
            break;
        case "TE":
            $init = "rlf.initTePage();";
            break;
        default:
    }
?>

<script type="text/javascript">
    var rlfData = <?=json_encode($jsVars, 512)?>;

    $(document).ready(function() {
        <?= $init ?>
        rlf.initSearch();
    });
</script>

