<?php
/**
 * Created by IntelliJ IDEA.
 * User: tcook
 * Date: 8/6/19
 * Time: 3:06 PM
 */

namespace Player\Service\Position;

use Player\Model\Player\PlayerCommandInterface;
use Player\Model\Player\PlayerRepositoryInterface;
use Zend\Db\Adapter\AdapterInterface;
use Zend\ProgressBar\Adapter\Console;
use Zend\ProgressBar\ProgressBar;
use Zend\Db\Sql\Select;
use Zend\Http\Request;
use Zend\Http\Client;
use Zend\Dom\Query;

class RbService extends ServiceAbstract
{
    private $consoleAdapter;
    private $repository;
    private $command;
    private $db;

    public $specialMetrics = [
        'grinder' => [
            'field' => 'metrics',
            'sort' => 'ASC'
        ],
        'passCatcher' => [
            'field' => 'metrics',
            'sort' => 'ASC'
        ],
        'alpha' => [
            'field' => 'metrics',
            'sort' => 'ASC'
        ],
        'collegeScore' => [
            'field' => 'metrics',
            'sort' => 'ASC'
        ],
        'bestDominator' => [
            'field' => 'metrics',
            'sort' => 'ASC'
        ],
        'bestRecDominator' => [
            'field' => 'metrics',
            'sort' => 'ASC'
        ]
    ];

    public function __construct(
        AdapterInterface $db,
        Console $consoleAdapter,
        PlayerCommandInterface $command,
        PlayerRepositoryInterface $repository)
    {
        parent::__construct($db, $consoleAdapter, $command, $repository);
        $this->repository = $repository;
        $this->command = $command;
        $this->consoleAdapter = $consoleAdapter;
    }


    public function calculateMetrics()
    {
        parent::calculateMetrics("RB"); // TODO: Change the autogenerated stub
    }

    public function calculatePercentiles()
    {
        parent::calculatePercentiles("RB", $this->percentileMetrics); // TODO: Change the autogenerated stub
    }

    public function calculateSpecialPercentiles()
    {
        parent::calculatePercentiles("RB", $this->specialMetrics);
    }

    public function calculateSpecialScores()
    {
        $rbs = $this->repository->findAllPlayers("RB");
        $progressBar = new ProgressBar($this->consoleAdapter, 0, count($rbs));
        $pointer = 0;
        foreach ($rbs as $rb) {
            $rb->decodeJson();
            if (empty($rb->getMetrics())) {
                continue;
            }

            $info = $rb->getPlayerInfo();
            $metrics = $rb->getMetrics();
            $percentiles = $rb->getPercentiles();

            if ($rb->getTeam() == "Rookie") {
                if ($rb->college_stats != null) {
                    $college = $this->makeCollegeScore($rb);
                    $metrics['collegeScore'] = $college['collegeScore'];
                    $metrics['bestSeason'] = $college['bestSeason'];
                    $metrics['breakoutClass'] = $college['breakoutClass'];
                    $metrics['breakoutSeasons'] = $college['breakoutSeasons'];
                    $metrics['collegeSeasons'] = $college['collegeSeasons'];
                    $metrics['bestDominator'] = $college['bestDominator'];
                    $metrics["bestYPC"] = $college['bestYPC'];
                    $metrics["bestCarryDominator"] = $college['bestCarryDominator'];
                    $metrics['bestRecDominator'] = $college['bestRecDominator'];
                } else {
                    $metrics['collegeScore'] = null;
                    $metrics['bestSeason'] = null;
                    $metrics['breakoutClass'] = null;
                    $metrics['breakoutSeasons'] = null;
                    $metrics['collegeSeasons'] = null;
                    $metrics['bestDominator'] = null;
                    $metrics["bestYPC"] = null;
                    $metrics["bestCarryDominator"] = null;
                    $metrics['bestRecDominator'] = null;
                }

                $rb->setMetrics($metrics);

                $this->command->save($rb);

                $pointer++;
                $progressBar->update($pointer);

                continue;
            }

            $data['receiver'] = 0;
            $data['grinder'] = 0;

            /*** Make Grinder Base ***/
            // 1. We have elusiveness, power, and speedScore
            if ($metrics['elusiveness'] !== null && $metrics['power'] !== null && $metrics['speedScore'] !== null) {
                $data['grinder'] = ($percentiles['power'] * .6) + ($percentiles['elusiveness'] * .2) + ($percentiles['speedScore'] * .2);
            }
            // 2. No agility so no elusiveness, just broad jump and speedScore
            if ($metrics['elusiveness'] == null && $metrics['power'] !== null && $metrics['speedScore'] !== null) {
                $data['grinder'] = ($percentiles['power'] * .6) + ($percentiles['speedScore'] * .4);
            }

            // 3. Just speedScore
            if ($metrics['elusiveness'] == null && $metrics['power'] == null && $metrics['speedScore'] !== null) {
                $data['grinder'] = $percentiles['speedScore'];
            }

            // 4. Just broadJump
            if ($metrics['elusiveness'] == null && $metrics['power'] !== null && $metrics['speedScore'] == null) {
                $data['grinder'] = $percentiles['power'];
            }

            /*** Make Receiver Base ***/
            // 1. We have agility scores and forty time
            if ($metrics['shuttle'] !== null && $metrics['cone'] !== null && $metrics['fortyTime'] !== null) {
                $data['receiver'] = ($percentiles['routeAgility'] * .6) + ($percentiles['jukeAgility'] * .2) + ($percentiles['fortyTime'] * .2);
            }
            // 2. No agility scores just forty time
            if ($metrics['shuttle'] == null && $metrics['cone'] == null && $metrics['fortyTime'] !== null) {
                $data['receiver'] = $percentiles['fortyTime'];
            }

            // 3. Agility but no 40 time
            if ($metrics['cone'] == null && $metrics['shuttle'] == null && $metrics['fortyTime'] !== null) {
                $data['receiver'] = ($percentiles['routeAgility'] * .7) + ($percentiles['jukeAgility'] * .3);
            }


            if (!empty($rb->getCollegeStats())) {
                $collegeStuff = $this->makeCollegeScore($rb);
                $metrics['collegeScore'] = $collegeStuff['collegeScore'];
                $metrics['breakoutSeasons'] = $collegeStuff['breakoutSeasons'];
                $metrics['bestDominator'] = $collegeStuff['bestDominator'];
                $metrics['bestRecDominator'] = $collegeStuff['bestRecDominator'];
                $metrics['collegeSeasons'] = $collegeStuff['collegeSeasons'];
                $metrics['breakoutClass'] = $collegeStuff['breakoutClass'];
                $metrics['bestYPC'] = $collegeStuff['bestYPC'];
                $metrics['bestCarryDominator'] = $collegeStuff['bestCarryDominator'];
                $rb->setCollegeStats($collegeStuff['collegeStats']);

                /*** Use College Stats to adjust scores ***/

                $data['receiver'] = ($percentiles['bestRecDominator'] * .6) + ($data['receiver'] * .4);

                if ($collegeStuff['bestYPC'] < 5) {
                    $data['grinder'] = $data['grinder'] - 10;
                }

                if ($collegeStuff['bestCarryDominator'] < 30) {
                    $data['grinder'] = $data['grinder'] - 10;
                }

            } else {
                $metrics['collegeScore'] = null;
                $metrics['breakoutSeasons'] = "N/A";
                $metrics['bestDominator'] = "N/A";
                $metrics['bestRecDominator'] = "N/A";
                $metrics['collegeSeasons'] = "N/A";
                $metrics['bestYPC'] = "N/A";
                $metrics['bestCarryDominator'] = "N/A";
            }

            $data['alpha'] = ($data['receiver'] * .6) + ($data['grinder'] * .4);

            $metrics['alpha'] = round($data['alpha'],2);
            $metrics['passCatcher'] = round($data['receiver'],2);
            $metrics['grinder'] = round($data['grinder'],2);

            $rb->setMetrics($metrics);
            $this->command->save($rb);

            $pointer++;
            $progressBar->update($pointer);
        }
        $progressBar->finish();
    }


    public function makeCollegeScore($rb)
    {
        if ($rb->getId() == 5238) {
            $gotHim = true;
        } else {
            $notHIm = true;
        }

        $i = 0;
        $breakout = false;
        $collegeScore = 0;
        $bestDominator = .01;
        $bestSeason = [];
        $lastYear = "";
        $breakoutClass = "None";
        $bestRecDominator = 0;
        $breakoutSeasons = 0;
        $lastBreakout = 0;
        $bestYPC = 0;
        $bestCarryDom = 0;

        $collegeStats = $rb->getCollegeStats();
        foreach ($collegeStats as $year => $stats) {
            if ($stats->year != "Career") {
                //increment year count
                $i++;

                if ($stats['totals']['yds'] == 0 || !array_key_exists('totals', $stats)) {
                    //we don't have team totals so we can't do calculations
                    return [
                        'collegeScore' => null,
                        'bestSeason' => null,
                        'bestRecDominator' => null,
                        'breakoutClass' => null,
                        'breakoutSeasons' => null,
                        "collegeSeasons" => null,
                        "bestDominator" => null,
                        "bestYPC" => null,
                        "bestCarryDominator" => null,
                        "collegeStats" => $collegeStats,
                    ];
                }

                if (!array_key_exists("scrimmageTds", $stats)) {
                    $stats["scrimmageTds"] = $stats["rushTds"] + $stats['recTds'];
                }

                if (!array_key_exists("scrimmageYds", $stats)) {
                    $stats["scrimmageYds"] = $stats["rushYds"] + $stats['recYds'];
                }

                // determine dominators
                $dominator['td'] = round(($stats['scrimmageTds'] / $stats['totals']['tds']) * 100, 2);
                $dominator['yd'] = round(($stats['scrimmageYds'] / $stats['totals']['yds']) * 100, 2);
                $dominator['rec'] = round(($stats['recs'] / $stats['totals']['recs']) * 100, 2);
                $dominator['carries'] = round(($stats['rushAtt'] / $stats['totals']['carries']) * 100, 2);

                // save dominators to collegestats
                $collegeStats[$year]['dominator'] = round(($dominator['yd'] + $dominator['td'])/2, 2);
                $collegeStats[$year]['tdDominator'] = round($dominator['td'], 2);
                $collegeStats[$year]['recDominator'] = round($dominator['rec'], 2);
                $collegeStats[$year]['ydDominator'] = round($dominator['yd'], 2);
                $collegeStats[$year]['carryDominator'] = round($dominator['carries'], 2);


                $breakout = 0;

                // determine breakout
                foreach ($dominator as $type => $score) {
                    if ($type == 'td') {
                        if ($score !== 0) {
                            switch (true) {
                                case ($score > 10):
                                    $breakout = $breakout + 1;
                                    break;
                                case ($score > 7):
                                    $breakout = $breakout + .5;
                                    break;
                                default:
                            }
                        }
                    }

                    if ($type == 'yd') {
                        if ($score !== 0) {
                            switch (true) {
                                case ($score > 20):
                                    $breakout = $breakout + 1;
                                    break;
                                case ($score > 15):
                                    $breakout = $breakout + .5;
                                    break;
                                default:
                            }
                        }
                    }
                }

                //update dominate season count
                switch ($breakout) {
                    case 2:
                        $breakoutSeasons = $breakoutSeasons + 1;
                        break;
                    case ($breakout >= 1):
                        $breakoutSeasons = $breakoutSeasons + .5;
                        break;
                    default:
                }

                // determine breakout class
                if ($breakout == 2) {
                    if ($breakoutClass == "None") {
                        if ($i == 1) {
                            if ($stats['class'] == "FR") {
                                $breakoutClass = "True Freshman";
                            } else {
                                $breakoutClass = $stats['class'];
                            }
                        } elseif ($i == 2) {
                            if ($stats['class'] == "FR") {
                                $breakoutClass = "Redshirt Freshman";
                            } elseif ($stats['class'] == "SO") {
                                $breakoutClass = "Sophomore";
                            } else {
                                $breakoutClass = $stats['class'];
                            }
                        } elseif ($i == 3) {
                            if ($stats['class'] == "SO") {
                                $breakoutClass = "Redshirt Sophomore";
                            } elseif ($stats['class'] == "JR") {
                                $breakoutClass = "Junior";
                            } else {
                                $breakoutClass = $stats['class'];
                            }
                        } elseif ($i == 4) {
                            if ($stats['class'] == "JR") {
                                $breakoutClass = "Redshirt Junior";
                            } elseif ($stats['class'] == "SR") {
                                $breakoutClass = "Senior";
                            } else {
                                $breakoutClass = $stats['class'];
                            }
                        } elseif ($i == 5) {
                            if ($stats['class'] == "SR") {
                                $breakoutClass = "Redshirt Senior";
                            } elseif ($stats['class'] == "SR") {
                                $breakoutClass = "SR";
                            } else {
                                $breakoutClass = $stats['class'];
                            }
                        } else {
                            $breakoutClass = "SR";
                        }
                    }
                }

                // determine best dominators and save info
                $currentDominator = round((array_sum([$dominator['yd'], $dominator['td']])) / 2, 2);
                if ($currentDominator > $bestDominator) {
                    $bestDominator = $currentDominator;
                }

                if ($dominator['rec'] > $bestRecDominator) {
                    $bestRecDominator = $dominator['rec'];
                }

                if ($stats['rushAvg'] > $bestYPC) {
                    $bestYPC = $stats['rushAvg'];
                }

                if ($dominator['carries'] > $bestCarryDom) {
                    $bestCarryDom = $dominator['carries'];
                }

                if ($breakout == 3) {
                    switch ($currentDominator) {
                        case $currentDominator >= 40 && $stats['rushYds'] > 1000:
                            $collegeScore = $collegeScore + 3;
                            break;
                        case $currentDominator >= 35 && $stats['rushYds'] > 1000:
                            $collegeScore = $collegeScore + 2.75;
                            break;
                        case $currentDominator >= 30:
                            $collegeScore = $collegeScore + 2.50;
                            break;
                        case $currentDominator >= 27.51:
                            $collegeScore = $collegeScore + 2.25;
                            break;
                        case $currentDominator >= 25:
                            $collegeScore = $collegeScore + 2;
                            break;
                        case $currentDominator >= 20:
                            $collegeScore = $collegeScore + 1.75;
                            break;
                        case $currentDominator >= 15:
                            $collegeScore = $collegeScore + 1.50;
                            break;
                        case $currentDominator >= 10:
                            $collegeScore = $collegeScore + 1.25;
                            break;
                        default:
                    }
                }

                // Best Recbreakout score
                switch ($dominator['rec']) {
                    case $dominator['rec'] >= 15:
                        $collegeScore = $collegeScore + 3;
                        break;
                    case $dominator['rec'] >= 12:
                        $collegeScore = $collegeScore + 2;
                        break;
                    case $dominator['rec'] >= 9:
                        $collegeScore = $collegeScore + 1;
                        break;
                    default:
                }

                if ($stats['rushAvg'] > 6 && $stats['rushYds'] > 500) {
                    $collegeScore = $collegeScore + 1;
                }

                $collegeScore = $collegeScore + $breakout;

                //save last breakout
                $lastBreakout = $breakout;
                $lastYear = $stats['class'];

                //save conference
                if (array_key_exists('conference', $stats)) {
                    $conf = $stats['conference'];
                    if ($stats['college'] == "Notre Dame") {
                        $conf = "ACC";
                    }
                } else {
                    $conf = "";
                }
            }
        }

        // Coming out as a junior, add last breakout to simulate senior season
        if (($lastYear == "JR" || $lastYear == "SO") && $i == 3) {
            $collegeScore = $collegeScore + $lastBreakout + 2;
        }

        /**** Bonuses ****/

        // Breakout class
        if ($breakoutClass == "True Freshman") {
            $power5 = ["ACC", "Big Ten", "SEC", "Big 12", "Pac-12"];
            $minor5 = ["MWC", "American", "CUSA", "MAC", "Sun Belt"];
            if (in_array($conf, $power5) ) {
                $collegeScore = $collegeScore + 7;
            } else {
                $collegeScore = $collegeScore + 6;
            }
        } elseif (in_array($breakoutClass, ["Redshirt Freshman", "SO", "Sophomore"])) {
            $collegeScore = $collegeScore + 5;
        } elseif (in_array($breakoutClass, ["JR", "Redshirt Sophomore", "Junior"])) {
            $collegeScore = $collegeScore + 4;
        } elseif (in_array($breakoutClass, ["SR", "Redshirt Junior", "Senior"])) {
            $collegeScore = $collegeScore + 3;
        } elseif ($breakoutClass == "Redshirt Senior") {
            $collegeScore = $collegeScore + 1;
        }

        //Conference bonus/penalty for not Division 1
        $power5 = ["ACC", "Big Ten", "SEC", "Big 12", "Pac-12"];
        $minor5 = ["MWC", "American", "CUSA", "MAC", "Sun Belt"];
        if (in_array($conf, $power5)) {
            $collegeScore = $collegeScore + 4;
        } elseif (in_array($conf, $minor5)) {
            $collegeScore = $collegeScore + 0;
        } else {
            $collegeScore = $collegeScore - 2;
        }


        if ($breakoutClass == "JR") {
            $breakoutClass = "Junior";
        }

        if ($breakoutClass == "SR") {
            $breakoutClass = "Senior";
        }

        return [
            'collegeScore' => $collegeScore,
            'bestSeason' => $bestSeason,
            'bestRecDominator' => $bestRecDominator,
            'breakoutClass' => $breakoutClass,
            'breakoutSeasons' => $breakoutSeasons,
            "collegeSeasons" => $i,
            "bestDominator" => $bestDominator,
            "bestYPC" => $bestYPC,
            "bestCarryDominator" => $bestCarryDom,
            "collegeStats" => $collegeStats
        ];
    }

    public function scrapCollegeJob()
    {
        $rbs = $this->repository->findAllPlayers("RB");
        $progressBar = new ProgressBar($this->consoleAdapter, 0, $rbs->count());
        $pointer = 0;

        foreach ($rbs as $rb) {
            if (true) {
                $rb->decodeJson();
                $result = $this->scrapCollegeStats($rb);
                if ($result == false) {
                    continue;
                }
                $pointer++;
                $progressBar->update($pointer);
            }
        }
        $progressBar->finish();
    }



    public function scrapCollegeStats($rb)
    {
        $request = new Request();
        $apiInfo = $rb->getApiInfo();
        if (!array_key_exists('cfb-alias', $apiInfo) || $apiInfo['cfb-alias'] == null) {
            $firstName = strtolower($rb->getFirstName());
            $lastName = strtolower($rb->getLastName());
            $cfb = "{$firstName}-{$lastName}-1";
        } else {
            $cfb = $apiInfo['cfb-alias'];
        }
        $request->setUri("https://www.sports-reference.com/cfb/players/{$cfb}.html");

        $client = new Client();
        $response = $client->send($request);
        $html = $response->getBody();

        $dom = new Query($html);
        $results = $dom->execute('#rushing tr');

        $count = count($results);
        if ($count == 0) {
            return false;
        }
        $collegeStats = [];
        foreach ($results as $result) {
            $rowChildren = $result->childNodes;
            $firstItem = $rowChildren->item(1)->nodeValue;

            if (!empty($firstItem) && $firstItem != 'Year') {
//                if ($rowChildren->item(1)->nodeValue != $info->college) {
//                    return false;
//                }
                $year = $rowChildren->item(0)->nodeValue;
                $year = str_replace("*", "", $year);
                if ($year == "Career") {
                    continue;
                }
                if (! $rowChildren->item(1)->firstChild instanceof \DOMElement) {
                    return false;
                }
                $collegeHref = $rowChildren->item(1)->firstChild->getAttribute("href");
                try {
                    $totals = $this->getCollegeTotals($collegeHref);
                } catch (\Exception $e) {
                    return false;
                }
                if (!empty($year)) {
                    $collegeStats[$year]['totals'] = $totals;
                    $collegeStats[$year]['year'] = $year;
                    $collegeStats[$year]['college'] = $rowChildren->item(1)->nodeValue;
                    $collegeStats[$year]['conference'] = $rowChildren->item(2)->nodeValue;
                    $collegeStats[$year]['class'] = $rowChildren->item(3)->nodeValue;
                    $collegeStats[$year]['position'] = $rowChildren->item(4)->nodeValue;
                    $collegeStats[$year]['games'] = $rowChildren->item(5)->nodeValue;
                    $collegeStats[$year]['rushAtt'] = $rowChildren->item(6)->nodeValue;
                    $collegeStats[$year]['rushYds'] = $rowChildren->item(7)->nodeValue;
                    $collegeStats[$year]['rushAvg'] = $rowChildren->item(8)->nodeValue;
                    $collegeStats[$year]['rushTds'] = $rowChildren->item(9)->nodeValue;
                    $collegeStats[$year]['recs'] = $rowChildren->item(10)->nodeValue;
                    $collegeStats[$year]['recYds'] = $rowChildren->item(11)->nodeValue;
                    $collegeStats[$year]['recAvg'] = $rowChildren->item(12)->nodeValue;
                    $collegeStats[$year]['recTds'] = $rowChildren->item(13)->nodeValue;
                    $collegeStats[$year]['scrimmageYds'] = $rowChildren->item(15)->nodeValue;
                    $collegeStats[$year]['scrimmageTds'] = $rowChildren->item(16)->nodeValue;
//                    $collegeStats[$year]['ydsDominator'] = (round($collegeStats[$year]['scrimmageYds'] / $totals['yds'], 4)) * 100;
//                    $collegeStats[$year]['recDominator'] = (round($collegeStats[$year]['recs'] / $totals['recs'], 4)) * 100;
//                    $collegeStats[$year]['tdDominator'] = (round($collegeStats[$year]['scrimmageTds'] / $totals['tds'], 4)) * 100;
                }
            }
            // $result is a DOMElement
        }

        $rb->setCollegeStats($collegeStats);
        $this->command->save($rb);
        return true;
    }

    public function getCollegeTotals($href)
    {
        $request = new Request();
        $uri = "https://www.sports-reference.com{$href}";
        $request->setUri($uri);

        $client = new Client();
        $response = $client->send($request);
        $html = $response->getBody();

        $dom = new Query($html);
        $results = $dom->execute('#team tr');
        $count = count($results);
        $totals = [];
        foreach ($results as $result) {
            $rowChildren = $result->childNodes;
            $firstItem = $rowChildren->item(0)->nodeValue;
            if ($firstItem == "Offense") {
                $games = $rowChildren->item(1)->nodeValue;
                $rushing = $rowChildren->item(8)->nodeValue;
                $scrimmage = $rowChildren->item(12)->nodeValue;
                $totals['rushing'] = $games * $rushing;
                $totals['scrimmage'] = $games * $scrimmage;
            }
        }

        $weird = strpos($html, '<div class="overthrow table_container" id="div_rushing_and_receiving">');
        // $pos = ‌‌strpos($html, '<div class="overthrow table_container" id="div_rushing_and_receiving">');
        $newhtml =  substr($html, $weird);

        $dom = new Query($newhtml);
        $results = $dom->execute('#rushing_and_receiving tr');
        $count = count($results);
        $totals['recs'] = 0;
        $totals['yds'] = 0;
        $totals['tds'] = 0;
        $totals['carries'] = 0;
        foreach ($results as $result) {
            $rowChildren = $result->childNodes;
            $firstItem = $rowChildren->item(0)->nodeValue;
            if ($firstItem > 0.5) {
                $carries = $rowChildren->item(2)->nodeValue;
                $totals['carries'] = $carries + $totals['carries'];
                $recs = $rowChildren->item(6)->nodeValue;
                $totals['recs'] = $recs + $totals['recs'];
                $yds = $rowChildren->item(11)->nodeValue;
                $totals['yds'] = $yds + $totals['yds'];
                $tds = $rowChildren->item(13)->nodeValue;
                $totals['tds'] = $tds + $totals['tds'];
            }
        }

        return $totals;
    }
}