<?php

    $this->headTitle('Add User');
    $form->get('email')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'name@example.com'
    ]);
    $form->get('firstName')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'John Doe'
    ]);
    $form->get('lastName')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'John Doe'
    ]);
    $form->get('status')->setAttributes([
        'class'=>'form-control'
    ]);
    $form->get('password')->setAttributes([
        'class'=>'form-control'
    ]);
    $form->get('confirm_password')->setAttributes([
        'class'=>'form-control'
    ]);
    $form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
    $form->prepare();
    ?>
<div class="section white full-height container">
    <div class="container">
<h3>Add User</h3>

<p class="black-text">
    Please fill out the following form and click the <i>Create</i> button.
</p>

<div class="row">
    <div class="col s6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('firstName')); ?>
            <?= $this->formElement($form->get('firstName')); ?>
            <?= $this->formElementErrors($form->get('firstName')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('lastName')); ?>
            <?= $this->formElement($form->get('lastName')); ?>
            <?= $this->formElementErrors($form->get('lastName')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <?= $this->formElementErrors($form->get('password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('confirm_password')); ?>
            <?= $this->formElement($form->get('confirm_password')); ?>
            <?= $this->formElementErrors($form->get('confirm_password')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
    </div>
</div>