<?php
$this->headTitle('Edit User');
//$this->mainMenu()->setActiveItemId('users');
//$this->pageBreadcrumbs()->setItems([
//    'Home'=>$this->url('home'),
//    'Manage Users'=>$this->url('users'),
//    'Edit User'=>$this->url('users', ['action'=>'edit', 'id'=>$user->getId()])
//]);
$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'name@example.com'
]);
$form->get('firstName')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'John Doe'
]);
$form->get('lastName')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'John Doe'
]);
$form->get('status')->setAttributes([
    'class'=>'form-control'
]);
$form->get('submit')
    ->setAttributes(['class'=>'btn btn-primary'])
    ->setValue('Save');
$form->prepare();
?>
<div class="section white full-height container">
    <div class="container">
<h3>Edit User <?= $this->escapeHtml($user->getEmail()) ?></h3>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('firstName')); ?>
            <?= $this->formElement($form->get('firstName')); ?>
            <?= $this->formElementErrors($form->get('firstName')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('lastName')); ?>
            <?= $this->formElement($form->get('lastName')); ?>
            <?= $this->formElementErrors($form->get('lastName')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>
    </div>
</div>
