
<?php
$this->headTitle('View User');
$this->mainMenu()->setActiveItemId('users');
$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Manage Users'=>$this->url('users'),
    'View User'=>$this->url('users', ['action'=>'view', 'id'=>$user->getId()])
]);

?>


<div class="section white full-height container">
    <div class="container">
        <?= $this->pageBreadcrumbs()->render() ?>
        <h3>View User</h3>
        <div class="row">
            <div class="col-md-6">
                <table class="table table-striped table-bordered container">
                    <tr>
                        <th>ID:</th>
                        <td><?= $this->escapeHtml($user->getId()) ?></th>
                    </tr>
                    <tr>
                        <th>E-mail:</th>
                        <td><?= $this->escapeHtml($user->getEmail()) ?></th>
                    </tr>
                    <tr>
                        <th>Full Name:</th>
                        <td><?= $this->escapeHtml($user->getFullName()) ?></th>
                    </tr>
                    <tr>
                        <th>Date Created:</th>
                        <td><?= $this->escapeHtml($user->getDateCreated()) ?></th>
                    </tr>
                    <tr>
                        <th>Status:</th>
                        <td><?= $this->escapeHtml($user->getStatusAsString()) ?></th>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>