<div class="section container full-height white">
    <div class="row container">
<h3>Add an Article</h3>

        <?php
        $form = $this->form;
        $form->setAttribute('action', $this->url());

        $fieldset = $form->get('post');

        $title = $fieldset->get('title');

//        $text = $fieldset->get('text');
//        $text->setAttribute('class', 'form-control');
//        $text->setAttribute('placeholder', 'Post content');

        $submit = $form->get('submit');
        $submit->setAttribute('class', 'btn btn-primary');

        $form->prepare();

        echo $this->form()->openTag($form);
        ?>


        <div class="row">
            <form class="col s12">
                <div class="row">
                    <div class="input-field col s7">
                        <?= $this->formElement($fieldset->get('title')) ?>
                        <?= $this->formLabel($fieldset->get('title')) ?>
                        <?= $this->formElementErrors()->render($fieldset->get('title'), ['class' => 'help-block']) ?>
                    </div>
                    <div class="input-field col s5">
                        <?= $this->formElement($fieldset->get('originalUrl')) ?>
                        <?= $this->formLabel($fieldset->get('originalUrl')) ?>
                        <?= $this->formElementErrors()->render($fieldset->get('originalUrl'), ['class' => 'help-block']) ?>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s6">
                        <?= $this->formElement($fieldset->get('headline')) ?>
                        <?= $this->formLabel($fieldset->get('headline')) ?>
                        <?= $this->formElementErrors()->render($fieldset->get('headline'), ['class' => 'help-block']) ?>
                    </div>
                    <div class="file-field input-field col s6">
                        <div class="btn">
                            <span>Main Image</span>
                            <?= $this->formElement($fieldset->get('file')) ?>
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" type="text">
                        </div>
                    </div>
                    <div class="input-field col s12">
                        <?= $this->formElement($fieldset->get('summary')) ?>
                        <?= $this->formLabel($fieldset->get('summary')) ?>
                        <?= $this->formElementErrors()->render($fieldset->get('summary'), ['class' => 'help-block']) ?>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        <label for="textarea1">Textarea</label>
                        <textarea id="textarea1" class="materialize-textarea"></textarea>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s5">
                        <?= $this->formElement($fieldset->get('author')) ?>
                        <?= $this->formLabel($fieldset->get('author')) ?>
                        <?= $this->formElementErrors()->render($fieldset->get('author'), ['class' => 'help-block']) ?>
                    </div>
                    <div class="input-field col s5">
                        <?= $this->formElement($fieldset->get('publishDate')) ?>
                        <?= $this->formLabel($fieldset->get('publishDate')) ?>
                        <?= $this->formElementErrors()->render($fieldset->get('publishDate'), ['class' => 'help-block']) ?>
                    </div>
                    <div class="input-field col s2">
                        <div class="switch">
                            <label>
                                InActive
                                <?= $this->formElement($fieldset->get('active')) ?>
                                <span class="lever"></span>
                                Active
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group col m6 my-2">
                    <?= $this->formSubmit($submit) ?>
                </div>

                <?php
                echo $this->formHidden($fieldset->get('id'));
                ?>

            </form>
        </div>


    </div>
</div>
<script>tinymce.init({selector:'textarea'});</script>