<?php
/**
 * Created by IntelliJ IDEA.
 * User: tcook
 * Date: 3/22/19
 * Time: 8:46 AM
 */

namespace Player\Controller;

use Player\Model\Player;
use Player\Model\Player\PlayerCommandInterface;
use Player\Model\Player\PlayerRepositoryInterface;
use Player\Service\PlayerManager;
use Zend\Mvc\Controller\AbstractActionController;
use Zend\View\Model\ViewModel;


class ScriptController extends AbstractActionController
{
    private $command;
    private $repository;
    private $playerManager;

    public function __construct(
        PlayerCommandInterface $command,
        PlayerRepositoryInterface $repository,
        PlayerManager $playerManager
    )
    {
        $this->command = $command;
        $this->repository = $repository;
        $this->playerManager = $playerManager;
    }

    public function indexAction()
    {
        return parent::indexAction(); // TODO: Change the autogenerated stub
    }

    public function updateWrMetricsAction()
    {
        $this->playerManager->updateWrMetrics();
//        $type = "QB";
////        $this->qbCommand->calculateMetrics($type);
////        $this->qbCommand->calculatePercentiles($type);
//        $this->qbCommand->calculateSpecialScores($type);
//        $this->qbCommand->calculateSpecialPercentiles($type);
//
//        $type = "CB";
//        $this->cbCommand->calculateMetrics($type);
//        $this->cbCommand->calculatePercentiles($type);
//        $this->cbCommand->calculateSpecialScores($type);
//        $this->cbCommand->calculateSpecialPercentiles($type);
//
//        $type = "ILB";
//        $this->ilbCommand->calculateMetrics($type);
//        $this->ilbCommand->calculatePercentiles($type);
//        $this->ilbCommand->calculateSpecialScores($type);
//        $this->ilbCommand->calculateSpecialPercentiles($type);
//
//        $type = "OLB";
//        $this->olbCommand->calculateMetrics($type);
//        $this->olbCommand->calculatePercentiles($type);
//        $this->olbCommand->calculateSpecialScores($type);
//        $this->olbCommand->calculateSpecialPercentiles($type);
//
//        $type = "DL";
//        $this->dlCommand->calculateMetrics($type);
//        $this->dlCommand->calculatePercentiles($type);
//        $this->dlCommand->calculateSpecialScores($type);
//        $this->dlCommand->calculateSpecialPercentiles($type);



//        $type = "DL";
//        $this->dlCommand->calculateMetrics($type);
//        $this->dlCommand->calculatePercentiles($type);
//        $type = "OLB";
//        $this->olbCommand->calculateMetrics($type);
//        $this->olbCommand->calculatePercentiles($type);
//        $type = "ILB";
//        $this->ilbCommand->calculateMetrics($type);
//        $this->ilbCommand->calculatePercentiles($type);
//        $type = "CB";
//        $this->cbCommand->calculateMetrics($type);
//        $this->cbCommand->calculatePercentiles($type);
//        $type = "FS";
//        $this->fsCommand->calculateMetrics($type);
//        $this->fsCommand->calculatePercentiles($type);
//        $type = "SS";
//        $this->ssCommand->calculateMetrics($type);
//        $this->ssCommand->calculatePercentiles($type);

//        $type = "WR";
//        $this->wrCommand->calculateMetrics($type);
//        $this->wrCommand->calculatePercentiles($type);
//        $this->wrCommand->calculateSpecialScores($type);
//        $this->wrCommand->calculateSpecialPercentiles($type);
    }

    public function updateRbMetricsAction()
    {
//        $type = "RB";
//        $this->rbCommand->calculateMetrics($type);
//        $this->rbCommand->calculatePercentiles($type);
//        $this->rbCommand->calculateSpecialScores($type);
//        $this->rbCommand->calculateSpecialPercentiles($type);
    }

    public function updateTeMetricsAction()
    {
//        $type = "OL";
//        $this->olCommand->calculateMetrics($type);
//        $this->olCommand->calculatePercentiles($type);
//        $this->olCommand->calculateSpecialScores($type);
//        $this->olCommand->calculateSpecialPercentiles($type);
//        $type = "TE";
//        $this->teCommand->calculateMetrics($type);
//        $this->teCommand->calculatePercentiles($type);
//        $this->teCommand->calculateSpecialScores($type);
//        $this->teCommand->calculateSpecialPercentiles($type);
    }

    public function updateOLMetricsAction()
    {
//        $type = "OL";
//        $this->olCommand->calculateMetrics($type);
//        $this->olCommand->calculatePercentiles($type);
//        $this->olCommand->calculateSpecialScores($type);
//        $this->olCommand->calculateSpecialPercentiles($type);
    }

    public function dataScrapperAction()
    {
        $this->qbCommand->scrapCollegeJob();
    }

    public function getSleeperStatsAction()
    {
        $this->command->getSleeperStats();
    }

    public function makeNameJsonAction()
    {
       $json = $this->repository->getPlayerNames('Off');
       file_put_contents('public/data/names.json', json_encode($json));
    }

    public function updateSleeperInfoAction()
    {
        $this->playerManager->updateSleeperInfo();
    }

    public function getSleeperLogsAction()
    {
        $this->command->getSleeperGameLogs();
    }
}