<!doctype html>
<html>
<head>

    <meta charset="utf-8">
    <?= $this->headTitle("Draft Trade Win | Fantasy Football")->setSeparator(' | ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.png'])
        ->appendStylesheet("https://fonts.googleapis.com/icon?family=Material+Icons")
        ->appendStylesheet($this->basePath('css/materialize.css'))
        ->appendStylesheet("https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css")
        ->appendStylesheet($this->basePath('css/startup-materialize.css'))
        ->appendStylesheet($this->basePath('css/new_rlf.css'))
        ->appendStylesheet("https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.css");
    ?>

    <!-- External Scripts -->
    <?= $this->headScript()
        ->appendFile('https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js')
        ->appendFile("https://cdn.plot.ly/plotly-latest.min.js")
        ->appendFile("https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js")
        ->appendFile($this->basePath("js/twitter/typeahead.js/dist/typeahead.bundle.js"))
        ->appendFile($this->basePath("js/twitter/typeahead.js/dist/bloodhound.js"))
        ->appendFile($this->basePath("js/imagesloaded.pkgd.min.js"))
        ->appendFile($this->basePath("js/masonry.pkgd.min.js"))
        ->appendFile($this->basePath("js/TweenMax.min.js"))
        ->appendFile($this->basePath("js/ScrollMagic.min.js"))
        ->appendFile("https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js")
        ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/tinymce/5.7.1/tinymce.min.js')
        ->appendFile('https://unpkg.com/freezeframe/dist/freezeframe.min.js')
        ->appendFile($this->basePath("js/animation.gsap.min.js"));
    ?>

    <!-- Initialization Scripts -->
    <?= $this->headScript()
        ->appendFile($this->basePath('js/materialize.js'))
        ->appendFile($this->basePath('js/startup.js'))
        ->appendFile($this->basePath('js/init.js'))
        ->appendFile($this->basePath("/js/rlfPlayer.js"))
        ->appendFile($this->basePath("/js/rlfMatchup.js"));
    ?>

    <script async src="https://www.googletagmanager.com/gtag/js?id=G-41VYVC57MQ"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-41VYVC57MQ');
    </script>

    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-2208849449045688",
            enable_page_level_ads: true
        });
    </script>
    <script src="https://kit.fontawesome.com/4e552e909b.js"></script>
</head>
<?php
$mobileDetect = $this->mobileDetect(); //Retrieve "\Mobile_Detect" object
if ($mobileDetect->isMobile() == true) {
    $mobileClass = "mobile";
} else {
    $mobileClass = "";
}
?>

<body class="<?=$mobileClass?>">

<!-- Navbar -->
<nav class="dark">
    <div class="nav-wrapper">
        <div class="container">
            <a href="/" class="brand-logo">Draft Trade Win</a>
            <ul id="nav-mobile" class="right hide-on-med-and-down">
                <li><a href="/player/search">Player Research</a></li>
<!--                <li><a href="/podcasts">Podcasts</a></li>-->
                <li><a href="/player/rankings">Rankings</a></li>
                <li><a href="/articles">Articles</a></li>

            </ul>

            <!--<ul id="pages" class="dropdown-content">-->
            <!--<li><a class="active" href="horizontal-half.html">Horizontal Halves</a></li>-->
            <!--<li><a href="sierra.html">Zoom Out</a></li>-->
            <!--<li><a href="circle-reveal.html">Circle Reveal</a></li>-->
            <!--<li><a href="phone-wall.html">Phone Wall</a></li>-->
            <!--<li><a href="element-transitions.html">Element Transitions</a></li>-->
            <!--<li><a href="basic-elements.html">Basic Elements</a></li>-->
            <!--<li><a href="card-shuffle.html">Shuffle</a></li>-->
            <!--<li><a href="postcards.html">Postcards</a></li>-->
            <!--</ul>-->

            <a href="#" data-target="slide-out" class="sidenav-trigger button-collapse right"><i class="material-icons white-text">menu</i></a>
        </div>
    </div>
</nav>
<ul id="slide-out" class="sidenav">
<!--    <li class="no-padding">-->
<!--        <ul class="collapsible collapsible-accordion">-->
<!--            <li class="bold">-->
<!--                <a class="collapsible-header waves-effect waves-teal active">Pages</a>-->
<!--                <div class="collapsible-body">-->
<!--                    <ul>-->
<!--                        <li><a href="/player/search">Player Research</a></li>-->
<!--                        <li><a href="/podcasts">Podcasts</a></li>-->
<!--                        <li><a href="/player/rankings">Rankings</a></li>-->
<!--                        <li><a href="/threads">Threads</a></li>-->
<!--                    </ul>-->
<!--                </div>-->
<!--            </li>-->
<!--        </ul>-->
<!--    </li>-->
    <li><a class="waves-effect waves-teal" href="/player/search">Player Research</a></li>
<!--    <li><a class="waves-effect waves-teal" href="/podcasts">Podcasts</a></li>-->
    <li><a class="waves-effect waves-teal" href="/player/rankings">Rankings</a></li>
    <li><a class="waves-effect waves-teal" href="/articles">Articles</a></li>
</ul>

<?= $this->content ?>

<!-- Footer -->
<footer class="page-footer">
    <div class="container">
        <div class="row">
            <div class="col s3 m3">
                <h5>About</h5>
                <ul>
                    <li><a href="/about">What is This?</a></li>
                </ul>
            </div>
            <div class="col s9 m9">
                <ul>
                    <li><h5>Follow us on Twitter<a href="https://twitter.com/drafttradewin"><span class="teal-text bold">&nbsp;@DraftTradeWin<i class="fab fa-twitter"></i></span></a></h5></li>
                    <li><h5>Email @<a href="mailto:relllifefantasy@gmail.com"><span class="teal-text">&nbsp;relllifefantasy@gmail.com <i class="fab fa-twitter"></i></span></a></h5></li>
                </ul>
            </div>
        </div>
    </div>
</footer>


<script src="<?=$this->basePath("js/materialize.min.js")?>"></script>
<script>
    $(document).ready(function(){
        $('.tabs').tabs();
        $('.scrollspy').scrollSpy();

        $('.modal').modal();

        $('.carousel.carousel-slider').carousel({
            fullWidth: true,
            indicators: true,
        });

        $('.parallax').parallax();

        setInterval(function() {
            $('.carousel.carousel-slider').carousel('next');
        }, 5000);
    });

</script>

<!-- External libraries -->


<!--<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>-->


<!-- Initialization script -->

</body>
</html>