<div class="section white full-height container center">
    <h3>Manage Articles</h3>

    <div class="row">
        <div class="btn-group" role="group" aria-label="Post actions">
            <a class="btn btn-primary dark" href="<?= $this->url('cms/add') ?>">Write new post</a>
        </div>
    </div>

    <div class="row">
        <table class="table table-striped container">
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>URL</th>
                <th>Image</th>
                <th>Date Created</th>
                <th>Status</th>
                <th>Actions</th>
            </tr>

            <?php foreach ($this->posts as $post): ?>
                <tr>
                    <td><?= $this->escapeHtml($post->getId()); ?></td>
                    <td>
                        <a href="<?= $this->url('cms', ['action'=>'cms', 'id'=>$post->getId()]); ?>">
                            <?= $this->escapeHtml($post->getTitle()); ?>
                        </a>
                    </td>
                    <td><?= $this->escapeHtml($post->getOriginalUrl()); ?>
                    </td>
                    <td>
                        <img class="freezeframe" width="100" height="100" src="<?= $this->escapeHtml($post->getImage()); ?>"/>
                    </td>
                    <td><?= $this->escapeHtml($post->getPublishDate()); ?></td>
                    <td><?= $this->escapeHtml($post->getActive()); ?></td>
                    <td>
                        <a class="btn btn-info dark" href="<?= $this->url('cms/edit', ['id'=>$post->getId()]); ?>">
                            <span class="glyphicon glyphicon-pencil" ></span> Edit
                        </a>
                        <a class="btn btn-default dark" href="<?= $this->url('cms/delete',['id'=>$post->getId()]); ?>">
                            <span class="glyphicon glyphicon-asterisk"></span> Delete
                        </a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </table>
    </div>
</div>

<script>
    $(document).ready({
        new Freezeframe();
    });
</script>