<?php
$form = $this->form;
$fieldset = $form->get('post');

$title = $fieldset->get('title');
$title->setAttribute('class', 'form-control');
$title->setAttribute('placeholder', 'Post title');

$text = $fieldset->get('text');
$text->setAttribute('class', 'form-control');
$text->setAttribute('placeholder', 'Post content');

$submit = $form->get('submit');
$submit->setValue($this->submitLabel);
$submit->setAttribute('class', 'btn btn-primary');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="row container">
    <div class="row">
        <form class="col s12">
            <div class="row">
                <div class="input-field col s7">
                    <?= $this->formElement($fieldset->get('title')) ?>
                    <?= $this->formLabel($fieldset->get('title')) ?>
                    <?= $this->formElementErrors()->render($fieldset->get('title'), ['class' => 'help-block']) ?>
                </div>
                <div class="input-field col s5">
                    <?= $this->formElement($fieldset->get('originalUrl')) ?>
                    <?= $this->formLabel($fieldset->get('originalUrl')) ?>
                    <?= $this->formElementErrors()->render($fieldset->get('originalUrl'), ['class' => 'help-block']) ?>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s6">
                    <?= $this->formElement($fieldset->get('headline')) ?>
                    <?= $this->formLabel($fieldset->get('headline')) ?>
                    <?= $this->formElementErrors()->render($fieldset->get('headline'), ['class' => 'help-block']) ?>
                </div>
                <div class="file-field input-field col s6">
                    <?= $this->formElement($fieldset->get('image')) ?>
                    <?= $this->formLabel($fieldset->get('image')) ?>
                    <?= $this->formElementErrors()->render($fieldset->get('image'), ['class' => 'help-block']) ?>
                </div>
                <div class="input-field col s12">
                    <?= $this->formElement($fieldset->get('summary')) ?>
                    <?= $this->formLabel($fieldset->get('summary')) ?>
                    <?= $this->formElementErrors()->render($fieldset->get('summary'), ['class' => 'help-block']) ?>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s12">
                    <label for="textarea1">Textarea</label>
                    <?= $this->formElement($fieldset->get('text')) ?>
                </div>
            </div>
            <div class="row">
                <div class="input-field col s5">
                    <?= $this->formElement($fieldset->get('author')) ?>
                    <?= $this->formLabel($fieldset->get('author')) ?>
                    <?= $this->formElementErrors()->render($fieldset->get('author'), ['class' => 'help-block']) ?>
                </div>
                <div class="input-field col s5">
                    <?= $this->formElement($fieldset->get('publishDate')) ?>
                    <?= $this->formLabel($fieldset->get('publishDate')) ?>
                    <?= $this->formElementErrors()->render($fieldset->get('publishDate'), ['class' => 'help-block']) ?>
                </div>
                <div class="input-field col s2">
                    <div class="switch">
                        <label>
                            InActive
                            <?= $this->formElement($fieldset->get('active')) ?>
                            <span class="lever"></span>
                            Active
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group col m6 my-2">
                <?= $this->formSubmit($submit) ?>
            </div>

            <?php
            echo $this->formHidden($fieldset->get('id'));
            ?>

        </form>
    </div>

</div>
<script>
    tinymce.init({
        selector: "textarea",
        // setup: function(ed) {
        //     ed.on("change", function(e) {
        //         $("#preview-html-"+letter).html(ed.getContent());
        //         $("#edit-text-"+letter).val(ed.getContent({format:"text"}));
        //     });
        //     ed.on("keyup", function(e) {
        //         $("#preview-html-"+letter).html(ed.getContent());
        //         $("#edit-text-"+letter).val(ed.getContent({format:"text"}));
        //     });
        // },
        plugins: [
            "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
            "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
            "save contextmenu directionality emoticons template paste textcolor visualblocks table"
        ],
        toolbar: "fontsizeselect bold italic forecolor alignleft aligncenter alignright alignjustify link unlink image media  undo redo removeformat formats table",
        fontsize_formats: "8pt 10pt 12pt 14pt 16pt 18pt 20pt 22pt 24pt 28pt 36pt",
        style_formats: [
            { title: 'Headers', items: [
                    { title: 'h1', block: 'h1' },
                    { title: 'h2', block: 'h2' },
                    { title: 'h3', block: 'h3' },
                    { title: 'h4', block: 'h4' },
                    { title: 'h5', block: 'h5' },
                    { title: 'h6', block: 'h6' }
                ] },

            { title: 'Blocks', items: [
                    { title: 'p', block: 'p' },
                    { title: 'div', block: 'div' },
                    { title: 'pre', block: 'pre' }
                ] },

            { title: 'Containers', items: [
                    { title: 'section', block: 'section', wrapper: true, merge_siblings: false },
                    { title: 'article', block: 'article', wrapper: true, merge_siblings: false },
                    { title: 'blockquote', block: 'blockquote', wrapper: true },
                    { title: 'hgroup', block: 'hgroup', wrapper: true },
                    { title: 'aside', block: 'aside', wrapper: true },
                    { title: 'figure', block: 'figure', wrapper: true }
                ] }
        ],
        table_toolbar: "tableprops tabledelete | tableinsertrowbefore tableinsertrowafter tabledeleterow | tableinsertcolbefore tableinsertcolafter tabledeletecol",
        end_container_on_empty_block: true,
        relative_urls : false,
        remove_script_host: false,
        convert_urls: false
    });
</script>
