<?php
// module/Album/view/album/album/index.phtml:

$title = 'What is Draft Trade Win?';
$this->headTitle($title);
?>
<div class="section container full-height page">
    <div class="row container">
        <h2><?= $this->escapeHtml($title) ?></h2>
        <p class="tagline">Draft Trade Win is the ultimate resource for fantasy football research. We provide unique tools to help you dominate whether you are playing seasonal, dynasty, best ball or daily fantasy. We offer unique position based metrics based on workout metrics and college production. These metrics help to predict exactly how a player will win at the next level and what roles they are likely to excel at. We also offer rankings, podcasts, twitter threads and a player comparison tool with more features to come.</p>

          <p>  Credits:
            Pro Football Reference
            NFL.com</p>
    </div>
</div>