<div class="header full-height horizontal-half-transition">
    <div class="background">
        <img src="/images/chalkboard.jpg" alt="">
    </div>
    <div class="desktop-preview-sizer">
        <div class="desktop-preview"></div>
        <div class="image-container active" style="background-image:url(/images/JuJu.png)"></div>
        <div class="image-container" style="background-image:url(/images/baker.png)"></div>
        <div class="image-container" style="background-image:url(/images/compare.png)"></div>
    </div>
    <div class="horizontal-half-wrapper right-side active">
        <div class="header-background white"></div>
        <div class="header-wrapper row valign-wrapper">
            <div class="col s12 m8 offset-m2 valign">
                <h1>Draft.<br><span class="purple-text">Trade.</span><br>Win.</h1>
                <span class="tagline">A football analytics super-site to help you dominate fantasy football.</span>
                <button class="read-more"><i class="icon-caret-down"></i></button>
            </div>
        </div>
    </div>
    <div class="horizontal-half-wrapper">
        <div class="header-background white"></div>
        <div class="header-wrapper row valign-wrapper">
            <div class="col s12 m8 offset-m2 valign">
                <h1>Smarter <span class="purple-text">Player</span> Pages</h1>
                <span class="tagline">Detailed Info on every player. Metrics to highlight exactly what players will excel at.</span>
                <button class="read-more"><i class="icon-caret-down"></i></button>
            </div>
        </div>
    </div>
    <div class="horizontal-half-wrapper right-side">
        <div class="header-background white"></div>
        <div class="header-wrapper row valign-wrapper">
            <div class="col s12 m8 offset-m2 valign">
                <h1>Compare<span class="purple-text"> Players</span></h1>
                <span class="tagline">Settle your arguments here. Compare players on multiple levels, performance, combine metrics, atheltic profiles and more</span>
                <button class="read-more"><i class="icon-caret-down"></i></button>
            </div>
        </div>
    </div>
</div>

<div class="section valign-wrapper">
    <div class="row valign">
        <div class="col s12 m10 offset-m1">
            <div class="row staggered-transition-wrapper" data-duration="0" data-staggereddelay=".9">
                <div class="col s12"><h2 class="section-title">Features</h2></div>
                <div class="col s12 m6 l4 fade-in-out">
                    <h4><i class="icon-light-bulb"></i>&nbsp;&nbsp;Smart Player Pages</h4>
                    <p class="caption">Gifs and Detailed Info on every player. College scores, interactive game logs and more ...</p>
                </div>
                <div class="col s12 m6 l4 fade-in-out">
                    <h4><i class="icon-bolt"></i>&nbsp;&nbsp;Easy Metrics</h4>
                    <p class="caption">Metrics to highlight exactly what players will excel at and what roles they are best suited for</p>
                </div>
                <div class="col s12 m6 l4 fade-in-out">
                    <h4><i class="icon-rocket"></i>&nbsp;&nbsp;Compare Players</h4>
                    <p class="caption">Compare players on multiple levels, performance, combine metrics, atheltic profiles and more</p>
                </div>
                <div class="col s12 m6 l4 fade-in-out">
                    <h4><i class="icon-settings"></i>&nbsp;&nbsp;Player Rankings</h4>
                    <p class="caption">Best Player Rankings on Earth.</p>
                </div>
                <div class="col s12 m6 l4 fade-in-out">
                    <h4><i class="icon-umbrella"></i>&nbsp;&nbsp;Podcasts</h4>
                    <p class="caption">Best Fantasy Football Podcast on Earth</p>
                </div>
                <div class="col s12 m6 l4 fade-in-out">
                    <h4><i class="icon-compass"></i>&nbsp;&nbsp;Twitter threads</h4>
                    <p class="caption">Best Twitter Threads on Earth</p>
                </div>
            </div>
        </div>
    </div>
</div>


<!-- Pricing Tables -->
<!--<div class="section valign-wrapper">-->
<!--    <div class="row valign">-->
<!--        <div class="col s12 m10 offset-m1">-->
<!--            <div class="row">-->
<!--                <div class="col s12 m4">-->
<!--                    <div class="pricing-table">-->
<!--                        <div class="pricing-header">-->
<!--                            <i class="icon-paper-plane"></i>-->
<!--                            <h4>Basic</h4>-->
<!--                            <div class="price">-->
<!--                                <span class="currency">$</span>-->
<!--                                <span class="dollars">9</span>-->
<!--                                <span class="cents">99</span>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <ul class="pricing-features">-->
<!--                            <li class="pricing-feature"><i class="icon-accept"></i>10 product uses.</li>-->
<!--                            <li class="pricing-feature"><i class="icon-accept"></i>10 product uses.</li>-->
<!--                            <li class="pricing-feature"><i class="icon-accept"></i>10 product uses.</li>-->
<!--                            <li class="pricing-feature disabled"><i class="icon-close"></i>Pro and above.</li>-->
<!--                            <li class="pricing-feature disabled"><i class="icon-close"></i>Enterprise only.</li>-->
<!--                            <li class="pricing-feature disabled"><i class="icon-close"></i>Enterprise only.</li>-->
<!--                            <li class="pricing-feature disabled"><i class="icon-close"></i>Enterprise only.</li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!---->
<!--                <div class="col s12 m4">-->
<!--                    <div class="pricing-table featured">-->
<!--                        <div class="pricing-header">-->
<!--                            <i class="icon-plane"></i>-->
<!--                            <h4>Pro</h4>-->
<!--                            <div class="price">-->
<!--                                <span class="currency">$</span>-->
<!--                                <span class="dollars">59</span>-->
<!--                                <span class="cents">99</span>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <ul class="pricing-features">-->
<!--                            <li class="pricing-feature"><i class="icon-accept"></i>10 product uses.</li>-->
<!--                            <li class="pricing-feature"><i class="icon-accept"></i>10 product uses.</li>-->
<!--                            <li class="pricing-feature"><i class="icon-accept"></i>10 product uses.</li>-->
<!--                            <li class="pricing-feature"><i class="icon-accept"></i>Pro and above.</li>-->
<!--                            <li class="pricing-feature disabled"><i class="icon-close"></i>Enterprise only.</li>-->
<!--                            <li class="pricing-feature disabled"><i class="icon-close"></i>Enterprise only.</li>-->
<!--                            <li class="pricing-feature disabled"><i class="icon-close"></i>Enterprise only.</li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!---->
<!--                <div class="col s12 m4">-->
<!--                    <div class="pricing-table">-->
<!--                        <div class="pricing-header">-->
<!--                            <i class="icon-rocket"></i>-->
<!--                            <h4>Enterprise</h4>-->
<!--                            <div class="price">-->
<!--                                <span class="currency">$</span>-->
<!--                                <span class="dollars">299</span>-->
<!--                                <span class="cents">99</span>-->
<!--                            </div>-->
<!--                        </div>-->
<!--                        <ul class="pricing-features">-->
<!--                            <li class="pricing-feature"><i class="icon-accept"></i>10 product uses.</li>-->
<!--                            <li class="pricing-feature"><i class="icon-accept"></i>10 product uses.</li>-->
<!--                            <li class="pricing-feature"><i class="icon-accept"></i>10 product uses.</li>-->
<!--                            <li class="pricing-feature"><i class="icon-accept"></i>10 product uses.</li>-->
<!--                            <li class="pricing-feature"><i class="icon-accept"></i>Enterprise only.</li>-->
<!--                            <li class="pricing-feature"><i class="icon-accept"></i>Enterprise only.</li>-->
<!--                            <li class="pricing-feature"><i class="icon-accept"></i>Enterprise only.</li>-->
<!--                        </ul>-->
<!--                    </div>-->
<!--                </div>-->
<!---->
<!--            </div>-->
<!--        </div>-->
<!--    </div>-->
<!--</div>-->

<div class="section light full-height">
    <div class="row">
        <div class="col s12 m10 offset-m1 center">
            <h1>Latest Podcasts</h1>
<!--            <div class="row masonry-grid">-->
<!--                <div class="col s12 m6 l4">-->
<!--                    <div class="card">-->
<!--                        <div class="card-image">-->
<!--                            <a href="blog.html"><img src="http://placehold.it/600x400"></a>-->
<!--                            <span class="card-title">Something Interesting</span>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="col s12 m6 l4">-->
<!--                    <div class="card">-->
<!--                        <div class="card-image">-->
<!--                            <a href="blog.html"><img src="http://placehold.it/600x400"></a>-->
<!--                            <span class="card-title">Another Blog Post</span>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="col s12 m6 l4">-->
<!--                    <div class="card">-->
<!--                        <div class="card-image">-->
<!--                            <a href="blog.html"><img src="http://placehold.it/600x400"></a>-->
<!--                            <span class="card-title">Click Bait Article</span>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="col s12 m6 l4">-->
<!--                    <div class="card">-->
<!--                        <div class="card-image">-->
<!--                            <a href="blog.html"><img src="http://placehold.it/600x400"></a>-->
<!--                            <span class="card-title">Don't Read This!</span>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="col s12 m6 l4">-->
<!--                    <div class="card">-->
<!--                        <div class="card-image">-->
<!--                            <a href="blog.html"><img src="http://placehold.it/600x400"></a>-->
<!--                            <span class="card-title">Why Are You Still Reading?</span>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--                <div class="col s12 m6 l4">-->
<!--                    <div class="card">-->
<!--                        <div class="card-image">-->
<!--                            <a href="blog.html"><img src="http://placehold.it/600x400"></a>-->
<!--                            <span class="card-title">Good Bye</span>-->
<!--                        </div>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
        </div>
    </div>
</div>

<!-- Contact Us -->
<!--<div class="section light valign-wrapper">-->
<!--    <div class="container">-->
<!--        <form>-->
<!--            <div class="row">-->
<!--                <div class="col s12"><h2 class="section-title">Contact Us</h2></div>-->
<!--                <div class="input-field col s6">-->
<!--                    <input id="first_name" type="text">-->
<!--                    <label for="first_name">First Name</label>-->
<!--                </div>-->
<!--                <div class="input-field col s6">-->
<!--                    <input id="last_name" type="text">-->
<!--                    <label for="last_name">Last Name</label>-->
<!--                </div>-->
<!--                <div class="input-field col s12">-->
<!--                    <textarea id="message" class="materialize-textarea"></textarea>-->
<!--                    <label for="message">Message</label>-->
<!--                    <a class="waves-effect waves-light btn-large">Button</a>-->
<!--                </div>-->
<!--            </div>-->
<!--        </form>-->
<!--    </div>-->
<!--</div>-->