<?php
// module/Album/view/album/album/index.phtml:

$title = 'Twitter Threads';
$this->headTitle($title);
?>
<div class="section container full-height page">
    <div class="row container">
        <h1><?= $this->escapeHtml($title) ?></h1>
        <div class="col m6">
            <blockquote class="twitter-tweet"><p lang="en" dir="ltr">Word on the street is that Marlon Mack has lost all his upside with the loss of Luck. I&#39;m here to show that he is still a top 10 RB with top 5 upside. A thread. <a href="https://t.co/UfKeY4QFzG">pic.twitter.com/UfKeY4QFzG</a></p>&mdash; DraftTradeWin (@drafttradewin) <a href="https://twitter.com/drafttradewin/status/1166506035743461376?ref_src=twsrc%5Etfw">August 28, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
    </div>
</div>