<?php
// module/Album/view/album/album/index.phtml:

$title = 'Twitter Threads';
$this->headTitle($title);
?>
<div class="section container full-height page">
    <div class="row container">
        <h1><?= $this->escapeHtml($title) ?></h1>
        <div class="col m4">
            <blockquote class="twitter-tweet"><p lang="en" dir="ltr">Damien Williams has nothing to worry about. Only one RB on the roster has:<br>Lead back size + <br>Lead back athleticism + <br>Lead back performance + <br>Doesn&#39;t have 2,821 touches + <br>Has been running as the feature back all off-season.<a href="https://t.co/iUTASVRqiQ">https://t.co/iUTASVRqiQ</a><br>(Thread alert) <a href="https://t.co/R5Q2yeP3gF">pic.twitter.com/R5Q2yeP3gF</a></p>&mdash; DraftTradeWin (@drafttradewin) <a href="https://twitter.com/drafttradewin/status/1168299861860585472?ref_src=twsrc%5Etfw">September 1, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
        <div class="col m4">
            <blockquote class="twitter-tweet"><p lang="en" dir="ltr">Devin Singletary is why the size adjusted metrics <a href="https://t.co/F8ieaEHRv3">https://t.co/F8ieaEHRv3</a> matter. Looking at his combine metrics alone makes him look like a poor athlete. We have an elusiveness rating which is a combination of the shuttle and 3 cone but is BMI adjusted. <a href="https://t.co/e04JLJr0ZL">pic.twitter.com/e04JLJr0ZL</a></p>&mdash; DraftTradeWin (@drafttradewin) <a href="https://twitter.com/drafttradewin/status/1167848883659116544?ref_src=twsrc%5Etfw">August 31, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
        <div class="col m4">
            <blockquote class="twitter-tweet"><p lang="en" dir="ltr">RBs who scored more PPR ppg than the WR1<br>2015 - none &gt; AB 23<br>2016 - Bell 26, DJ 25, Zeke 21 &gt; AB 20<br>2017 - Gurley 25, Bell 22 &gt; AB 22<br>2018 - Gurley 26, McCaffery 24, Saquon 24, Kamara 23, Gordon 22, Zeke 21, Conner 21 &gt; Adams 21</p>&mdash; DraftTradeWin (@drafttradewin) <a href="https://twitter.com/drafttradewin/status/1167158600491511809?ref_src=twsrc%5Etfw">August 29, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
        <div class="col m4">
            <blockquote class="twitter-tweet"><p lang="en" dir="ltr">Word on the street is that Marlon Mack has lost all his upside with the loss of Luck. I&#39;m here to show that he is still a top 10 RB with top 5 upside. A thread. <a href="https://t.co/UfKeY4QFzG">pic.twitter.com/UfKeY4QFzG</a></p>&mdash; DraftTradeWin (@drafttradewin) <a href="https://twitter.com/drafttradewin/status/1166506035743461376?ref_src=twsrc%5Etfw">August 28, 2019</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
        </div>
    </div>
</div>